### ISSUE TITLE
When will be released the next stable version?

### ISSUE THREAD

**Issue by securez** [mongodb/mongo-php-driver#1004]
We are having a lot of problems with this module and a MongoDB cluster that is on a system with OpenSSL 1.1.1, after a bit of investigation, seems that the problem is on the libmongoc library, the problem is tracked here:

https://jira.mongodb.org/browse/CDRIVER-2846

But PHP mongodb module uses libmongoc 1.13.0 that has this bug, I already compiled the 1.6.0Alpha2 and the problem disappear, It link against libmongc 1.14.0.

¿Is there any date for the 1.6.0 stable release?

**Comment by alcaeus** [comment]
A release is currently planned shortly after the release of MongoDB 4.2 GA, which will happen next week. I can't give you a more specific date yet.

**Comment by securez** [comment]
Hi  @alcaeus a lot of thanks for your fast reply, I'll be aware of the updates next week. A specific date is not required, this issues can be marked as question and closed.
