### ISSUE TITLE
Connecting Laravel project to mongodb fails. Returns the the error "No suitable servers found (`serverSelectionTryOnce` set: ...):"

### ISSUE THREAD

**Issue by laingmedia** [mongodb/mongo-php-driver#1045]
Hi,

Im working on connecting my larval project to mongodb but when I run php **php artisan migrate** I get this error.

   

> MongoDB\Driver\Exception\ConnectionTimeoutException  : No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on '127.0.0.1:27017']

at App/vendor/mongodb/mongodb/src/functions.php:431
    427|         // TODO: PHPLIB-476: Read transaction read preference once PHPC-1439 is implemented
    428|         $readPreference = new ReadPreference(ReadPreference::RP_PRIMARY);
    429|     }
    430| 
  > 431|     return $manager->selectServer($readPreference);
    432| }
    433| 

  Exception trace:

  1   MongoDB\Driver\Manager::selectServer(Object(MongoDB\Driver\ReadPreference))
   App/vendor/mongodb/mongodb/src/functions.php:431

  2   MongoDB\select_server(Object(MongoDB\Driver\Manager), [])
   App/vendor/mongodb/mongodb/src/Database.php:423

  Please use the argument -v to see more details.

**Comment by alcaeus** [comment]
From the error message that you posted, we can see that the driver is trying to connect to the default MongoDB URI (127.0.0.1:27017), but can't reach it. The first step would be to ensure that your MongoDB server is up and running where you expect it to be, and to double-check the configuration that you are actually trying to reach the server that you want to reach.

Depending on whether you use a special Laravel library to use MongoDB or straight up use `mongodb/mongodb`, the process described above may vary. Using `mongodb/mongodb` directly, you pass the connection string when constructing your `MongoDB\Client` instance, along with any connection options you want to apply.

**Comment by laingmedia** [comment]
Hi Alcaeus,

Thanks for your response, I will implement suggestions and get back to you.

**Comment by laingmedia** [comment]
HI @alcaeus 

Mongodb was where I expected it to be, I just had to change my connection config to dsn connection with url. I hop this helps someone in the future.

**Comment by zezont4** [comment]
> HI @alcaeus
> 
> Mongodb was where I expected it to be, I just had to change my connection config to dsn connection with url. I hop this helps someone in the future.

Could you please clarify more ?
Thank you.

**Comment by marcnewton** [comment]
I am having same issue using Jensegers MongoDB for Laravel but my migrations work just fine, database creates and collections are created even `db:seed` works perfectly but when I try to login... I get the "No suitable servers found" error!...
