### ISSUE TITLE
 mongodb change stream example for php ?

### ISSUE THREAD

**Issue by gfanini** [mongodb/mongo-php-driver#1050]
where can I find any mongo change stream example for php ?
not tailable cursor on a "capped" collection, I'd need to "watch" a modifiable collection from php

the environment is WAMP php 7.2 windows

**Comment by jmikola** [comment]
Dupe of https://github.com/mongodb/mongo-php-library/issues/693 and [mongodb-user thread](https://groups.google.com/d/msg/mongodb-user/_saU8uO8voU/eVt5MPtEDgAJ).
