### ISSUE TITLE
pecl install fails

### ISSUE THREAD

**Issue by jfederer** [mongodb/mongo-php-driver#1056]
Following your instructions...

```
$ sudo pecl install mongodb
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /usr/share/pear/PEAR/Frontend.php on line 91
```

My php version from php -v is 
```
$ php -v
PHP 7.0.33 (cli) (built: Dec  6 2018 22:30:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

my php version from phpinfo() is 7.0.27

My OS is centos 7

I'm inexperienced with linus, so I have no idea why phpinfo and php -v return different values... that's why I gave both.

**Comment by alcaeus** [comment]
From what I could find after a quick search, this seems to be a problem of running an older version of PEAR on PHP 7. You can check the version by running `pear version` and checking the output. This will print the current PEAR version, as well as the PHP and Zend Engine versions currently in use:
```
PEAR Version: 1.10.9
PHP Version: 7.4.0RC4
Zend Engine Version: 3.4.0-dev
Running on: Darwin vulcan.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

You need PEAR version 1.10 or newer when running PHP 7. You can upgrade PEAR by running:
```
wget http://pear.php.net/go-pear.phar
php go-pear.phar
```

Once that is done, you should be able to install the extension as expected. Please let me know if this works for you or if the problem persists.

**Comment by jfederer** [comment]
running php go-pear.phar claims it's no webserver is installed and ends up asking a bunch of additional questions about where the www directory is, and other things. It feels like it's not picking up on my apache installation.   (to be clear, I don't know what pear is)

**Comment by alcaeus** [comment]
Since this isn't an issue with the installation of the driver, but rather with your installation of pecl itself, I'd ask you to post this question to one of the PHP support channels on Stackoverflow or the php-general mailing list: https://news-web.php.net/php.general. Thanks!
