### ISSUE TITLE
mongo 1.7.1 - pecl install error on php:7.4-fpm-alpine3.10

### ISSUE THREAD

**Issue by litan1106** [mongodb/mongo-php-driver#1097]
### Bug Report

Error on docker-ext-install with mongo 1.7.1

### Environment

docker [php:7.4-fpm-alpine3.10](https://github.com/docker-library/php/blob/703a3d0a4e4c149bfd62fc3e7b71645f9496b178/7.4/alpine3.10/fpm/Dockerfile)

pecl install  mongo

### Debug Log

 mongodb was configured with the following options:
 
 Build configuration:
   CFLAGS                                           : -g -O2
   Extra CFLAGS                                     :
   Developers flags (slow)                          :
   Code Coverage flags (extra slow)                 :
   System libmongoc                                 : no
   System libbson                                   : no
   System libmongocrypt                             : no
   LDFLAGS                                          :
   EXTRA_LDFLAGS                                    :
   MONGODB_SHARED_LIBADD                            : -lresolv -Wl,-rpath,/lib -L/lib  -lz -lssl -lcrypto
 
 Please submit bugreports at:
   https://jira.mongodb.org/browse/PHPC
 
 
 config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/libbson/src/bson/bson-config.h
 config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/libbson/src/bson/bson-version.h
 config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-config.h
 config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-version.h
 config.status: creating /tmp/pear/temp/mongodb/src/libmongocrypt/src/mongocrypt-config.h
 config.status: creating /tmp/pear/temp/mongodb/src/libmongocrypt/src/mongocrypt.h
 config.status: creating config.h
 running: make

...

-I/tmp/pear/temp/mongodb/src/MongoDB/Exception/ -I/tmp/pear/temp/mongodb/src/MongoDB/Monitoring/ -I/tmp/pear/temp/mongodb/src/contrib/ -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_kv_list.c  -fPIC -DPIC -o src/libmongocrypt/kms-message/src/.libs/kms_kv_list.o
 In file included from /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_kv_list.h:21,
                  from /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_kv_list.c:18:
 /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_request_str.h:42:52: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  kms_request_str_new_from_chars (const char *chars, ssize_t len);
                                                     ^~~~~~~
                                                     size_t
 /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_request_str.h:44:36: error: unknown type name 'ssize_t'; did you mean 'size_t'?
  kms_request_str_wrap (char *chars, ssize_t len);
                                     ^~~~~~~
                                     size_t
 /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_request_str.h:56:28: error: unknown type name 'ssize_t'; did you mean 'size_t'?
                             ssize_t len);
                             ^~~~~~~
                             size_t
 /tmp/pear/temp/mongodb/src/libmongocrypt/kms-message/src/kms_request_str.h:66:31: error: unknown type name 'ssize_t'; did you mean 'size_t'?
                                ssize_t len);
                                ^~~~~~~
                                size_t
 make: *** [Makefile:603: src/libmongocrypt/kms-message/src/kms_kv_list.lo] Error 1

**Comment by jrgilman** [comment]
+1 this broke all our pipelines today.

**Comment by jmikola** [comment]
This appears to be an issue in one of of upstream libraries, [libmongocrypt](https://github.com/mongodb/libmongocrypt). I've reported the issue in JIRA and created a tracking ticket ([PHPC-1553](https://jira.mongodb.org/browse/PHPC-1553)) since the libmongocrypt project is private.

Until this is fixed upstream and the fix is incorporated into a PHP driver release, I think the best course of action is to work around the issue by compiling the extension without libmongocrypt. Following the [manual install process](https://www.php.net/manual/en/mongodb.installation.manual.php), you can specify the `--with-mongodb-client-side-encryption=no` option to `configure` to avoid building libmongocrypt with the driver.

**Comment by litan1106** [comment]
thanks. I will stick to mongo-1.6.1 for now.

**Comment by jrgilman** [comment]
Same, we'll stick to 1.6.1. Something about disabling encryption rubs me the wrong way @jmikola. I'll be watching that JIRA ticket though so we'll update to the next 1.7 point release that works.

**Comment by alcaeus** [comment]
> Something about disabling encryption rubs me the wrong way

The feature being controlled with the `--with-mongodb-client-side-encryption` is called [Client-Side Field Level Encryption](https://docs.mongodb.com/manual/core/security-client-side-encryption/). It is a feature that you have to opt-in by either adding an `autoEncrypt` configuration to your client, or by explicitly encrypting values using a ClientEncryption object. Simply compiling in support for that feature does not make anything more or less secure, so please rest assured that you're not opening yourself up to vulnerabilities if you install 1.7 without libmongocrypt support.

**Comment by jrgilman** [comment]
Ah, appreciate the clarification there @alcaeus!

**Comment by alireza1371** [comment]
> +1 this broke all our pipelines today.
> 
> EDIT: on php:7.2-fpm-alpine

it's brook all of out piplines too, what they are doing?!!!

**Comment by sudarshantech9** [comment]
Any update on this one? I am stuck with docker setup due to this one. Cant proceed unless it make "pecl install mongodb" command works.

**Comment by alcaeus** [comment]
We are currently testing a fix upstream in libmongocrypt and will release 1.7.2 as soon as the fix is available.

**Comment by Jean85** [comment]
> Any update on this one? I am stuck with docker setup due to this one. Cant proceed unless it make "pecl install mongodb" command works.

You just need to force the version to 1.6.1 with `pecl install mongodb-1.6.1`

**Comment by alcaeus** [comment]
1.7.2 has just been released. Apologies for the delay, but libmongocrypt 1.0.2 (which fixed your issue) introduced an issue with `ssize_t` on Windows which we needed to fix first. Sorry for the disruption this has caused, and please let me know if you encounter any other issues.
