### ISSUE TITLE
error with pecl install mongodb (xampp and default pecl)

### ISSUE THREAD

**Issue by AliHashemzadeh** [mongodb/mongo-php-driver#1109]
Hello 
I have mac os mojave and xampp with php version 7.2.27.
When I run sudo pecl install mongodb or sudo /Applications/XAMPP/xamppfiles/bin/pecl install mongodb it returns :
make: *** [src/libmongoc/src/libmongoc/src/mongoc/mongoc-scram.lo] Error 1
ERROR: `make' failed
Here is my configs:

php -v:
`PHP 7.2.27 (cli) (built: Jan 30 2020 02:16:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies`

php --ini:
`Configuration File (php.ini) Path: /Applications/XAMPP/xamppfiles/etc
Loaded Configuration File:         /Applications/XAMPP/xamppfiles/etc/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)`

**Comment by alcaeus** [comment]
Can you please post the `configure` output that is printed at the beginning of the install process, as well as the entire error message that you're seeing? Thanks!

**Comment by AliHashemzadeh** [comment]
Here is configure :
`WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading mongodb-1.7.3.tgz ...
Starting to download mongodb-1.7.3.tgz (1,223,414 bytes)
.................................................................................................................................................................................................................................................done: 1,223,414 bytes
533 source files, building
running: phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
building in /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pear/temp/pear-build-rootLx5FEW/mongodb-1.7.3
running: /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pear/temp/mongodb/configure --with-php-config=/Applications/XAMPP/xamppfiles/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking target system type... x86_64-apple-darwin18.7.0
checking for PHP prefix... /Applications/XAMPP/xamppfiles
checking for PHP includes... -I/Applications/XAMPP/xamppfiles/include/php -I/Applications/XAMPP/xamppfiles/include/php/main -I/Applications/XAMPP/xamppfiles/include/php/TSRM -I/Applications/XAMPP/xamppfiles/include/php/Zend -I/Applications/XAMPP/xamppfiles/include/php/ext -I/Applications/XAMPP/xamppfiles/include/php/ext/date/lib
checking for PHP extension directory... /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20170718
checking for PHP installed headers prefix... /Applications/XAMPP/xamppfiles/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable MongoDB support... yes, shared
checking PHP version... 7.2.27
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking whether to compile against system libraries instead of bundled... no
checking whether to use system libbson... no
checking whether to use system libmongoc... no
checking whether to enable client-side encryption... auto
checking for gcc... (cached) cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking accept ARG2 => struct sockaddr ARG3 => socklen_t ... ok
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for typeof syntax and keyword spelling... typeof
checking for __sync_add_and_fetch_4... yes
checking for __sync_add_and_fetch_8... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for strings.h... (cached) yes
checking whether byte ordering is bigendian... no
checking for strnlen... yes
checking for reallocf... yes
checking for syscall... yes
checking for snprintf... yes
checking for strlcpy... yes
checking for struct timespec... yes
checking for library containing clock_gettime... none required
checking for library containing floor... none required
checking for gmtime_r... yes
checking for rand_r... yes
checking if compiler needs -Werror to reject unknown flags... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... yes
checking whether PTHREAD_ONCE_INIT needs braces... no
checking for pkg-config... /Applications/XAMPP/xamppfiles/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PHP_MONGODB_SNAPPY... no
checking for snappy_uncompress in -lsnappy... no
checking snappy-c.h usability... no
checking snappy-c.h presence... no
checking for snappy-c.h... no
checking for PHP_MONGODB_ZLIB... yes
/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pear/temp/mongodb/configure: line 10920: cd: @@BITROCK_COMMON_ROOTDIR@@: No such file or directory
checking for res_nsearch... yes
checking for res_ndestroy... yes
checking whether to enable SASL for Kerberos authentication... auto
checking for PHP_MONGODB_SASL... no
checking for sasl_client_init in -lsasl2... yes
checking sasl/sasl.h usability... yes
checking sasl/sasl.h presence... yes
checking for sasl/sasl.h... yes
checking for sasl_client_done in -lsasl2... yes
checking which SASL library to use... cyrus
checking whether to enable crypto and TLS... auto
checking deprecated option for OpenSSL library path... auto
configure: checking whether Darwin SSL is available
checking which TLS library to use... darwin
checking whether to use system crypto profile... no
checking deprecated option for whether to use system crypto profile... no
checking whether to enable ICU for SASLPrep with SCRAM-SHA-256 authentication... auto
checking for PHP_MONGODB_ICU... yes
/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/pear/temp/mongodb/configure: line 14850: cd: @@BITROCK_COMMON_ROOTDIR@@: No such file or directory
checking for shm_open... yes
checking for sched_getcpu... no
checking for socklen_t... yes
checking for struct sockaddr_storage.ss_family... yes
checking for pthread_join in LIBS= with CFLAGS=-D_THREAD_SAFE ... yes
checking if compiler needs -Werror to reject unknown flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... (cached) yes
checking whether C compiler accepts -Wno-deprecated-declarations... yes
checking whether C compiler accepts -Wno-cast-align... yes
checking whether C compiler accepts -Wno-unneeded-internal-declaration... yes
checking whether C compiler accepts -Wno-error=unused-command-line-argument... yes
checking if weak symbols are supported... yes
checking which crypto library to use for libmongocrypt... darwin
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common
checking if g++ PIC flag -fno-common works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status`

**Comment by AliHashemzadeh** [comment]
also fix my problem with 
[883#](https://github.com/mongodb/mongo-php-driver/issues/883#issuecomment-406707863)
