### ISSUE TITLE
Can't install on amazon linux ec2

### ISSUE THREAD

**Issue by pesseyjulien** [mongodb/mongo-php-driver#1113]
HI,

Trying to upgrade from version 1.5 to 1.7 but I'm getting the following :

```
checking whether the C compiler works... no
configure: error: in `/var/tmp/pear-build-root8IlpZo/mongodb-1.7.3':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: `/var/tmp/mongodb/configure --with-php-config=/usr/bin/php-config' failed
```

Any idea why ?

**Comment by alcaeus** [comment]
> See `config.log' for more details

Can you check the log to see what the error is? Without more details we won't be able to figure out what's wrong. Please also include the full command that you used to install this (I'd assume it was `pecl install mongodb`, but please confirm).

**Comment by pesseyjulien** [comment]
```
cc: error: unrecognized command line option '-qversion'; did you mean '--version'?
cc: fatal error: no input files
compilation terminated.
configure:3000: $? = 1
configure:3020: checking whether the C compiler works
configure:3042: cc    conftest.c  >&5
configure:3046: $? = 0
configure:3084: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3089: error: in `/home/ec2-user/mongo-php-driver':
configure:3091: error: C compiler cannot create executables
See `config.log' for more details
```

And tried with pecl and manual installation also.

Thanks,
Julien

**Comment by pesseyjulien** [comment]
gcc version 7.3.1 20180712 (Red Hat 7.3.1-6) (GCC)

**Comment by alcaeus** [comment]
I don't have an Amazon box to try and reproduce this, so I could only look for the problem online. There are various problems that could cause this, but I won't know without taking a closer look at the log. Can you please update the full log to a gist? Thanks!

**Comment by pesseyjulien** [comment]
Working with version MongoDB extension version => 1.7.4 !

**Comment by alcaeus** [comment]
That's odd, but I'm glad this was resolved for you!

**Comment by pesseyjulien** [comment]
Even weirder, works on some servers but all of them..

Attached the config.log

Thanks !

[config.log](https://github.com/mongodb/mongo-php-driver/files/4416012/config.log)

**Comment by alcaeus** [comment]
The compilation failed because we couldn't locate `ld`:
> configure:3000: $? = 1
> configure:3020: checking whether the C compiler works
> configure:3042: cc    conftest.c  >&5
> collect2: fatal error: cannot find 'ld'
> compilation terminated.

A quick google search shows that on some machines the location where `ld` is stored was missing from the PATH. Since you have some machines where compilation works and others where it doesn't, it may be worth checking for differences between the systems (e.g. running `which ld` on both systems, checking if the files are found in both places, etc.

**Comment by pesseyjulien** [comment]
Yep you are right, missing ld 

`/usr/bin/which: no ld in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin)`

Trying to install it but no success so far..

**Comment by pesseyjulien** [comment]
No idea why installing the binutils won't install the 'ld' extension by any chance ?

**Comment by alcaeus** [comment]
> No idea why installing the binutils won't install the 'ld' extension by any chance ?

No idea, at all. Is the file actually missing from the system or is the PATH missing the folder where it's located?

**Comment by pesseyjulien** [comment]
the file is actually missing

**Comment by alcaeus** [comment]
> the file is actually missing

That's odd, but I have no idea what the issue could be. I would suggest you ask AWS support about this.

**Comment by pesseyjulien** [comment]
all good, I have to remove an old 'ld' file in '/var/lib/alternatives/' and then reinstall binutils. Thanks for the help !

**Comment by alcaeus** [comment]
Glad to see you were able to solve it. Thanks for updating!
