### ISSUE TITLE
Is it difficult adding a close() method?

### ISSUE THREAD

**Issue by ar414-com** [mongodb/mongo-php-driver#1115]
I think the library should be open
let's the end user to choose the behavior what they want
I think users should be free

**Comment by alcaeus** [comment]
As per previous comments in https://github.com/mongodb/mongo-php-driver/issues/393#issuecomment-245638805, this functionality is not available in the driver. If you want to close all connections from a process, terminating this process will close any open connections. Note that when using FPM, this means restarting FPM workers.
