### ISSUE TITLE
Why changed Legacy/Old fashion Coding format?

### ISSUE THREAD

**Issue by AbdulJabbarDumrai** [mongodb/mongo-php-driver#1116]
It will be really appreciating if someone could tell why this new release of **Mongo PHP Driver** has Changed Legacy/Old implementation of functions like db.products.find() & db.getCollection().insertOne() etc? That was really easy to code because it matched the Mongo Docs as well.

It also removed the functionality to perform single CRUD operations like InsertOne,  Update or Delete? Now we have to use BulkWrite for even one single write operation. Why?

If there are 3 different collections to write data, we have to call the whole BulkWrite for every new Collection

$connection->executeBulkWrite($database'.'.**$col1**, $bulk);
$connection->executeBulkWrite($database'.'.**$col2**, $bulk);
$connection->executeBulkWrite($database'.'.**$col3**, $bulk);

Also when we have to write something on database with Transactions, We have to use BulkWrite for all different Collections. This is a very high resource intensive task to combine BulkWrite with Transactions.

I forgot to mention that I am using Windows. 

Or am I missing anything?

**Comment by alcaeus** [comment]
It sounds like you are using the extension without the library. The PHP extension only provides a low-level API (the ability to run bulk writes, queries, and commands on a server), while the library provides the high-level API that is also provided by the other drivers. To get started with the library, run `composer require mongodb/mongodb` and have a look at the [tutorials](https://docs.mongodb.com/php-library/current/tutorial/), which cover CRUD operations, GridFS, and other topics.

**Comment by AbdulJabbarDumrai** [comment]
> It sounds like you are using the extension without the library. The PHP extension only provides a low-level API (the ability to run bulk writes, queries, and commands on a server), while the library provides the high-level API that is also provided by the other drivers. To get started with the library, run `composer require mongodb/mongodb` and have a look at the [tutorials](https://docs.mongodb.com/php-library/current/tutorial/), which cover CRUD operations, GridFS, and other topics.

\

**Comment by AbdulJabbarDumrai** [comment]
> It sounds like you are using the extension without the library. The PHP extension only provides a low-level API (the ability to run bulk writes, queries, and commands on a server), while the library provides the high-level API that is also provided by the other drivers. To get started with the library, run `composer require mongodb/mongodb` and have a look at the [tutorials](https://docs.mongodb.com/php-library/current/tutorial/), which cover CRUD operations, GridFS, and other topics.

Thanks @alcaeus for such prompt response. Actually you are right I just missed this Library and wasted the whole day creating one of my own. 

Please can you tell me if this Library uses the BulkWrite to provide functionality of insertOne()? Or it uses some core functions of driver? I mean what's happening on the background when I call InsertOne()? Is this Library using BulkWrite() to create functions like insertOne, Update or Delete etc?

**Comment by alcaeus** [comment]
`InsertOne` for example uses a BulkWrite to do its insert. The `Update` operation uses the `update` command, while the `Delete` operation uses a `delete` command. For more, I'll refer you to the various [operations in the library](https://github.com/mongodb/mongo-php-library/tree/master/src/Operation).
