### ISSUE TITLE
Load extension error

### ISSUE THREAD

**Issue by a07061625** [mongodb/mongo-php-driver#1122]
openssl
![image](https://user-images.githubusercontent.com/12109534/79191141-8281fc00-7e58-11ea-8400-9b251298ab4d.png)

php
![image](https://user-images.githubusercontent.com/12109534/79191174-93cb0880-7e58-11ea-9bd7-164e0abc3b69.png)

when I add php.ini for extension=mongodb.so，then
![image](https://user-images.githubusercontent.com/12109534/79191288-caa11e80-7e58-11ea-90b4-3b602ef0465f.png)

gdb about the core file
![image](https://user-images.githubusercontent.com/12109534/79191373-fde3ad80-7e58-11ea-80d9-f105a78565c9.png)

**Comment by alcaeus** [comment]
Thanks for providing a trace for the segmentation fault! To properly investigate this, could you please provide the following information:
* How did you install the extension? Did you compile it manually or install it via pecl?
* Can you please post the **complete** output from the `configure` call, including the call itself it you compiled the extension yourself?

**Comment by a07061625** [comment]
1. install extension with pecl
2. cd mongodb-1.7.4/ && /usr/local/php7/bin/phpize && ./configure --with-php-config=/usr/local/php7/bin/php-config && make && make install

**Comment by a07061625** [comment]
@alcaeus

**Comment by alcaeus** [comment]
@a07061625 can you please post the full output of that `configure` call in a gist at https://gist.github.com? Thanks!

**Comment by a07061625** [comment]
@alcaeus sorry,I can not open the gist website, but it return no error info when I install extension

**Comment by a07061625** [comment]
the reason is install two version of openssl ，now it is fixed
