### ISSUE TITLE
Build with phpize

### ISSUE THREAD

**Issue by flip111** [mongodb/mongo-php-driver#1123]
I compiled PHP from source to have a debug build (because i was getting segfaults). I would like to use this extension but i don't have `pecl`. Is it possible to install this extension with phpize, configure and make ?

**Comment by alcaeus** [comment]
Yes, the documentation contains a dedicated chapter that explains the necessary steps: https://www.php.net/manual/en/mongodb.installation.manual.php.

**Comment by flip111** [comment]
Could `Manually Installing the MongoDB PHP Driver` be renamed to `Building MongoDB PHP Driver from source` ?

**Comment by alcaeus** [comment]
Good idea, and done: http://svn.php.net/viewvc/phpdoc/en/trunk/reference/mongodb/configure.xml?r1=348993&r2=349668.

**Comment by flip111** [comment]
Thank you @alcaeus
