### ISSUE TITLE
Turn off automatic serialization

### ISSUE THREAD

**Issue by thawkins** [mongodb/mongo-php-driver#114]
Is there any way to turn off the automatic serialization and have the driver behave like the older legacy driver as far as read and writing documents is concerned, IE just provide a serialization to and from array objects. 

this is to avoid

1. The insertion of type annotations into the on disk format
2. The need to inherit data classes from the driver type hierarchy. (makes building storage adapters that target multiple storage systems near impossible). 

I get that there is a need to be able provide support for extending functionality of the driver. But this attempt to convert the driver into an ORM is a step too far.  I dont  want class factories in my database driver, if i want them I will provide my own. Or I will use an ORM layer that suits my needs.

**Comment by bjori** [comment]
We don't store the class reference by default. You must explicitly implement the `MongoDB\BSON\Persistable` interface.

It was decided that the Driver should be consistent with the wire protocol format (e.g. BSON) when it came to serialization of containers -- mean the "root document" should be considered as stdClass, not array. See: https://jira.mongodb.org/browse/PHPC-319

You can configure this behavior by setting the typemap yourself:
```
$result = $manager->executeQuery(NS, $query);
$result->setTypeMap(array("document"=> "array", "root" => "array"));
foreach($result as $document) {
    var_dump($document);
}
```

**Comment by derickr** [comment]
@thawkins Does @bjori's comment address your concern?

**Comment by thawkins** [comment]
Not 100%,  i still think there is a need where we can set 

$result->setTypeMap(array("document"=> "array", "root" => "array"));

As the default behaviour, otherwise it just adds a load of noise to the interface if people are forced to do this on every query for compatability reasons. 

Something like 

$manager->setDefaultTypeMap(array("document"=> "array", "root" => "array"));

Im going to have to try converting our ORM to work with the new driver so i have to hide all this in our MongoCollection analog class. Our ORM is very like doctrine, but has a bunch of support for automatic DublinCore Metadata in each object. 

It already does its own class factory, so the one in tbe driver just gets in the way.

**Comment by derickr** [comment]
Hi @thawkins,

The driver itself is meant to be as bare bones as possible, and hence setting a default type map is not in the scope of the driver. 

However, we are going to address this in the accompanying library. There is an issue at https://github.com/mongodb/mongo-php-library/issues/39, and a ticket too: https://jira.mongodb.org/browse/PHPLIB-74

cheers,
Derick

**Comment by jmikola** [comment]
@thawkins: Would you mind taking a look at https://github.com/mongodb/mongo-php-library/pull/73? I believe this implements what you were requesting.

**Comment by thawkins** [comment]
We are starting to look at the migration in mid jan, at the moment we are stabilising a large deployment on php5.6/3.0.8/legacy driver. Once that is complete and deployed, i can free up some of my developers to start working through the migration issues. We will be targeting  php7/3.2.1/new driver/phplib.

**Comment by jmikola** [comment]
@thawkins: Thanks for following up. I'm going to close this out, as the corresponding PHPLIB ticket should address your needs. Feel free to ping us later on if you have additional concerns/feedback, though.
