### ISSUE TITLE
PHP startup warning: Unable to load dynamic library 'mongodb'

### ISSUE THREAD

**Issue by nspeedzy** [mongodb/mongo-php-driver#1155]
## Bug Report

I am trying to create a project using php and mongodb's php driver. When I try to install the library with composer, composer gives me an error saying that I need to install the mongodb extension for php. So I go to [pecl.php.net](https://pecl.php.net/package/mongodb) to install the php extension. But php gives me an error saying that the extension was not found (Debug output mentioned under debug log). I have even tried following the steps in #677, but it doesn't work. I haven't experienced this issue before with older versions of the extension 

## Environment
**Environment Info:**
<details>
    <summary>Click to expand</summary>
     <table>
         <tr>
             <th>Operating System:</th>
             <td><code>Windows 10 x64</code></td>
         </tr>
         <tr>
             <th>PHP Version:</th>
             <td><code>7.4.8</code></td>
         </tr>
         <tr>
             <th>PHP mongodb ext version:</th>
             <td><code>1.7.5</code></td>
         </tr>
         <tr>
             <th>MongoDB version:</th>
             <td><code>4.2.6</code></td>
         </tr>
    </table>
</details>

**Have you installed php using a third-party service like MAMP or XAMPP?**

No

## Test Script
The problem was not caused by any php scripts

## Expected and Actual Behavior
**Expected behaviour:**

PHP should have loaded the extension without any 404 warnings outputted

**Actual behaviour**

PHP says that the extension was not found according to the debug output mentioned under the debug log category

## Debug Log
Here is the debug log outputted by php when the problem occured:
```ps1
PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb' (tried: ext\mongodb (The specified module could not be found.), ext\php_mongodb.dll (The specified module could not be found.)) in Unknown on line 0
```

**Comment by jmikola** [comment]
> But php gives me an error saying that the extension was not found (Debug output mentioned under debug log).

Is this error from the web environment, CLI environment (i.e. `php.exe`), or both?

For each environment where this error occurred, can you share your `phpinfo()` output? Feel free to only include `INFO_GENERAL` and `INFO_CONFIGURATION` (i.e. `phpinfo(INFO_GENERAL|INFO_CONFIGURATION)`) as the PHP platform details and INI configuration are most relevant here.

Additionally, can you link to the exact archive of the extension that you've downloaded (from PECL) and indicate the full path where you've extracted the DLL?

**Comment by nspeedzy** [comment]
> Is this error from the web environment, CLI environment (i.e. php.exe), or both?

@jmikola It from both `php.exe`, the web environment and wherever I use php like in debugging, installing packages using composer, etc

Just gimme a few minutes and I'll share the info right away

**Comment by nspeedzy** [comment]
Here is a screenshot of `INFO_GENERAL` (general info):

![php_general](https://user-images.githubusercontent.com/60068454/88759888-5ed58e00-d189-11ea-9c98-33653f08649f.png)

**Comment by nspeedzy** [comment]
Ok here is the config info (`INFO_CONFIGURATION`):

<table>

<tbody>

<tr class="h">

<th>Directive</th>

<th>Local Value</th>

<th>Master Value</th>

</tr>

<tr>

<td class="e">allow_url_fopen</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">allow_url_include</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">arg_separator.input</td>

<td class="v">&</td>

<td class="v">&</td>

</tr>

<tr>

<td class="e">arg_separator.output</td>

<td class="v">&</td>

<td class="v">&</td>

</tr>

<tr>

<td class="e">auto_append_file</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">auto_globals_jit</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">auto_prepend_file</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">browscap</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">default_charset</td>

<td class="v">UTF-8</td>

<td class="v">UTF-8</td>

</tr>

<tr>

<td class="e">default_mimetype</td>

<td class="v">text/html</td>

<td class="v">text/html</td>

</tr>

<tr>

<td class="e">disable_classes</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">disable_functions</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">display_errors</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">display_startup_errors</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">doc_root</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">docref_ext</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">docref_root</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">enable_dl</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">enable_post_data_reading</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">error_append_string</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">error_log</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">error_prepend_string</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">error_reporting</td>

<td class="v">32767</td>

<td class="v">32767</td>

</tr>

<tr>

<td class="e">expose_php</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">extension_dir</td>

<td class="v">ext</td>

<td class="v">ext</td>

</tr>

<tr>

<td class="e">file_uploads</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">hard_timeout</td>

<td class="v">2</td>

<td class="v">2</td>

</tr>

<tr>

<td class="e">highlight.comment</td>

<td class="v"><font style="color: #FF8000">#FF8000</font></td>

<td class="v"><font style="color: #FF8000">#FF8000</font></td>

</tr>

<tr>

<td class="e">highlight.default</td>

<td class="v"><font style="color: #0000BB">#0000BB</font></td>

<td class="v"><font style="color: #0000BB">#0000BB</font></td>

</tr>

<tr>

<td class="e">highlight.html</td>

<td class="v"><font style="color: #000000">#000000</font></td>

<td class="v"><font style="color: #000000">#000000</font></td>

</tr>

<tr>

<td class="e">highlight.keyword</td>

<td class="v"><font style="color: #007700">#007700</font></td>

<td class="v"><font style="color: #007700">#007700</font></td>

</tr>

<tr>

<td class="e">highlight.string</td>

<td class="v"><font style="color: #DD0000">#DD0000</font></td>

<td class="v"><font style="color: #DD0000">#DD0000</font></td>

</tr>

<tr>

<td class="e">html_errors</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">ignore_repeated_errors</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">ignore_repeated_source</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">ignore_user_abort</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">implicit_flush</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">include_path</td>

<td class="v">.;C:\php\pear</td>

<td class="v">.;C:\php\pear</td>

</tr>

<tr>

<td class="e">input_encoding</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">internal_encoding</td>

<td class="v">_no value_</td>

<td class="v">_no value_</td>

</tr>

<tr>

<td class="e">log_errors</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">log_errors_max_len</td>

<td class="v">1024</td>

<td class="v">1024</td>

</tr>

<tr>

<td class="e">mail.add_x_header</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">mail.force_extra_parameters</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">mail.log</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">max_execution_time</td>

<td class="v">30</td>

<td class="v">30</td>

</tr>

<tr>

<td class="e">max_file_uploads</td>

<td class="v">20</td>

<td class="v">20</td>

</tr>

<tr>

<td class="e">max_input_nesting_level</td>

<td class="v">64</td>

<td class="v">64</td>

</tr>

<tr>

<td class="e">max_input_time</td>

<td class="v">60</td>

<td class="v">60</td>

</tr>

<tr>

<td class="e">max_input_vars</td>

<td class="v">1000</td>

<td class="v">1000</td>

</tr>

<tr>

<td class="e">memory_limit</td>

<td class="v">128M</td>

<td class="v">128M</td>

</tr>

<tr>

<td class="e">open_basedir</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">output_buffering</td>

<td class="v">4096</td>

<td class="v">4096</td>

</tr>

<tr>

<td class="e">output_encoding</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">output_handler</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">post_max_size</td>

<td class="v">8M</td>

<td class="v">8M</td>

</tr>

<tr>

<td class="e">precision</td>

<td class="v">14</td>

<td class="v">14</td>

</tr>

<tr>

<td class="e">realpath_cache_size</td>

<td class="v">4096K</td>

<td class="v">4096K</td>

</tr>

<tr>

<td class="e">realpath_cache_ttl</td>

<td class="v">120</td>

<td class="v">120</td>

</tr>

<tr>

<td class="e">register_argc_argv</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">report_memleaks</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">report_zend_debug</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">request_order</td>

<td class="v">GP</td>

<td class="v">GP</td>

</tr>

<tr>

<td class="e">sendmail_from</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">sendmail_path</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">serialize_precision</td>

<td class="v">-1</td>

<td class="v">-1</td>

</tr>

<tr>

<td class="e">short_open_tag</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">SMTP</td>

<td class="v">localhost</td>

<td class="v">localhost</td>

</tr>

<tr>

<td class="e">smtp_port</td>

<td class="v">25</td>

<td class="v">25</td>

</tr>

<tr>

<td class="e">sys_temp_dir</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">syslog.facility</td>

<td class="v">LOG_USER</td>

<td class="v">LOG_USER</td>

</tr>

<tr>

<td class="e">syslog.filter</td>

<td class="v">no-ctrl</td>

<td class="v">no-ctrl</td>

</tr>

<tr>

<td class="e">syslog.ident</td>

<td class="v">php</td>

<td class="v">php</td>

</tr>

<tr>

<td class="e">track_errors</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">unserialize_callback_func</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">upload_max_filesize</td>

<td class="v">2M</td>

<td class="v">2M</td>

</tr>

<tr>

<td class="e">upload_tmp_dir</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">user_dir</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

<tr>

<td class="e">user_ini.cache_ttl</td>

<td class="v">300</td>

<td class="v">300</td>

</tr>

<tr>

<td class="e">user_ini.filename</td>

<td class="v">.user.ini</td>

<td class="v">.user.ini</td>

</tr>

<tr>

<td class="e">variables_order</td>

<td class="v">GPCS</td>

<td class="v">GPCS</td>

</tr>

<tr>

<td class="e">windows.show_crt_warning</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">xmlrpc_error_number</td>

<td class="v">0</td>

<td class="v">0</td>

</tr>

<tr>

<td class="e">xmlrpc_errors</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">zend.assertions</td>

<td class="v">1</td>

<td class="v">1</td>

</tr>

<tr>

<td class="e">zend.detect_unicode</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">zend.enable_gc</td>

<td class="v">On</td>

<td class="v">On</td>

</tr>

<tr>

<td class="e">zend.exception_ignore_args</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">zend.multibyte</td>

<td class="v">Off</td>

<td class="v">Off</td>

</tr>

<tr>

<td class="e">zend.script_encoding</td>

<td class="v">no value</td>

<td class="v">no value</td>

</tr>

</tbody>

</table>

**Comment by jmikola** [comment]
> Additionally, can you link to the exact archive of the extension that you've downloaded (from PECL) and indicate the full path where you've extracted the DLL?

I'm referring to the archive you downloaded  https://pecl.php.net/package/mongodb/1.7.5/windows.

Based on your `phpinfo()` output, you're running PHP 7.4 without thread-safety (i.e. NTS) on an x64 architecture. I would expect that you have downloaded [php_mongodb-1.7.5-7.4-nts-vc15-x64.zip](https://windows.php.net/downloads/pecl/releases/mongodb/1.7.5/php_mongodb-1.7.5-7.4-nts-vc15-x64.zip) but I'd like to confirm.

I also see that your `extension_dir` INI setting is set to `ext`. [This comment on PHP.net](https://www.php.net/manual/en/install.pecl.windows.php#122732) suggests changing that to an absolute path as a possible workaround.

**Comment by nspeedzy** [comment]
@jmikola Thank you so much for your help! Tbh I had downloaded the thread-safe version of the `php_mongodb.dll` extension when I actually have a Non thread-safe version of php on my computer Lol!

You can close this issue now. My problem has been solved.
