### ISSUE TITLE
Does not detect SASL function on windows

### ISSUE THREAD

**Issue by chasepeeler** [mongodb/mongo-php-driver#1157]
```
Checking for library libsasl.lib ... ..\deps\lib\libsasl.lib
Checking for sasl/sasl.h ...  D:\php-sdk\phpdev\vc14\x64\deps\include
Checking for sasl_client_done in sasl/sasl.h ... Checking for sasl/sasl.h ...  <not found>
Checking for sasl/sasl.h ...  <not found>
No
```

I'm using the deps provided in https://windows.php.net/downloads/php-sdk/archives/deps-7.0-vc14-x86_2018-12.7z and I verified that the `sasl_client_done` method does exist in `sasl/sasl.h`. 

```
/* dispose of all SASL plugins.  Connection
 * states have to be disposed of before calling this.
 * This function should be called instead of sasl_done(),
   whenever possible.
 */
LIBSASL_API int sasl_client_done(void);
```

I went in and just commented out the if statement in config.w32 that checks for that:
```
//if (CHECK_FUNC_IN_HEADER("sasl/sasl.h", "sasl_client_done")) {
    mongoc_opts.MONGOC_HAVE_SASL_CLIENT_DONE = 1;
//}
```

I then reran config and compiled the extension. phpinfo() shows that libmongoc SASL is enabled (it showed disabled before). 

Additional Info:
- Building on Windows 10 against 7.0.32 source.
- Using 1.7.5 source from pecl.
- `configure --disable-zts --disable-all --enable-cli --enable-mongodb=shared --with-openssl --enable-json --with-mongodb-sasl`

**Comment by jmikola** [comment]
If `config.w32` makes it to the `CHECK_FUNC_IN_HEADER` call that you cited, `MONGOC_ENABLE_SASL` should already have been enabled and `phpinfo()` should report that SASL is enabled (per [this code](https://github.com/mongodb/mongo-php-driver/blob/1.7.5/php_phongo.c#L3896)). Can you double-check that output when building the driver without that modification to `config.w32`?

For context, `MONGOC_HAVE_SASL_CLIENT_DONE` is only relevant for [this code in libmongoc](https://github.com/mongodb/mongo-c-driver/blob/1.16.2/src/libmongoc/src/mongoc/mongoc-init.c#L150). I agree that there's probably an issue with detecting the function here, but I want to confirm that it's not resulting in the driver having no support for SASL at all.

I opened [PHPC-1667](https://jira.mongodb.org/browse/PHPC-1667) to track this.

**Comment by chasepeeler** [comment]
It is enabled even without those modifications. I think I forgot the --with-mongodb-sasl when I originally did it (I keep forgetting that --disable-all includes the default enabled options as well). When I went back and enabled it, I noticed that it wasn't finding that function, so I assumed that was the reason it wasn't enabled the first time, without ever actually building it and confirming.

**Comment by jmikola** [comment]
Good to know. I just wanted to be sure that there's no urgent blocker for using SASL on your end or in the PECL builds.

As for the `--disable-all` issue, we got bit by that as well (see: https://github.com/mongodb/mongo-php-driver/commit/c4d1f7e49a75e3be91a020d5dca50ab97f958d75) :smile:
