### ISSUE TITLE
Unrecognized pipeline stage name: '$convert'

### ISSUE THREAD

**Issue by globules-io** [mongodb/mongo-php-driver#1160]
### Bug Report

Fatal error: Uncaught MongoDB\Driver\Exception\CommandException: Unrecognized pipeline stage name: '$convert' in (...)\vendor\mongodb\mongodb\src\Operation\Aggregate.php:298 Stack trace: #0

### Environment

PHP 7.4.9 x64
MongoDB 4.2.8 x64
mongodb/mongodb 1.7.0

### Question
Has "$convert" been implemented in aggregate ?

**Comment by alcaeus** [comment]
The error message "Unrecognized pipeline stage name" makes it look like you tried to run the following:
```php
$collection->aggregate([
    ['$convert' => [...]],
    ...
]);
```

This is incorrect as `$convert` is not a pipeline stage, but rather a pipeline operator. For anything else, you'll have to provide some sample code that allows us to reproduce the error. Thanks!

**Comment by globules-io** [comment]
Thanks, that's exactly what happened. Closing, will do more research.
