### ISSUE TITLE
Error : Cannot find input file "common-config.h.in"

### ISSUE THREAD

**Issue by rizaldimaulidia** [mongodb/mongo-php-driver#1180]
### Bug Report
I want to install this driver in my computer. But when I try to configure with command :
`sudo ./configure --with-php-config=/opt/lampp/bin/php-config`

and when executed that command, I got an error like this :
`config.status: error: cannot find input file: /home/ubuntu/Downloads/mongo-php-driver-master/src/libmongoc/src/common/common-config.h.in'`

### Environment
OS : Linux Ubuntu 18.04
I used Xampp in my computer.
MongoDB shell version v3.6.3

### Test Script
none

### Expected and Actual Behavior
This is the complete debug that I got :
```
Build configuration:
  CFLAGS                                           : -g -O2
  Extra CFLAGS                                     :  
  Developers flags (slow)                          : 
  Code Coverage flags (extra slow)                 : 
  libmongoc                                        : Bundled (1.18.0-20200727+git60267532b6)
  libbson                                          : Bundled (1.18.0-20200727+git60267532b6)
  libmongocrypt                                    : Bundled (1.0.4)
  LDFLAGS                                          : 
  EXTRA_LDFLAGS                                    : 
  MONGODB_SHARED_LIBADD                            : -lrt -lresolv  -pthread -lssl -lcrypto -pthread

Please submit bugreports at:
  https://jira.mongodb.org/browse/PHPC


config.status: error: cannot find input file: `/home/ubuntu/Downloads/mongo-php-driver-master/src/libmongoc/src/common/common-config.h.in'
```

### Debug Log
none

**Comment by alcaeus** [comment]
From the `configure` output that you posted I can see that you're using the current `master` branch to build the library. Did you install submodules as detailed in the [build instructions](https://www.php.net/manual/en/mongodb.installation.manual.php)? This is one step where the manual installation process differs from most other PHP extensions, as you need to run a `git submodule update --init` before calling `phpize` and `configure`. Please let me know if this fixes your issue.

On a different note, the `master` branch is a development version that includes a non-stable libmongoc dependency. Please be aware that we don't recommend using development versions in production. If you want to use a stable version, please install the library using `pecl` or check out a specific tag before building the extension manually.

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/PHPC-1715

**Comment by agolin95** [comment]
Hi @rizaldimaulidia, we are closing this issue since we have not heard back in several weeks, but please let us know if you'd like to start up the conversation again and we'll be happy to reopen.

**Comment by pawan-saxena** [comment]
Hi @agolin95 .
I am facing this issue :

~~~
Build configuration:
  CFLAGS                                           : -g -O2
  Extra CFLAGS                                     :  -Wno-deprecated-declarations -Wno-cast-align -Wno-unneeded-internal-declaration -Wno-error=unused-command-line-argument 
  Developers flags (slow)                          : 
  Code Coverage flags (extra slow)                 : 
  libmongoc                                        : Bundled (1.18.0-20200727+git60267532b6)
  libbson                                          : Bundled (1.18.0-20200727+git60267532b6)
  libmongocrypt                                    : Bundled (1.0.4)
  LDFLAGS                                          : 
  EXTRA_LDFLAGS                                    : 
  MONGODB_SHARED_LIBADD                            : -Wl,-rpath,/lib -L/lib -framework Security -framework CoreFoundation -lsasl2 -lzstd -Wl,-rpath,/lib -L/lib  -lz -licuuc -licudata
~~~

let me know if you need any further details
thank you in advance

**Comment by jmikola** [comment]
@pawan-saxena: Please read https://github.com/mongodb/mongo-php-driver/issues/1180#issuecomment-732752841. The missing file is likely caused by forgetting to initialize git submodules, as is mentioned in the docs for [Building the MongoDB PHP Driver from source](https://www.php.net/manual/en/mongodb.installation.manual.php).

In the future, please refrain from commenting on a closed issue. If you believe you have found a bug, create a new issue and feel free to reference (i.e. link to) any related closed issues for context. If you are not reporting a bug and instead looking for technical support, you should create a post in the [MongoDB Developer Community Forums](https://developer.mongodb.com/community/forums/) where it will likely receive more attention from our community support team (and other users).
