### ISSUE TITLE
Issue while installing PHP MongoDB Driver on MacOS Catalina over xampp

### ISSUE THREAD

**Issue by ptindia** [mongodb/mongo-php-driver#1182]
Hi there,

I am using MacOS Catalina and installed XAMPP on it. When I am trying to install PHP MongoDB driver using following command, it gives me errors mentioned below.

`sudo pecl install mongodb`

I am getting following error:
**starts with**
`running: phpize
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:
Zend Module Api No:
Zend Extension Api No:
building in /private/tmp/pear/install/pear-build-root6XKiXd/mongodb-1.9.0
running: /private/tmp/pear/install/mongodb/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
`

**ends with**

` cc -I. -I/private/tmp/pear/install/mongodb -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootVeGkZj/mongodb-1.9.0/include -I/private/tmp/pear/install/pear-build-rootVeGkZj/mongodb-1.9.0/main -I/private/tmp/pear/install/mongodb -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/private/tmp/pear/install/mongodb/src/libmongoc/src/common/ -I/private/tmp/pear/install/mongodb/src/libmongoc/src/libbson/src/ -I/private/tmp/pear/install/mongodb/src/libmongoc/src/libbson/src/jsonsl/ -I/private/tmp/pear/install/mongodb/src/libmongoc/src/libmongoc/src/ -I/private/tmp/pear/install/mongodb/src/libmongocrypt/src/ -I/private/tmp/pear/install/mongodb/src/libmongocrypt/kms-message/src/ -I/private/tmp/pear/install/mongodb/src/libmongocrypt-compat/ -I/private/tmp/pear/install/mongodb/src/BSON/ -I/private/tmp/pear/install/mongodb/src/MongoDB/ -I/private/tmp/pear/install/mongodb/src/MongoDB/Exception/ -I/private/tmp/pear/ins
tall/mongodb/src/MongoDB/Monitoring/ -I/private/tmp/pear/install/mongodb/src/contrib/ -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/install/mongodb/php_phongo.c  -fno-common -DPIC -o .libs/php_phongo.o
/private/tmp/pear/install/mongodb/php_phongo.c:22:10: fatal error: 'php.h' file not found
#include <php.h>
         ^~~~~~~
1 error generated.
make: *** [php_phongo.lo] Error 1
ERROR: `make' failed`

Please help me to fix this error.

I am using PHP 7.3.11

Than kyou

**Comment by agolin95** [comment]
Hi there! For now we've added a ticket for this in our Jira system and will report back to you by Friday
https://jira.mongodb.org/browse/PHPC-1714

**Comment by alcaeus** [comment]
Hi,

it looks like the original call to `phpize` is already broken. Please refer to [this comment](https://github.com/mongodb/mongo-php-driver/issues/883#issuecomment-406707863) for more information on installing the extension with xampp (OS version differs but I presume it's the same issue). If you have further problems, I'd refer you to the xampp support channels as the error seems to occur long before the extension is installed.

**Comment by alcaeus** [comment]
We're closing this issue as there has been no feedback in some time and this looks like it's not directly related to the driver itself. Please look at the comment linked above and reach out using the [MongoDB support portal](https://support.mongodb.com/welcome) or the [MongoDB community portal](https://developer.mongodb.com/community/forums/) if the problem persists. Thanks!

**Comment by DanielLDorn** [comment]
I hit this problem and had to [manually compile the code](https://www.php.net/manual/en/mongodb.installation.manual.php), except I had to change the `./configure` command to:

`./configure --with-mongodb-sasl=no --with-php-config=/Applications/XAMPP/xamppfiles/bin/[insert your php config filename here, mine was: php-config-7.4.12]`

If this doesn't work, then you may need to update PCRE.
