### ISSUE TITLE
[Cursor] the current method does not return anything!

### ISSUE THREAD

**Issue by ziaratban** [mongodb/mongo-php-driver#1183]
After the last fetch, the `current` method of `MongoDB\Driver\Cursor` must be return `null` but not returns anything.([according to the doc](https://www.php.net/manual/en/mongodb-driver-cursor.current.php#refsect1-mongodb-driver-cursor.current-returnvalues)).
| Q | A
| ------------- | ---
| OS | CentOS 8
| PHP | 7.4.12
| MongoDB extension version | 1.9.0
| MongoDB server | MongoDB Enterprise 4.4.1
| MongoDB environment | Replica Set

**Test.php**
```php
<?php
$mng = new \MongoDB\Driver\Manager('mongodb://user:pass@127.0.0.1:27017/myDB');
$mng->selectServer($mng->getReadPreference());
$cursor = $mng->executeQuery('myDB.myCollection',new \MongoDB\Driver\Query([],['batchSize' => 100]));
$cursor->SetTypeMap([
    'root' => 'array',
    'document' => 'array'
]);
var_dump($cursor->isDead());
var_dump($cursor->getId());
$cursor->rewind();
while(true){
    $row = $cursor->current();
    var_dump($row);
    $cursor->next();
}
```
```sh
root# php Test.php
```
**output**
```text
bool(false)
object(MongoDB\Driver\CursorId)#4 (1) {
  ["id"]=>
  int(0)
}
array(13) {
...
}
array(13) {
...
}
PHP Notice:  Undefined variable: row in Test.php on line 14
NULL
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\RuntimeException: Cannot advance a completed or failed cursor. in Test.php:15
Stack trace:
#0 Test.php(15): MongoDB\Driver\Cursor->next()
#1 {main}
  thrown in Test.php on line 15
```

**Comment by alcaeus** [comment]
Hi @ziaratban! Thanks for reporting this. Are you running the latest version (1.9.0)? That version introduced changes to cursor iteration by implementing the `Iterator` interface, so that might have something to do with this. I'll investigate this and report back.

**Comment by ziaratban** [comment]
Hi @alcaeus.
thanks for your reply.
yes. i am certain.

![image](https://user-images.githubusercontent.com/6462878/100639561-90827f80-334a-11eb-8ac4-5056e48bc3ad.png)

**Comment by jmikola** [comment]
@alcaeus I believe this behavior may be expected given the implementation of [`Cursor::current()`](https://github.com/mongodb/mongo-php-driver/blob/1.9.0/src/MongoDB/Cursor.c#L299). `return_value` is only set if `data` is non-null, so perhaps an earlier guard statement with `RETURN_NULL()` is needed.

That said, @ziaratban should only call `current()` if `valid()` returns `true`, per PHP's own contract for the Iterator interface.

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/PHPC-1713

**Comment by alcaeus** [comment]
Will be fixed in the upcoming patch release.
