### ISSUE TITLE
Current build log output with PHP 8.0.0 is really chatty

### ISSUE THREAD

**Issue by BanzaiMan** [mongodb/mongo-php-driver#1185]
### Bug Report

We are trying to create a binary archive for PHP 8.0.0 that includes mongo-php-driver.

The process is basically:
1. Compile 8.0.0 from source
1. Run `pecl install mongodb`

https://github.com/travis-ci/php-src-builder/blob/default/bin/compile-extension-mongodb
(`pecl_install` function is defined in https://github.com/travis-ci/php-src-builder/blob/a6c0a1a69c7730c0d0bef697b8c09f87f14b8c6c/bin/compile-extensions-common#L28-L51.)

When the process kicks off, though, there is a big chunk of log messages and the log limit is reached. You can see such an output starting at
https://travis-ci.com/github/travis-ci/php-src-builder/jobs/452193258#L4085

### Environment

The log comes from Ubuntu.

### Test Script

N/A

### Expected and Actual Behavior

Not entirely sure what can be removed from the log (or how), to be honest.

### Debug Log

See https://travis-ci.com/github/travis-ci/php-src-builder/jobs/452193258#L4085

**Comment by alcaeus** [comment]
Looking at the log, I spot two `tail -1` lines (first at https://travis-ci.com/github/travis-ci/php-src-builder/jobs/452193258#L5356, second somewhere around Line 12000). Not sure where that is coming from, but printing the logs three times seems excessive to me 🤔

You can also run `pecl install -q mongodb` to reduce install output from pecl itself.

**Comment by BanzaiMan** [comment]
Thanks for the quick reply! I really appreciate it.

The `tail` comes from
https://github.com/travis-ci/php-src-builder/blob/a6c0a1a69c7730c0d0bef697b8c09f87f14b8c6c/bin/compile-extensions-common#L37
which is supposed to help detect installation failure (because the exit code from `pecl install` is unreliable, IIRC). Hopefully `-q` by itself is sufficient to reduce the noise level.

**Comment by BanzaiMan** [comment]
https://travis-ci.com/github/travis-ci/php-src-builder/jobs/452803109 Voilà!

**Comment by BanzaiMan** [comment]
Well, the `-q` flag doesn't seem to be recognized, actually. ☹️ 

https://travis-ci.com/github/travis-ci/php-src-builder/jobs/452803109#L11009

**Comment by alcaeus** [comment]
Looking at the usage (from `pecl help`), `pecl install -q mongodb` is indeed invalid:
```
Usage: pecl [options] command [command-options] <parameters>
```

`-q` is an option, not a command option to `install` (see `pecl help install` for a list of those). Sorry for giving you the wrong command above - that's what I get for pretending my GitHub comment window is a shell.

The correct command would be `pecl -q install mongodb`, which produces the following output:
```
$ pecl -q install mongodb
Extension mongodb enabled in php.ini
```
