### ISSUE TITLE
Mongodb driver issue

### ISSUE THREAD

**Issue by Niranjanck** [mongodb/mongo-php-driver#1198]
I install mongodb  also done these steps

$ sudo pecl install mongodb

extension=mongodb.so

But mongodb is not in phpinfo
 What can i do?

**Comment by alcaeus** [comment]
Please note that you may have multiple SAPIs (e.g. php-fpm, CLI) that may require enabling the extensions in separate files.

You can check if it was enabled in the CLI by running `php --ri mongodb`. If this produces version output, it means that the extension is enabled and working for CLI, so if it doesn't show up when running `phpinfo()` through your web server you may have to enable it in a separate file depending on the installation you are using (e.g. XAMPP).

For further questions, I'd like to refer you to the [MongoDB Developer Community Forums](https://developer.mongodb.com/community/forums/), as we are trying to keep this space for bug reports.
