### ISSUE TITLE
Serialization of 'MongoDB\Driver\Manager' is not allowed

### ISSUE THREAD

**Issue by Giacomo92** [mongodb/mongo-php-driver#1278]
Hello,
my application is based on Laravel and MongoDB. Serialization is often used  in this framework for session and emit event. When I try to pass a MongoDB model with nested data with more than 2 level the serialization() not working. The only workaround that I have found is to cast data into array of object.
Is there a way to fix this without casting?

Thanks

### Bug Report
I got this exception: Serialization of 'MongoDB\Driver\Manager' is not allowed

### Environment
I am experiencing this issue with MacOS and Ubuntu 

name     : mongodb/mongodb
descrip. : MongoDB driver library
keywords : database, driver, mongodb, persistence
versions : * 1.10.0

### Test Script

`$user = User::all();`
`serialize($user)`

### Expected and Actual Behavior

I expected to serialize the model like a mysql model, instead I got this exception:
Serialization of 'MongoDB\Driver\Manager' is not allowed

**Comment by jmikola** [comment]
Apart from the BSON classes and some value objects (e.g. ReadPreference), most classes in the `mongodb` extension reference an internal structure from ilbmongoc and thus cannot be serialized. The correct approach here would be for the User model to exclude the Manager (or whatever other object contains a reference to the Manager) from its serialization data (e.g. [`__serialize()`](https://www.php.net/manual/en/language.oop5.magic.php#object.serialize)).

If you're using [jenssegers/mongodb](https://github.com/jenssegers/laravel-mongodb), this may warrant [reporting an issue there](https://github.com/jenssegers/laravel-mongodb/issues/new/choose).

**Comment by Giacomo92** [comment]
Thanks for your reply @jmikola . I will open a PR/issue on [jenssegers/mongodb](https://github.com/jenssegers/laravel-mongodb)
