### ISSUE TITLE
phpsize errors

### ISSUE THREAD

**Issue by zainescu** [mongodb/mongo-php-driver#129]
I get the following errors when running phpsize.
/usr/bin/m4:config.m4:429: cannot open `src/libmongoc/build/autotools/m4/ax_pthr                                                                                                                                                             ead.m4': No such file or directory
/usr/bin/m4:config.m4:463: cannot open `src/libbson/build/autotools/CheckAtomics                                                                                                                                                             .m4': No such file or directory
/usr/bin/m4:config.m4:464: cannot open `src/libbson/build/autotools/FindDependen                                                                                                                                                             cies.m4': No such file or directory
/usr/bin/m4:config.m4:465: cannot open `src/libbson/build/autotools/m4/ac_compil                                                                                                                                                             e_check_sizeof.m4': No such file or directory
/usr/bin/m4:config.m4:466: cannot open `src/libbson/build/autotools/m4/ac_create                                                                                                                                                             _stdint_h.m4': No such file or directory
/usr/bin/m4:config.m4:508: cannot open `src/libmongoc/build/autotools/Versions.m                                                                                                                                                             4': No such file or directory
/usr/bin/m4:config.m4:523: cannot open `src/libbson/build/autotools/Versions.m4'                                                                                                                                                             : No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1

**Comment by bjori** [comment]
I guess this resolved it self when you ran "git submodule update --init" ? :)
