### ISSUE TITLE
Support refreshSession method

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-driver#1308]
Hello,
I am writing to request an enhancement to mongodb sessions by adding a method

Much like the relationship between
https://docs.mongodb.com/manual/reference/command/endSessions/
and
https://www.php.net/manual/en/mongodb-driver-session.endsession.php,

It would be nice if there was a method for
https://docs.mongodb.com/manual/reference/command/refreshSessions/
in the mongodb-php-driver to be able to refresh an individual session.

Thank you for your consideration.

**Comment by 719media** [comment]
Hm, I see I was probably mistaken, and the endsession php method is probably based off of the session object itself, as documented loosely here: https://docs.mongodb.com/manual/reference/method/Session/#mongodb-method-Session.endSession

So, I suppose this ticket can be closed, as the php driver is probably just mirroring the session object. It's annoying, because trying to get behavior for allowing a given query to exceed the default 10 min idle timeout is really quite more difficult than I was expecting it to be...

**Comment by 719media** [comment]
Wow thanks for the detailed response.

In my scenario, I am using aggregate(), which appears to have no option for noCursorTimeout (contrast https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-aggregate/ with https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-find/ to see this).

So, if my desire it to avoid the cursor timeout during an `aggregate` using mongodb 5.0, then currently I MUST:
1) start a session (to get the noCursorTimeout behavior)
2) periodically ping during iteration to avoid sessionTimeout (obviously this would assume that a single "loop" of the iteration wouldn't exceed the sessionTimeout, that would be a separate issue)

Makes sense. Although, can you clarify if the automatic refresh behavior that MAY be implemented in the future ([DRIVERS-1602)](https://jira.mongodb.org/browse/DRIVERS-1602) is supposed to be something that happens on implicit sessions as well? Or just explicit sessions? In other words, is DRIVERS-1602 just supposed to make it so I only would use step 1 (start a session) and not step 2?

**Comment by 719media** [comment]
Thanks. One clarifying note. If it is required to start an explicit session before running an aggregate in order to avoid cursor timeout (by means of the session implicitly using noCursorTimeout in the aggregate), can you tell me why this behavior does NOT happen with IMPLICIT sessions already then?
I guess I'm a little confused as to the understanding of "starting a session will use noCursorTimeout" and the fact that every driver operation actually still uses an "implicit" session behind the scenes... as I don't understand then why these implicit sessions are also not utilizing this noCursorTimeout option. I'm missing some basic understanding somewhere...

**Comment by jmikola** [comment]
> If it is required to start an explicit session before running an aggregate in order to avoid cursor timeout (by means of the session implicitly using noCursorTimeout in the aggregate), can you tell me why this behavior does NOT happen with IMPLICIT sessions already then?

As of MongoDB 4.4.8+, any cursor associated with a session should get `noCursorTimeout` automatically applied to it (per [SERVER-6036](https://jira.mongodb.org/browse/SERVER-6036)). No matter whether the operation uses an explicit or implicit session, the `find` or `aggregate` command will include an `lsid` field. That will denote the session on the cursor yielded by the command, and should be all the cursor cares about when deciding to apply `noCursorTimeout`. Apologies if that wasn't clear from [this comment](https://github.com/mongodb/mongo-php-driver/issues/1308#issuecomment-1069214871).

Offhand, I don't know what would happen if an outgoing `find` or `aggregate` omitted an `lsid` field; however, that cannot happen in any driver that implements implicit sessions.

> don't understand then why these implicit sessions are also not utilizing this noCursorTimeout option. I'm missing some basic understanding somewhere...

Note that the `noCursorTimeout` option and the session lifetime are entirely separate concepts. The default lifetime for an idle _cursor_ is ten minutes, and the `noCursorTimeout` option only disables that. Sessions have their own idle timeout, which defaults to 30 minutes (see: [`localLogicalSessionTimeoutMinutes`](https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.localLogicalSessionTimeoutMinutes)). This is discussed in more detail in [Session Idle Timeout](https://docs.mongodb.com/manual/reference/command/find/#session-idle-timeout) within the `find` command documentation, but 

If a session is killed, all operations (including cursors) associated with that session are also killed, and that is the reason for the aforementioned tickets proposing the driver or server automatically refresh sessions. In the meantime, issuing _any_ command (e.g. `ping`, iterating the cursor such that a `getMore` is issued) will also ensure the session is refreshed.

The only reason I suggest using an _explicit_ session is that you can then use that for both the `find` or `aggregate` operation _and_ later to issue your own `ping` command. If the cursor happened to use an _implicit_ session, the application wouldn't have any way to know what session was being used behind the scenes (short of [command monitoring](https://www.php.net/manual/en/class.mongodb-driver-monitoring-commandsubscriber.php), but that'd be a needlessly complicated approach).

**Comment by 719media** [comment]
```
Note that the noCursorTimeout option and the session lifetime are entirely separate concepts. 
```
Yep, totally clear on that, just to confirm.

OK, so following that explanation, the `noCursorTimeout` option in the mongo php library (for example, see https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-find/) really only has application to mongo databases prior to 4.4.8?

Because from 4.4.8+, the find() command would either be using an implicit session, or an explicit session (via the `session` option in that same command, as an example), either of which would be issuing to noCursorTimeout. Is that correct?

**Comment by jmikola** [comment]
> Because from 4.4.8+, the find() command would either be using an implicit session, or an explicit session (via the session option in that same command, as an example), either of which would be basically issuing the noCursorTimeout: true option to the database. Is that correct?

I believe that is correct. I've opened [DOCS-15181](https://jira.mongodb.org/browse/DOCS-15181) to suggest that the server manual clarify this in the `find` command documentation. Depending on how that issue is triaged, I will also suggest that drivers update their downstream documentation for `Collection::find()` methods.

**Comment by 719media** [comment]
OK cool. I think this issue can be closed then! Thank you
