### ISSUE TITLE
Get session timeout from session object

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-driver#1310]
It appears in mongo documentation that there is a way to get the session timeout when starting a session:
https://docs.mongodb.com/manual/reference/command/startSession/
output: timeoutMinutes

In default setup, this value would be expected to be approximately 30 minutes from the current time.

In mongo php library, the start session method:
https://docs.mongodb.com/php-library/current/reference/method/MongoDBClient-startSession/

Returns a session object. However, this session object does not appear to have this timeoutMinutes value stored anywhere. It would be useful to obtain this value to get the expected timeout of a session, in case the db config is different than 30 minutes

**Comment by jmikola** [comment]
Quoting the [`startSession` section of the driver sessions spec](https://github.com/mongodb/specifications/blob/master/source/sessions/driver-sessions.rst#id2):

> Drivers SHOULD generate session IDs locally if possible instead of running the startSession command, since running the command requires a network round trip.

Most drivers (including PHP and libmongoc) do not use the [`startSession`](https://docs.mongodb.com/manual/reference/command/startSession/) command. Instead, they generate session IDs locally (see: [`mongoc_client_start_session`](https://github.com/mongodb/mongo-c-driver/blob/1.21.1/src/libmongoc/src/mongoc/mongoc-client.c#L1286)) and the server, upon seeing an ID for the first time, creates a server-side session automatically.

If you do need to access [`localLogicalSessionTimeoutMinutes`](https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.localLogicalSessionTimeoutMinutes) from your application, I believe you can invoke the [`getParameter`](https://docs.mongodb.com/manual/reference/command/getParameter/) command manually.
