### ISSUE TITLE
No suitable servers // Connection Not found in Host

### ISSUE THREAD

**Issue by Masihgh** [mongodb/mongo-php-driver#1311]
### Bug Report
Hello
No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling hello on '*****:32004']
The code is executed inside the local host without any problems, version 1.13.0 is installed and the driver is the latest version of PHP
But on the host version 1.11.1 is installed
I installed the version compatible with 1.11.1 but the problem was not resolved
How Can I Do?
### Environment
ext-MongoDb:

MongoDB support | enabled
-- | --
MongoDB extension version | 1.11.1
MongoDB extension stability | stable
libbson bundled version | 1.19.1
libmongoc bundled version | 1.19.1
libmongoc SSL | enabled
libmongoc SSL library | OpenSSL
libmongoc crypto | enabled
libmongoc crypto library | libcrypto
libmongoc crypto system profile | disabled
libmongoc SASL | enabled
libmongoc ICU | enabled
libmongoc compression | enabled
libmongoc compression snappy | disabled
libmongoc compression zlib | enabled
libmongoc compression zstd | enabled
libmongocrypt bundled version | 1.2.1
libmongocrypt crypto | enabled
libmongocrypt crypto library | libcrypto

i use last version in xampp version 1.13.0 all rights
but in cpanel alt-php8.1 and this ext i have error

### Test Script
```php
use MongoDB\Client;
$STR = "MONGO_SERVER 4.5 stable url with auth";
$c = new Client($STR_CONN);
$c->DataBase->Collection->find([]);

```

**Comment by jmikola** [comment]
> No suitable servers found (serverSelectionTryOnce set): [connection refused calling hello on '*****:32004']

Please search existing issues for "connection refused calling" and read through previous discussions. This is most certainly not a problem with the driver itself but rather evidence that your environment (either on the PHP or MongoDB side) is not configured properly to allow outgoing connections. This could be any number of things: firewall, security restrictions, routing, etc. A previous answer I shared in https://github.com/mongodb/mongo-php-driver/issues/783#issuecomment-374585106 may have some advice.

> The code is executed inside the local host without any problems, version 1.13.0 is installed and the driver is the latest version of PHP. I use last version in xampp version 1.13.0 all rights

This tells me your local environment is configured properly.

> But on the host version 1.11.1 is installed
> I installed the version compatible with 1.11.1 but the problem was not resolved
> but in cpanel alt-php8.1 and this ext i have error

I assume this is referring to [version 1.11.1 of the extension](https://pecl.php.net/package/mongodb/1.11.1), but I don't understand what "version compatible with 1.11.1" means. Are you referring to the [library](https://github.com/mongodb/mongo-php-library) (i.e. `mongodb/mongodb` Composer package)?

The reference to cPanel here leads me to assume this is indeed a configuration issue in your production environment. I'm not going to be able to assist with that, so I'd advise you to reach out to your web host if you can't resolve this after researching existing discussions.

**Comment by Masihgh** [comment]
Hello
OK Thanks
