### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by prolic** [mongodb/mongo-php-driver#132]
1) The timeout has no exception message
2) The timeout shouldn't occur

see the following tests scripts:

    <?php

    $manager = new MongoDB\Driver\Manager('mongodb://localhost:27017');
    $manager->executeCommand('mongotest', new MongoDB\Driver\Command(['dropDatabase' => 1]));
    
    $bulk = new MongoDB\Driver\BulkWrite();
    $bulk->insert(array(
        'x' => 1
    ));
    $manager->executeBulkWrite('mongotest.test', $bulk);
    
    sleep(1);

    try {
        $bulk = new MongoDB\Driver\BulkWrite();
        $bulk->insert(array(
            'x' => 2
        ));
        $manager->executeBulkWrite('mongotest.test', $bulk);
    } catch (\Exception $e) {
        var_dump($e->getMessage());
    }

Second (legacy driver works as expected):

    <?php
    
    $client = new MongoClient('mongodb://localhost:27017');
    $client->selectDB('mongotest')->drop();
    
    $collection = $client->selectDB('mongotest')->selectCollection('test');
    $collection->insert(array(
        'x' => 1
    ));
    
    sleep(1);
    
    $collection->insert(array(
        'x' => 2
    ));

**Comment by bjori** [comment]
The exception message is empty as.. The exception is wrong. It shouldn't have happened

The `sleep(1)` triggers a "stale connection check" in the driver... Which I implemented backwards, sorry!

**Comment by bjori** [comment]
As a quick fix, you can apply the linked Pull Request.
I'm sure @jmikola will merge it, with appropriate tests, as soon as he can :]

**Comment by prolic** [comment]
will try tomorrow, don't have the time now. thanks for your fast response.

**Comment by prolic** [comment]
For tests: I provided a test-script above, you can use that ;)

**Comment by bjori** [comment]
Yep, thats what I used -- just didn't turn it into a unit test yet :)

Thanks for the report! :)

**Comment by jmikola** [comment]
I'm on it.

**Comment by bjori** [comment]
See also https://jira.mongodb.org/browse/PHPC-487

**Comment by jmikola** [comment]
Will leave this open until #135 is merged and [PHPC-487](https://jira.mongodb.org/browse/PHPC-487) is resolved.

**Comment by jmikola** [comment]
#135 has been merged to master and [PHPC-487](https://jira.mongodb.org/browse/PHPC-487) has been resolved.
