### ISSUE TITLE
[Windows] failure on mongo-c-driver and mongo-php-driver

### ISSUE THREAD

**Issue by Jan-E** [mongodb/mongo-php-driver#1335]
@jmikola @vector-of-bool 
The mongo-c-driver did not compile anymore on Windows (PHP 8/8.1, VS16). See
https://github.com/mongodb/mongo-c-driver/commit/fe2bae72bc733515d766a46a8799783667396590#r77010392 

I had to revert the last commit in this repo as well to compile php_mongodb.dll once again.

**Comment by jmikola** [comment]
Quoting your comment from https://github.com/mongodb/mongo-c-driver/commit/fe2bae72bc733515d766a46a8799783667396590#r77010392:

> This commit is causing a fatal error on Windows, while building php_mongodb.dll for PHP 8.0 and PHP 8.1 with Visual Studio 16:
>
> ```
> mongodb\src\libmongoc\src\libmongoc\src\mongoc\mongoc-crypt.c(1166):
error C2440: 'function': cannot convert from 'const char *' to 'mongocrypt_query_type_t'
> ```
>
> I had to go back to the previous commit to enable building on Windows once again (git checkout ce28cf0)

If you look at the corresponding PHPC commit (https://github.com/mongodb/mongo-php-driver/commit/63540009f7592b9c8a5caeea2bf181f6c4829f15), you'll see that the libmongoc and libmongocrypt submodules were both updated. The error you reported above suggests that you're building PHPC against an outdated version of libmongoc.

The Windows builds on AppVeyor are also passing: https://ci.appveyor.com/project/jmikola/mongo-php-driver

**Comment by Jan-E** [comment]
My bad. For some reason `git submodule update --init` updated only libmongc, not libmongocrypt. So I was building against an old version of libmongocrypt. I reinstalled the module tree and it did compile fine.

Sorry about the fuzz.
