### ISSUE TITLE
Missing Windows DLLs

### ISSUE THREAD

**Issue by lindelius** [mongodb/mongo-php-driver#1368]
Hi,

It seems like there are no available Windows DLLs to be found for version 1.14.0 or later. While these are normally provided through PECL by the Internals team, it would be fantastic if you could share your builds (I assume you have builds for testing?) while they're working on restoring their build environment (https://news-web.php.net/php.internals.win/1241).

Thanks in advance :)

**Comment by alcaeus** [comment]
> I assume you have builds for testing?

Yes - the library is tested on [Appveyor](https://ci.appveyor.com/project/jmikola/mongo-php-driver), with each build also publishing the resulting DLL file (e.g. for the x64 PHP 8.1 build without thread safety, [here](https://ci.appveyor.com/project/jmikola/mongo-php-driver/build/job/choruw5o826kogda/artifacts)). The "problem" is that Appveyor only retains these files for one month. I'll check out pushing artifacts for tag builds to GitHub releases so they remain available.

If you have a PHP environment, you could locate the appropriate build (which would be for the upcoming 1.15 release currently in master) and test if the DLL file works for you. There is one further issue (quoting from the [mailing list](https://news-web.php.net/php.internals.win/1243)):
> But maybe more importantly, we need to avoid DLL hell and ABI breaks for users, so especially if there are libraries involved, we need to make sure that these are the same version, or at least compatible, between different extensions.

To that end, testing a Windows build of the extension would help us know whether publishing these artifacts would be sufficient or whether we need to do more work on this. I don't have a Windows environment at all to test on, so I appreciate any help you could give us 👍

**Comment by lindelius** [comment]
Thanks @alcaeus !

We'll try to do some testing with the latest versions 🙂

**Comment by alcaeus** [comment]
@lindelius for the new 1.14.2 release, I've updated Windows DLLs for for PHP 7.2 up to PHP 8.0 (for x64 and x86 platforms in both thread-safe and non-thread-safe variants). DLLs for PHP 8.2 will be published starting with the 1.15 release series. Please let me know if there are any issues with these files.

We'll be publishing the DLLs as part of the GitHub release process, so I'm closing this ticket. PHPC-2143 involves us publishing them automatically once we tag a release; until then we'll do this process manually.
