### ISSUE TITLE
Cannot find OpenSSL's libraries when I try to install

### ISSUE THREAD

**Issue by pocketmax** [mongodb/mongo-php-driver#138]
sudo pecl install mongodb-beta
...
checking configuring libmongoc... ...
checking Use system libmongoc... no
checking for pkg-config... no
configure: error: Cannot find OpenSSL's libraries

I've tried with/without sudo. I've tried to just install the mongodb lib without the -beta. I have all the openssl libs and dev libs installed and it still gives me this message. I'm using ubuntu utopic

**Comment by pocketmax** [comment]
fixed it...

sudo apt-get install clibcurl4-openssl-dev pkg-config libssl-dev libsslcommon2-dev

**Comment by bjori** [comment]
Do you know if you had libbsl-dev installed, or if installing pkg-config fixed it?

Using pkg-config is generally preferable, but the fallback _should_ work -- but you'll need to provide:
`--with-openssl-dir=/path/to/openssl`

**Comment by bjori** [comment]
(also "-beta" is no longer needed -- the 1.0.0-stable has been released :))

**Comment by pocketmax** [comment]
I already had libssl-dev and pkg-config installed already. After I installed those packages, I did a normal "sudo pecl install mogodb" and it worked without a problem.

**Comment by bjori** [comment]
The configure output said you were missing pkg-config

    checking for pkg-config... no


Anyway, glad everything worked out. Let us know if you find any other issues!

**Comment by pocketmax** [comment]
ug, sorry. I was thinking of a different VM I was testing with. omg, it's the very next line BEFORE the openssl error line and I didn't notice it. Sorry, ID-10T issue.

**Comment by warrenca** [comment]
I'm running in OSX and tried the following commands

```
$ brew reinstall pkg-config
$ brew link openssl --force
$ sudo pecl install mongodb
....
install ok: channel://pecl.php.net/mongodb-1.1.2
configuration option "php_ini" is not set to php.ini location
You should add "extension=mongodb.so" to php.ini
```

**Comment by necromant2005** [comment]
Ubuntu 16.10 
after installing:
sudo apt-get install libssl-dev
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install clibcurl4-openssl-dev pkg-config libssl-dev libsslcommon2-dev

sudo pecl install mongodb
configure: error: Cannot find OpenSSL's libraries
ERROR: `/tmp/pear/temp/mongodb/configure' failed

**Comment by derickr** [comment]
@necromant2005 Can you post your "config.log" somewhere (pastebin.com)? And provide a link here?

**Comment by necromant2005** [comment]
I fixed the issue by installing extra libraries, the whole list
sudo apt-get install -y autoconf g++ make openssl libssl-dev libcurl4-openssl-dev
sudo apt-get install -y libcurl4-openssl-dev pkg-config
sudo apt-get install -y libsasl2-dev

**Comment by zakhttp** [comment]
@pocketmax i did the same and it worked! thanks!

**Comment by Devidian** [comment]
@necromant2005 Thanks, worked for me on Debian 8.3 too!

**Comment by michelwilhelm** [comment]
On Ubuntu 16.04 I removed libcurl14-openssl-dev and works too

**Comment by ostojicmilica** [comment]
I am on Ubuntu 14.10 and I get same error but when I try to run everything that @necromant2005 said I get errors:

E: Package 'pkg-config' has no installation candidate
E: Unable to locate package libsasl2-dev

**Comment by jmikola** [comment]
@ostojicmilica: Those look like `apt-get` errors. Both of those packages should certainly exist in 14.04:

 * http://packages.ubuntu.com/trusty/pkg-config
 * http://packages.ubuntu.com/trusty/libsasl2-dev

If you're unable to get those installed, you may want to inquire in an Ubuntu support forum.

AFAIK, our [config.m4](https://github.com/mongodb/mongo-php-driver/blob/1.1.6/config.m4) only relies on `pkg-config` for locating the system libbson or libmongoc libraries. PHP core also uses it for locating SSL libraries in [`PHP_SETUP_OPENSSL()`](https://github.com/php/php-src/blob/ee8f402af8c964acac5740ee1677a7b47e20a883/acinclude.m4#L2314); however, they [fall back](https://github.com/php/php-src/blob/ee8f402af8c964acac5740ee1677a7b47e20a883/acinclude.m4#L2354) to searching common system paths if `pkg-config` is not available. For SASL, which is specific to the driver, we merely search some common system paths (i.e. `pkg-config` is not used).

Explicit paths for both OpenSSL and SASL may be set with the `--with-openssl-dir=/path/to/ssl` and `--with-mongodb-sasl=/path/to/sasl` options to the `configure` script, respectively. In that case, `pkg-config` would not be needed for detecting OpenSSL.

**Comment by ostojicmilica** [comment]
Maybe the problem is because I dont use 14.04, but 14.10 Ubuntu .

And can you tell me how to find these paths?

**Comment by jmikola** [comment]
> Maybe the problem is because I dont use 14.04, but 14.10 Ubuntu .

My mistake for misreading your last post. The packages are still present in 14.10, though:

 * http://packages.ubuntu.com/wily/pkg-config
 * http://packages.ubuntu.com/wily/libsasl2-dev

The OpenSSL library path will contain `include/openssl/evp.h` within it. The SASL library path should contain `include/sasl/sasl.h` within it. I'm discerning this by walking through the search logic in [`PHP_SETUP_OPENSSL()`](https://github.com/php/php-src/blob/ee8f402af8c964acac5740ee1677a7b47e20a883/acinclude.m4#L2314) and this extensions' [`config.m4`](https://github.com/mongodb/mongo-php-driver/blob/1.1.6/config.m4) file; however, I do not have a specific answer for your environment.

I should reiterate that if you are receiving the following errors:

> E: Package 'pkg-config' has no installation candidate
> E: Unable to locate package libsasl2-dev

...that really hints at a problem with your operating system's package manager and is likely outside the scope of this PHP extension.

**Comment by Syrok** [comment]
last solution:
`sudo apt-get install pkg-config libssl-dev`

**Comment by nmeegama** [comment]
Small correction for this command that I came across
sudo apt-get install clibcurl4-openssl-dev pkg-config libssl-dev libsslcommon2-dev
Error :  Unable to locate package clibcurl4-openssl-dev

So I tried 
sudo apt-get install pkg-config libssl-dev libsslcommon2-dev
And this still worked

**Comment by geoherna** [comment]
necromant2005 's solution worked perfectly for me. Thanks ! 🍻

**Comment by jmikola** [comment]
I've created [PHPC-1237](https://jira.mongodb.org/browse/PHPC-1237) so we can improve the installation notes on PHP.net to list a number of packages from https://github.com/mongodb/mongo-php-driver/issues/138#issuecomment-184749966. The current documentation is OS-agnostic, but I realize it'd be more helpful to list package names for the most common Linux distributions (e.g. Debian/Ubuntu and perhaps Fedora/CentOS).
