### ISSUE TITLE
Compile error in src/bson.c on ARM/Raspian

### ISSUE THREAD

**Issue by 3keerw** [mongodb/mongo-php-driver#139]
On OSX all compiles well; CPP output:
```
# 496 "/usr/local/src/mongo-php-driver-prototype/src/bson.c"
 return 0;
}
_Bool php_phongo_bson_visit_int64(const bson_iter_t *iter __attribute__ ((unused)), const char *key, int64_t v_int64, void *data)
{
 zval *retval = &((php_phongo_bson_state *)data)->zchild;
 add_assoc_long_ex(retval, key, strlen(key), v_int64);; 
 return 0;
}
```

On Linux 4.1.7-v7+ armv7l / Raspbian GNU/Linux 8.0 (jessie) the same code generates:
```
# 496 "/var/local/src/mongo-php-driver-prototype/src/bson.c"
 return 0;
}

_Bool php_phongo_bson_visit_int64(const bson_iter_t *iter __attribute__ ((unused)), const char *key, int64_t v_int64, void *data)
{
 zval *retval = &((php_phongo_bson_state *)data)->zchild;

 if (v_int64 > 2147483647L || v_int64 < (-2147483647L - 1L)) { char *tmp; int tmp_len; mongoc_log(MONGOC_LOG_LEVEL_WARNING, "PHONGO-BSON", "Integer overflow detected on your platform: %lld", v_int64); tmp_len = spprintf(&tmp, 0, "%lld", v_int64); add_assoc_stringl; } else { add_assoc_long_ex(retval, key, strlen(key), v_int64); };

 return 0;
}
```

with the following errors:
```
/var/local/src/mongo-php-driver-prototype/src/bson.c: In function ‘php_phongo_bson_visit_int64’:
/var/local/src/mongo-php-driver-prototype/src/bson.c:508:38: error: macro "add_assoc_stringl" passed 5 arguments, but takes just 4
  ADD_ASSOC_INT64(retval, key, v_int64);
                                      ^
In file included from /var/local/src/mongo-php-driver-prototype/src/bson.c:38:0:
./phongo_compat.h:112:3: error: ‘add_assoc_stringl’ undeclared (first use in this function)
   add_assoc_stringl(zval, key, tmp, tmp_len, 0); \
   ^
/var/local/src/mongo-php-driver-prototype/src/bson.c:508:2: note: in expansion of macro ‘ADD_ASSOC_INT64’
  ADD_ASSOC_INT64(retval, key, v_int64);
  ^
./phongo_compat.h:112:3: note: each undeclared identifier is reported only once for each function it appears in
   add_assoc_stringl(zval, key, tmp, tmp_len, 0); \
   ^
/var/local/src/mongo-php-driver-prototype/src/bson.c:508:2: note: in expansion of macro ‘ADD_ASSOC_INT64’
  ADD_ASSOC_INT64(retval, key, v_int64);
  ^
```

**Comment by bjori** [comment]
ef95a346 (Andi Gutmans                   2001-01-20 19:16:38 +0000 391) #define add_assoc_stringl(__arg, __key, __str, __length, __duplicate) add_assoc_stringl_ex(__arg, __key, strlen(__key)+1, __str, __length, __duplicate)

Are you compiling against PHP7?
For PHP7 support you have to use the PHP7 branch for now, or merge in Pull Request https://github.com/mongodb/mongo-php-driver/pull/136

**Comment by bjori** [comment]
Actually, don't use the PHP7 branch -- use the Pull Request https://github.com/mongodb/mongo-php-driver/pull/136
It appears the branch is out of date after @jmikola latest changes

**Comment by 3keerw** [comment]
Yes, I compiled the PHP7 first with a rather large set of modules, that went well. Both on OS-X 10.9.5 and Raspi Jessie (latest).
Then this mongo-php-driver went well on OS-X too.
But not on Raspi (against PHP7).
I ran the cpp (-E) to show above mentioned error.,
As I have other priorities right know, can't dive into it, and posted the problem here.

**Comment by bjori** [comment]
The current release (1.0.0) nor the current master branch compile against PHP7.
That issue is tracked in https://jira.mongodb.org/browse/PHPC-285 and there is an open Pull Request (https://github.com/mongodb/mongo-php-driver/pull/136) that adds PHP7 support.

The code you posted for OSX is not generated from the same code as you posted for ` Linux 4.1.7-v7+ armv7l / Raspbian GNU/Linux 8.0 (jessie) `.
The OSX version is actually very old. The boundry check was added in b63315086b6fde9c36a07c079986a119aa4b618c (0.4.0) :]

Anyway. Please refer to the linked Pull Request and make sure you merge it before attempting to compile against PHP7.
PHP7 support is scheduled for very very soon :)
