### ISSUE TITLE
Building for OS X and homebrew

### ISSUE THREAD

**Issue by sc0rp10** [mongodb/mongo-php-driver#142]
Hello, I trying to make missing Homebrew (OS X package manager) package for PHP7, but I have some troubles with building extension from source.
When I run `make -j6 all` I see error `mongo-php-driver-prototype/src/contrib/php-ssl.h:33:10: fatal error: 'openssl/evp.h' file not found`. I have installed openssl in my system, but i don't know how to link openssl with this extension.
Maybe someone can help me with building this extension?
Thanks.

**Comment by bjori** [comment]
Which OS X is that?
If this is the latest osx, then you have to brew install openssl
At the end of it, it'll tell you where it installed openssl.
Take that path and pass it to configure, for example:

    ./configure --with-openssl-dir=/usr/local/Cellar/openssl/1.0.1j

**Comment by sc0rp10** [comment]
@bjori thanks for advice, i had installed openssl, but i needed to execute `brew link openssl` and configure extension again. Now everything is fine, i've pushed Homebrew formula with your extension to homebrew-php repository. Thanks for quick reply!
