### ISSUE TITLE
Adding configure options for zstd, snappy, zlib?

### ISSUE THREAD

**Issue by crazywhalecc** [mongodb/mongo-php-driver#1427]
### Bug Report

I need to compile php with mongodb extension and make it statically linked. When I compile on MacOS, if I use Homebrew to install the dynamic link libraries for zstd and Snappy, and my pkg-config does not specify a system directory, it will also check for success during configure. But in the end, when executing the make command, it was prompted that the symbol could not be found.

Is there a way to add a few parameters here, such as `--without-mongodb-zstd`, `--without-mongodb-snappy`?

### Environment

macOS Ventura, same as GitHub Action macOS Runner, and installed `snappy,zstd,zlib`.

### Test Script

The project [static-php-cli](/crazywhalecc/static-php-cli) can compile a static binary of php, and I just found that mongodb cannot be compiled on macOS. Summary steps below:

1. extract mongodb source code to `php-src/ext/mongodb` directory.
2. `./buildconf --force`
3. `./configure --enable-mongodb  --with-mongodb-system-libs=no  --with-mongodb-sasl=no   --with-mongodb-icu=no PKG_CONFIG="/custom/pkg-config" PKG_CONFIG_PATH="/custom/buildroot/lib/pkgconfig/"`
4. `make -j8`

**Comment by jmikola** [comment]
I don't see any reason we can't expose configure options for those libraries. I've created [PHPC-2236](https://jira.mongodb.org/browse/PHPC-2236) to track the request.

**Comment by jmikola** [comment]
@crazywhalecc: https://github.com/mongodb/mongo-php-driver/pull/1438 adds configure options for the three compression libraries. If you're able to test that patch out locally and confirm it satisfies your needs that would be much appreciated.

**Comment by alcaeus** [comment]
PR was merged, this will be released in 1.16 shortly.
