### ISSUE TITLE
apache stop when I added extension=mongodb.so to php.ini

### ISSUE THREAD

**Issue by ibtissamwannas** [mongodb/mongo-php-driver#1431]
Hello, 
I am trying to install mongo php driver and it installed using this:

```
sudo CFLAGS="-I/Applications/XAMPP/xamppfiles/include" LDFLAGS="-L/Applications/XAMPP/xamppfiles/lib" /Applications/XAMPP/xamppfiles/bin/pecl install mongodb
```

```
ibtissamalwannas@Ibtissams-MacBook-Pro ~ % php -i | grep mongodb
mongodb
mongodb.debug => no value => no value
PATH => /Applications/XAMPP/xamppfiles/bin:/opt/homebrew/opt/mongodb-community@6.0/bin:/Users/ibtissamalwannas/FlutterDev/flutter/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
$_SERVER['PATH'] => /Applications/XAMPP/xamppfiles/bin:/opt/homebrew/opt/mongodb-community@6.0/bin:/Users/ibtissamalwannas/FlutterDev/flutter/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
```

but when I add `extension=mongodb.so` to php.ini, apache web server in xampp stoped that is what I get in log

```
[Sun Jun 11 10:50:24.982483 2023] [ssl:warn] [pid 74918] AH01906: www.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Sun Jun 11 10:50:24.982520 2023] [ssl:warn] [pid 74918] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 11 10:50:24.982664 2023] [lbmethod_heartbeat:notice] [pid 74918] AH02282: No slotmem from mod_heartmonitor
dyld[74917]: Assertion failed: (this->magic == kMagic), function loadAddress, file Loader.cpp, line 81.
```

php version:

```
PHP 8.2.4 (cli) (built: Apr  6 2023 04:12:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
```

mongo php driver version 1.15.3

I tried the solutions that are on previous issues but it doesn't work
I am using macOS Monterey 12.5,
I tried it on windows it installed without any issue.

**Comment by ibtissamwannas** [comment]
Any one can help ???

**Comment by alcaeus** [comment]
Apologies for the delay here. Looking at the error log from Apache, I fail to see what's going on. The assertion failure isn't triggered by PHP itself, and an extensive search didn't yield any significant results for that error. Aside from trying to minimise potential other causes (e.g. by running a minimal PHP version without lots of extensions, disabling other Apache modules, etc.) I'm not sure what else we can do to help with this.

I would suggest asking in the xampp support channels for help as it seems unrelated to the MongoDB extension itself.

**Comment by ibtissamwannas** [comment]
Ok thank you
