### ISSUE TITLE
The DSP mongodb.dsp does not exist

### ISSUE THREAD

**Issue by justin-frenzel** [mongodb/mongo-php-driver#145]
I seem to be getting an error: "The DSP mongodb.dsp does not exist" when I try to install this via the "pecl install mongodb-beta" command.

Anyone have any ideas on why this might be happening, and what I can do to fix it?

I'm running Windows 7 x64. If it's not possible to install this on Windows via PECL, is there a different way to get use this library?

Let me know, thanks!

**Comment by bjori** [comment]
Windows DLLs are available on "PECL", you don't have to "pecl install mongodb" when you are on Windows.

Instead, you have to manually download the latest release by going to

https://pecl.php.net/package/mongodb and then select the "Windows (DLL)" icon next to the latest release
(currently https://pecl.php.net/package/mongodb/1.0.0/windows).

Then you select the PHP version use are using (PHP5.5, or 5.6).
The exact "thread safe" or "x86" or "x64" depends on which PHP installation you are using.
See http://windows.php.net/ for more on these terms and what to pick.

**Comment by derickr** [comment]
@bjori's comment is right. There should be a DLL for you to download. There will not be a DSP, as that is (for a long time now) no longer an existing Windows compile option either.

**Comment by huma-m** [comment]
I got the same error and there is not DLL available for the latest version. Is there any other way to install it?
