### ISSUE TITLE
Extract mongodb-1.6.2.tgz error

### ISSUE THREAD

**Issue by jingjingxyk** [mongodb/mongo-php-driver#1459]
### Bug Report
```shell

curl  --connect-timeout 15 --retry 5  --retry-delay 5  -Lo '/work/pool/ext/mongodb-1.6.2.tgz' 'https://pecl.php.net/get/mongodb-1.6.2.tgz' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    34  100    34    0     0     29      0  0:00:01  0:00:01 --:--:--    29

tar --strip-components=1 -C /work/ext/mongodb -xf /work/pool/ext/mongodb-1.6.2.tgz
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


```

### Environment
alpine  3.17   php8.2    mongodb-1.6.2.tgz

### Test Script

```bash
curl  --connect-timeout 15 --retry 5  --retry-delay 5  -Lo '/work/pool/ext/mongodb-1.6.2.tgz' 'https://pecl.php.net/get/mongodb-1.6.2.tgz'

tar --strip-components=1 -C /work/ext/mongodb -xf /work/pool/ext/mongodb-1.6.2.tgz


```
### Expected and Actual Behavior

> use mongodb-1.6.1.tgz  no error 

```bash
curl  --connect-timeout 15 --retry 5  --retry-delay 5  -Lo '/work/pool/ext/mongodb-1.6.1.tgz' 'https://pecl.php.net/get/mongodb-1.6.1.tgz' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1068k  100 1068k    0     0   428k      0  0:00:02  0:00:02 --:--:--  428k

tar --strip-components=1 -C /work/ext/mongodb -xf /work/pool/ext/mongodb-1.6.1.tgz


```

**Comment by alcaeus** [comment]
Looking at the downloaded file, it contains the following:
> File 'mongodb-1.6.2.tgz' not found

This is expected, as there was no 1.6.2 release (1.6.1 was followed by 1.7.0). Did you mean to download 1.16.2, which was recently released?

**Comment by jingjingxyk** [comment]
https://pecl.php.net/package/mongodb

**Comment by alcaeus** [comment]
@jingjingxyk Yes, that would be the correct download URL for 1.16.2, and I have confirmed that it works as expected. I'm closing this issue here as there is no problem: 1.6.2 would never work as it doesn't exist.

**Comment by Frzk** [comment]
Hello there,
The release page (https://github.com/mongodb/mongo-php-driver/releases/tag/1.16.2) still misses the usual `mongodb-1.16.2.tgz` asset.
Would it be possible to upload it and make it available in Github too?
Thanks a billion :)

**Comment by alcaeus** [comment]
@Frzk thanks for pointing it out. I've attached the file to the release.
