### ISSUE TITLE
php7 install error

### ISSUE THREAD

**Issue by CloudXNS** [mongodb/mongo-php-driver#147]
$ git clone -b PHP7 https://github.com/mongodb-labs/mongo-php-driver-prototype.git
$ cd mongo-php-driver-prototype
$ git submodule update --init
$ phpize
$ ./configure
$ make -j6 all

-op.c  -fPIC -DPIC -o src/libmongoc/src/mongoc/.libs/mongoc-matcher-op.o
/opt/mongo-php-driver-prototype/src/libmongoc/src/mongoc/mongoc-matcher-op.c: In function '_mongoc_matcher_op_compare_new':
/opt/mongo-php-driver-prototype/src/libmongoc/src/mongoc/mongoc-matcher-op.c:166: error: #pragma GCC diagnostic not allowed inside functions
/opt/mongo-php-driver-prototype/src/libmongoc/src/mongoc/mongoc-matcher-op.c:167: error: #pragma GCC diagnostic not allowed inside functions
/opt/mongo-php-driver-prototype/src/libmongoc/src/mongoc/mongoc-matcher-op.c:172: error: #pragma GCC diagnostic not allowed inside functions
make: *** [src/libmongoc/src/mongoc/mongoc-matcher-op.lo] Error 1

**Comment by bjori** [comment]
The master branch does not currently support PHP7.
See https://jira.mongodb.org/browse/PHPC-285 (and related tickets) for the latest progress.

The current wip is unfortunately no longer in the PHP7 branch, but tracked in the Pull Request: https://github.com/mongodb/mongo-php-driver/pull/136

**Comment by CloudXNS** [comment]
git clone -b PHP7 https://github.com/mongodb-labs/mongo-php-driver-prototype.git
this is PHP7 branch
