### ISSUE TITLE
Windows build after 1.13.0

### ISSUE THREAD

**Issue by Geolim4** [mongodb/mongo-php-driver#1507]
### Bug Report
Hello,

Can you release a Windows build please ?
It's been a long time we haven't had one :(
https://pecl.php.net/package/mongodb

Thanks you,
Georges

### Environment
Windows 11

### Test Script
N/A

### Debug Log
N/A

**Comment by jmikola** [comment]
PECL stopped producing Windows builds over a year ago (see [this PHP internals thread](https://externals.io/message/117494#120114) for context). Since 1.14.2, we now attach Windows builds to [GitHub releases](https://github.com/mongodb/mongo-php-driver/releases).

**Comment by Geolim4** [comment]
Ohh ok I understand now, thanks.

Can you add, as the Pecl Maintainer, a mention somewhere on pecl page about the releases you made ?

Thanks you :D

**Comment by jmikola** [comment]
This was already communicated in [Installing the MongoDB PHP Driver on Windows](https://www.php.net/manual/en/mongodb.installation.windows.php) within the extension documentation on PHP.net. There isn't really a good place to note this in the PECL UI, but I've added some text to the project description on https://pecl.php.net/package/mongodb.

**Comment by Geolim4** [comment]
Thanks 👍🏻
