### ISSUE TITLE
Expected "writeConcern" option to have type "MongoDB\Driver\WriteConcern" but found "array"

### ISSUE THREAD

**Issue by sc0rp10** [mongodb/mongo-php-driver#153]
Exception threw in vendor/mongodb/mongodb/src/Operation/InsertOne.php:45
composer.lock: 
``` {
    "name": "mongodb/mongodb",
    "version": "1.0.0-beta1"
}```

**Comment by bjori** [comment]
Can you paste your example code?

It looks like you might be doing `$collection->insertOne($document, $options);` where `$options["writeConcern"]` is not an instance of `MongoDB\Driver\WriteConcern`

**Comment by sc0rp10** [comment]
oh, sorry.
```
/** @var MongoDB\Collection $collection */
$collection->insertOne([
    'foo' => 'bar',
]);
```

**Comment by sc0rp10** [comment]
I've created MongoDB\Collection with $writeConcern = null.
Below I see `$this->writeConcern = $writeConcern ?: $this->manager->getWriteConcern();`
`var_dump($this->manager->getWriteConcern())` in vendor/mongodb/mongodb/src/Collection.php:69 shows
```
array(4) { ["wmajority"]=> bool(false) ["wtimeout"]=> int(0) ["fsync"]=> NULL ["journal"]=> NULL }
```

**Comment by sc0rp10** [comment]
My mongodb.so was built from PHP7 branch of this repo, because I'm using php7

**Comment by bjori** [comment]
The `var_dump` will call the debug handler on the object, which is why you see it as array.
If you do

    $wc = $this->manager->getWriteConcern();
    var_dump(get_class($wc), $wc);

it should print out `MongoDB\Driver\WriteConcern`

**Comment by sc0rp10** [comment]
I got 'Warning: get_class() expects parameter 1 to be object, array given'

**Comment by bjori** [comment]
heh. uhm.. OK.... thats weird!

**Comment by bjori** [comment]
Can you try this for me:

    $ php -r '$manager = new MongoDB\Driver\Manager("mongodb://localhost:27017");  $wc = $manager->getWriteConcern(); var_dump($wc);'

I get the following:
```
object(MongoDB\Driver\WriteConcern)#2 (4) {
  ["w"]=>
  NULL
  ["wmajority"]=>
  bool(false)
  ["wtimeout"]=>
  int(0)
  ["journal"]=>
  NULL
}
```

**Comment by sc0rp10** [comment]
```
 php -v && php -r '$manager = new MongoDB\Driver\Manager("mongodb://localhost:27017");  $wc = $manager->getWriteConcern(); var_dump($wc);'
PHP 7.0.0 (cli) (built: Dec  5 2015 00:06:25) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC2, Copyright (c) 2002-2015, by Derick Rethans
array(4) {
  ["wmajority"]=>
  bool(false)
  ["wtimeout"]=>
  int(0)
  ["fsync"]=>
  NULL
  ["journal"]=>
  NULL
}
```

**Comment by bjori** [comment]
Ahhh. Found it.
You are using the PHP7 branch. It is no longer the most-up-2-date. @jmikola has a PR that is the latest version -- not entirely sure why its not merged into the branch or the branch deleted..

Using his PR it works for me (tm).

See: https://github.com/mongodb/mongo-php-driver/pull/136

**Comment by sc0rp10** [comment]
I've said it earlier: https://github.com/mongodb/mongo-php-driver/issues/153#issuecomment-162665375 :-)
Ok, thx, I'll be watch for progress.

**Comment by bjori** [comment]
Yeah, sorry. I mistakenly read it as if you were using @jmikola PHP7 branch, as thats what I was using hehe. Sorry :)

**Comment by jmikola** [comment]
https://github.com/mongodb/mongo-php-driver/pull/175 (PHP 7 support) has been merged to master, so I think this can be closed. We should have a release with those changes out in a day or two. Feel free to re-open if that's not the case.
