### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by oerdnj** [mongodb/mongo-php-driver#159]
Folks, the package.xml (and PECL) says "New BSD License", but the LICENSE file is Apache 2.0. Could you please fix the discrepancy?

**Comment by bjori** [comment]
I've updated the PECL page to say Apache, and sent PR for the package.xml generation script.

It was just the package file that was incorrect. All the files are Apache licensed.

**Comment by jmikola** [comment]
Resolving, as #161 has been merged.
