### ISSUE TITLE
Creating indexes

### ISSUE THREAD

**Issue by xplodwild** [mongodb/mongo-php-driver#170]
Hello

I couldn't find any example using the new MongoDB Driver (using it in PHP7 fwiw) on how to run commands such as createIndex/ensureIndex on a collection?

I tried using the executeCommand method, but it seems like it's intended only for management/administration commands, and not collection methods.

Thanks!

**Comment by bjori** [comment]
Keep in mind that the raw driver is not meant to be used directly.
The main gateway should be the https://github.com/mongodb/mongo-php-library which contains helper methods for this sort of functionality.

Using the raw driver requires extensive knowledge of inner workings of MongoDB, and all its internal commands -- such as how to create an index.

To get you quickly running, here is how it works in MongoDB 2.6 and later:

```php
<?php
$manager = new MongoDB\Driver\Manager("mongodb://127.0.0.1:27017");
$command = new MongoDB\Driver\Command([
    "createIndexes" => "collectionName",
    "indexes"       => [[
        "name" => "indexName",
        "key"  => [ "keyName" => 1],
        "ns"   => "databaseName.collectionName",
    ]],
]);
$result = $manager->executeCommand("databaseName", $command);
var_dump($result->toArray());
````
