### ISSUE TITLE
php 7 support

### ISSUE THREAD

**Issue by agiuliano** [mongodb/mongo-php-driver#171]
When trying to install mongodb with `pecl install mongodb` I get
`pecl/mongodb requires PHP (version >= 5.4.0, version <= 5.99.99), installed version is 7.0.0`

**Comment by bjori** [comment]
See: https://jira.mongodb.org/browse/PHPC-285

PHP7 support hasn't been released (or merged) just yet.. It is coming.. very very soon :)
