### ISSUE TITLE
phpize failed

### ISSUE THREAD

**Issue by anhzhi** [mongodb/mongo-php-driver#176]
/usr/bin/m4:config.m4:438: cannot open `src/libmongoc/build/autotools/WeakSymbols.m4': No such file or directory
/usr/bin/m4:config.m4:439: cannot open `src/libmongoc/build/autotools/m4/ax_pthread.m4': No such file or directory
/usr/bin/m4:config.m4:473: cannot open `src/libbson/build/autotools/CheckAtomics.m4': No such file or directory
/usr/bin/m4:config.m4:474: cannot open `src/libbson/build/autotools/FindDependencies.m4': No such file or directory
/usr/bin/m4:config.m4:475: cannot open `src/libbson/build/autotools/m4/ac_compile_check_sizeof.m4': No such file or directory
/usr/bin/m4:config.m4:476: cannot open `src/libbson/build/autotools/m4/ac_create_stdint_h.m4': No such file or directory
/usr/bin/m4:config.m4:520: cannot open `src/libmongoc/build/autotools/Versions.m4': No such file or directory
/usr/bin/m4:config.m4:534: cannot open `src/libbson/build/autotools/Versions.m4': No such file or directory

**Comment by bjori** [comment]
When you checkout for git you need to:

    $ git submodule update --init

**Comment by ZhiweiYuan** [comment]
after git clone and git submodule, phpize.
when ./configure , error occur.
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
checking for PHP extension directory... /usr/lib/php5/20121212+lfs
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking PHP version... 50509
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking Use system libbson... no
checking configuring libmongoc... ...
checking Use system libmongoc... no
checking for pkg-config... /usr/bin/pkg-config
checking pcre-dir install prefix
  --with-pcre-dir=DIR     mongodb: pcre install prefix... yes, shared
checking for pcre... not found
checking Build with Cyrus SASL support... yes, shared
checking for SASL... not found
configure: error: sasl.h not found!

**Comment by bjori** [comment]
You must have "cyrus-sasl" and its -dev package installed to.

I've filed a ticket to document this properly on https://jira.mongodb.org/browse/PHPC-520

**Comment by yonisolo** [comment]
It could be quite interesting to have this info in a build section of the home page...
Howaver it works for me too,
Thanks!
