### ISSUE TITLE
Count Method

### ISSUE THREAD

**Issue by mitchc32** [mongodb/mongo-php-driver#178]
Is there a plan to implement the count method as it was in the previous pecl/mongo package?

**Comment by bjori** [comment]
I think thats unlikely.

The way the count method worked was it would *re-execute* the query -- resulting in a new roundtrip -- but worse yet, had a document been added or removed, would not result in the same number as the cursor was iterating over.

There is no way to get the number of documents a cursor is wrapping. While thats not possible I think its important that the actual count command will need to be executed separately to make that obvious.

**Comment by jmikola** [comment]
For added context, see the explanation in https://github.com/mongodb/mongo-php-driver/issues/195#issuecomment-169405194.
