### ISSUE TITLE
bson and mongoc versions in Windows builds

### ISSUE THREAD

**Issue by Jan-E** [mongodb/mongo-php-driver#181]
When building on windows with http://pecl.php.net/get/mongodb-1.1.1.tgz the versions are reported as follows:

    mongodb version 	1.1.1 
    mongodb stability 	stable 
    libmongoc version 	1.1.2 
    libbson version 	1.1.3

However, looking at VERSION_CURRENT and VERSION_RELEASED in src/libbson and src/libmongoc in that tarball libbson seems v1.3.0 and libmongoc is v1.3.1-dev. Can the win32/*-version.h files be updated? In an ideal world that would be done automatically by the pecl packaging script, but I do not know if that is possible.

**Comment by bjori** [comment]
See:
- https://jira.mongodb.org/browse/PHPC-447
- https://jira.mongodb.org/browse/PHPC-481

**Comment by jmikola** [comment]
Closing this out since we have tracking tickets in JIRA. Please follow those for future updates.
