### ISSUE TITLE
Cannot append reference to bson

### ISSUE THREAD

**Issue by Martin1994** [mongodb/mongo-php-driver#182]
My environment:
* Win 10
* IIS 10
* PHP 7.0.0 NTS x64 / PHP 5.5.20 TS x64 with FastCGI
* mongodb 3.2.0
* mongodb (php driver) 1.1.1

I failed to write associative array with reference value to db.

The following codes should reproduce this issue:
````PHP
$some_field = array();

$data = array(
    'some_field' => &$some_field
);

$bulk = new BulkWrite();
$bulk->insert($data);
````

The exception message is:
`PHP Fatal error:  Uncaught MongoDB\Driver\Exception\UnexpectedValueException: Got unsupported type 10 'unknown'`
Type 10 is `IS_REFERENCE` defined in zend_types.h

It works after removing the `&` operator in line 3.

**Comment by jmikola** [comment]
Tracking in [PHPC-528](https://jira.mongodb.org/browse/PHPC-528). Thanks for the report.
