### ISSUE TITLE
Issue with Collection->findOne()

### ISSUE THREAD

**Issue by jeremyhodges** [mongodb/mongo-php-driver#183]
When I try and use the MongoDB\Collection->findOne, my PHP script completely dies without even returning any kind of error. If I open my apache logs I see:

```
/var/tmp/mongodb/src/libmongoc/src/mongoc/mongoc-cursor.c:52 _mongoc_n_return(): precondition failed: remaining > 0
[Tue Dec 22 21:35:46.198539 2015] [core:notice] [pid 812] AH00052: child pid 2206 exit signal Aborted (6)
```

I'm running on CentOS 7 and I know the query should be returning a single result.

```
$mongo = new MongoDB\Driver\Manager("mongodb://localhost:27017");
$receipts = new MongoDB\Collection($mongo, $databaseName.".receipts");
      
$r = $receipts->findOne(["receipt_id" => 1062792739]);
```

Change `findOne()` to `find()` and I have no issue. Cursor is returned with a single result.

**Comment by BradDodi** [comment]
Same issue here, connection is killed when using `findOne` yet `find` works fine. This is since upgrading to version 1.1.0 of the driver, previous versions worked fine.

**Comment by markz440** [comment]
Had the same problem. This has already been fixed here: https://github.com/mongodb/mongo-php-library/commit/ddd509092f21280756ec002ba6a28e162e0218ba but didn't make it into a release yet. If you need, you can apply the change manually in `vendor/mongodb/mongodb/src/Operation/FindOne.php`.

**Comment by BradDodi** [comment]
Thanks markz440, that's fixed it!

**Comment by jmikola** [comment]
[1.0.0-beta2](https://github.com/mongodb/mongo-php-library/releases/tag/1.0.0-beta2) of mongo-php-library has been tagged, which should also include this fix. Sorry for the delay on that.
