### ISSUE TITLE
Howto new a query with regex in php?

### ISSUE THREAD

**Issue by ejzhang** [mongodb/mongo-php-driver#186]
I new a query as follow, but the execute result is empty, what is it wrong?
```$query = new MongoDB\Driver\Query( array( 'FieldName' => new MongoDB\BSON\Regex( '/^Test/', 'i' ) ), array( 'sort' => array( 'OrderBy' => -1 ) ) );```

**Comment by ejzhang** [comment]
It's Ok. Thanks!
```$query = new MongoDB\Driver\Query( array( 'FieldName' => new MongoDB\BSON\Regex( '^Test', 'i' ) ), array( 'sort' => array( 'OrderBy' => -1 ) ) );```

**Comment by jmikola** [comment]
Thanks for asking, and following up when you found a solution! I improved the documentation a bit in [this commit](http://svn.php.net/viewvc?view=revision&revision=338408), which will hopefully benefit other users.

**Comment by fpiraneo** [comment]
Hi, it seems that this improvement is lost on the new doc; can you put a reference on the find method? Thanks! :-)

**Comment by derickr** [comment]
@fpiraneo - they're still there: http://docs.php.net/manual/en/mongodb-bson-regex.construct.php#refsect1-mongodb-bson-regex.construct-examples

Did I misunderstand you?

**Comment by jmikola** [comment]
> Hi, it seems that this improvement is lost on the new doc; can you put a reference on the find method?

Are you asking that we put a regex example on [Query::__construct()](http://php.net/manual/en/mongodb-driver-query.construct.php) or [Manager::executeQuery()](http://php.net/manual/en/mongodb-driver-manager.executequery.php)? 

> Also I cannot find any indications on how to handle the regular expressions query... any indications will be appreciated!

Assuming this is a general MongoDB question, the [$regex](https://docs.mongodb.com/v3.0/reference/operator/query/regex/#syntax-restrictions) documentation in the manual may address this. Note that there are two forms of querying by a regular expression in MongoDB. `$regex` is a query operator and allows you to specify the pattern and options are BSON string types. The `/pattern/` example in the manual corresponds to the regular expression BSON type (i.e. `MongoDB\BSON\Regex` in the PHP driver), which may be used as you would an equality query:

```php
$query = [ 'numericString' => new MongoDB\BSON\Regex('\d+') ];
```

**Comment by fpiraneo** [comment]
I hope to find the whole documentation about using the regex with find on the new doc page at https://docs.mongodb.com/php-library/master/ , just to have one single reference point for the user.

**Comment by jmikola** [comment]
I'm willing to add a regular expression example to the [CRUD tutorial](https://docs.mongodb.com/php-library/master/tutorial/crud/); however, I'd prefer not to burden the API reference with these examples, as there are dozens of different query operators and we simply cannot demonstrate them all.

**Comment by fpiraneo** [comment]
Thank you for accepting the suggestion; I don't know if there is some complete reference documentation about in the case just put a link; I find the mongo php driver a complex library and i think the documentation should respect such complexity, this for an optimal utilization and to avoid the programmer loosing himself through fake and incorrect post on forums and old and superseeded infos.

**Comment by jmikola** [comment]
> I don't know if there is some complete reference documentation about in the case just put a link

The most complete reference for querying is the MongoDB manual:

 * https://docs.mongodb.com/master/tutorial/query-documents/
 * https://docs.mongodb.com/master/reference/operator/query/

Between the legacy `ext-mongo` extension and the newer `ext-mongodb` extension, the only relevant changes to writing query criteria has been our renamed BSON classes (e.g. `MongoRegex` to `MongoDB\BSON\Regex`).

The task of adding a regular expression example is being tracked in [PHPLIB-243](https://jira.mongodb.org/browse/PHPLIB-243).
