### ISSUE TITLE
Missing OpenSSL headers OSX 10.11

### ISSUE THREAD

**Issue by peterrehm** [mongodb/mongo-php-driver#188]
I am using http://php-osx.liip.ch and I am trying to install mongodb locally on my dev machine (OS X 10.11). Dont get confused by the php5 path, this one is symlinked to the proper php7 path. I had no problems installing it in my vagrant boxes though. Maybe you have a hint how to get it installed.

I already reinstalled the xcode cli tools.

````
git:(php7) ✗ php --version
PHP 7.0.1 (cli) (built: Dec 19 2015 11:03:48) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

git:(php7) ✗ sudo pecl install mongodb
Password:
downloading mongodb-1.1.1.tgz ...
Starting to download mongodb-1.1.1.tgz (642,977 bytes)
.................................................................................................................................done: 642,977 bytes
349 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /private/tmp/pear/temp/pear-build-rootr7JiFb/mongodb-1.1.1
running: /private/tmp/pear/temp/mongodb/configure --with-php-config=/usr/local/php5/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin15.2.0
checking host system type... x86_64-apple-darwin15.2.0
checking target system type... x86_64-apple-darwin15.2.0
checking for PHP prefix... /usr/local/php5
checking for PHP includes... -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php5/lib/php/extensions/no-debug-non-zts-20151012
checking for PHP installed headers prefix... /usr/local/php5/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking PHP version... 70001
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking Use system libbson... no
checking configuring libmongoc... ...
checking Use system libmongoc... no
checking for pkg-config... no
configure: error: Cannot find OpenSSL's <evp.h>
ERROR: `/private/tmp/pear/temp/mongodb/configure --with-php-config=/usr/local/php5/bin/php-config' failed
````

**Comment by bjori** [comment]
OS X 10.11 no longer ships with usable OpenSSL.

You'll have to install it from homebrew (or macports, if thats your thing).

```
$ sudo brew install openssl
```

At the end it will tell you something about not wanting to overwrite the system path as it may have unforeseen consequences, so it'll tell you where it installed the library and the header, along with how to make sure to link to that version:

```
$ export LDFLAGS=-L/usr/local/opt/openssl/lib
$ export CPPFLAGS=-I/usr/local/opt/openssl/include
```

or run `brew install openssl --force` (not recommended).

You don't actually have to export the variables or overwrite the system symlinks.. The PHP configure script has an `--with-openssl-dir` option that takes the path to openssl to build against.

So after installing OpenSSL from homebrew you need to do something like this:
```
$ pecl download mongodb
$ tar zxvf mongodb*.tgz
$ cd mongodb*
$ phpize
$ ./configure --with-openssl-dir=/usr/local/opt/openssl
$ make
$ sudo make install
```

Would be awesome if pecl provided option to avoid all this manual process, like `pecl install mongodb --configure --with-openssl-dir=/usr/local/opt/openssl` but thats not possible at the moment.
We'll hopefully distribute [pharext](https://pharext.org/) archives soon, which would make this much simpler: `./mongodb.ext.phar -c --with-openssl-dir=/usr/local/opt/openssl`


--

***NOTE:*** The path `/usr/local/opt/openssl/` is for reference only. Your path might be different. Check the message at the end of `brew install openssl`.

**Comment by peterrehm** [comment]
Thank you for the detailed information, I will give it a try the coming days. Meanwhile I have it up and running in my VM.

**Comment by peterrehm** [comment]
Awesome, works as expected. I just did `bew install openssl` without `sudo`.

**Comment by vlaw** [comment]
Great, it works!

**Comment by Premitium** [comment]
I still get the configure: error: Cannot find OpenSSL's <evp.h>
even though openssl-1.0.2j is already installed.

**Comment by vrkansagara** [comment]
my comman was `sudo ./pecl install mongodb`

Am still getting this error 

```
configure: error: Cannot find OpenSSL's <evp.h>
ERROR: `/private/tmp/pear/temp/mongodb/configure --with-php-config=/Applications/XAMPP/xamppfiles/bin/php-config' failed
```

**Comment by vrkansagara** [comment]
something work for me https://github.com/mongodb/mongo-php-driver/issues/247#issuecomment-267718753

**Comment by kunal-arowana** [comment]
I was stucked for it so long finally solved

sudo C_INCLUDE_PATH=/usr/local/opt/openssl/include /Applications/XAMPP/xamppfiles/bin/pecl install mongo

Type above command if you are using xamp

Below command if not usinf xamp
sudo C_INCLUDE_PATH=/usr/local/opt/openssl/include pecl install mongo

**Comment by ParhamZare** [comment]
@bjori nice great work

**Comment by kunal-arowana** [comment]
Thanks @ParhamZare

**Comment by TechyTimo** [comment]
Anyone experiencing this issue on a mac try installing using homebrew:

    $ brew tap homebrew/php
    $ brew install php56-mongodb

Then to link the mongodb extension binary on your php.ini

extension='/usr/local/opt/**php56-mongodb**/mongodb.so'

You can suit this process to your preferred php version.

**Comment by sempijjawork** [comment]
```
checking whether to use system libmongoc... no
checking configuring libmongoc... ...
checking for pkg-config... /usr/local/bin/pkg-config
checking for OpenSSL version... >= 0.9.8
checking for CRYPTO_free in -lcrypto... no
configure: error: libcrypto not found!
```

Getting this error

**Comment by jmikola** [comment]
@sempijjawork: Please open a new issue instead of bumping a closed thread. Additionally, you should provide complete information about your environment (e.g. OS, PHP) instead of a small paste from `./configure` output.

**Comment by violapro** [comment]
> Awesome, works as expected. I just did `bew install openssl` without `sudo`.

brew
