### ISSUE TITLE
explain details for update query

### ISSUE THREAD

**Issue by intekhabrizvi** [mongodb/mongo-php-driver#190]
Hi, i am try to capture data given by explain function for update based queries but its not working but Its working fine for find based queries. Is there any plain for the same ??

**Comment by bjori** [comment]
That depends on the method you are using.

The new [explain command](https://docs.mongodb.org/manual/reference/command/explain/#dbcmd.explain) works the same on update and find commands, while the legacy [$explain modifier](https://docs.mongodb.org/manual/reference/operator/meta/explain/) is deprecated and only works for find queries

**Comment by intekhabrizvi** [comment]
Thanks, i am aware of that. I am talking specifically on [PHP Mongo Driver](http://php.net/manual/en/mongocursor.explain.php), how can i get explain data for update query using mentioned php mongo function ?? On my experiment its just returning explain data for find queries.

**Comment by bjori** [comment]
The documentation you linked to is a different driver, it is for the [pecl/mongo driver](https://pecl.php.net/package/mongo) that is deprecated an no longer developed. If you need support for that driver, please ask your questions on support forums, such as [stackoverflow.com](http://stackoverflow.com/questions/tagged/mongodb-php) or [mongodb-user@](https://groups.google.com/forum/#!forum/mongodb-user)

The documentations for this driver [pecl/mongodb driver](https://pecl.php.net/package/mongodb) are located on http://php.net/mongodb.

We generally recommend that people use the pecl/mongodb with our companion userland library: https://github.com/mongodb/mongo-php-library

**Comment by jmikola** [comment]
@intekhabrizvi: The legacy driver you're using does not have helper methods for explaining anything beyond basic queries. Aggregation is theoretically supported via its `explain` command option (documented [here|https://docs.mongodb.org/manual/reference/command/aggregate/]), but we don't have a helper method for the new [explain command](https://docs.mongodb.org/manual/reference/command/explain/) in MongoDB 3.0+. You'll need to use [`MongoDB::command()`](http://php.net/manual/en/mongodb.command.php) to issue an explain command.
