### ISSUE TITLE
How to the value of _id field?

### ISSUE THREAD

**Issue by ejzhang** [mongodb/mongo-php-driver#198]
I use $.post method of jQuery to send a request and received the response, but the _id is empty like  screen capture. How i get the value of _id or convert ObjectId to it's value in MongoDB? Thanks very much!
![image](https://cloud.githubusercontent.com/assets/452491/12164053/59fb2dd4-b54d-11e5-9c5b-baadf113fcb7.png)
btw: How i format fields in MongoDB? e.g. format '20150901180116' to '2015-09-01 18:01:16'.

**Comment by ZorgUK** [comment]
It has a __toString() method, just cast it as a string by putting (string) before the variable.

**Comment by ejzhang** [comment]
Thank you for your reply first!
But how i to do? I try it like bellow, and have an error.
···
$query = new MongoDB \ Driver \ Query (
	array(
		'FPRXM' => ‘XXXXX’
	),
	array(
		'projection' => array(
			'_id' => 0,
			'Id' => '$_id.toString()'
		)
	)
);
···

**Comment by ejzhang** [comment]
I convert it to string after got cursor.
```
foreach ( $cursor as $v ) {
	$v->_id = (string)$v->_id;
}
```
