### ISSUE TITLE
manager->executeInsert() still used in doc examples

### ISSUE THREAD

**Issue by jonnywang** [mongodb/mongo-php-driver#203]
where is executeInsert ?

**Comment by jonnywang** [comment]
![mongodb-error-api 2x](https://cloud.githubusercontent.com/assets/960982/12319137/fa0e92b0-bada-11e5-9790-d110709b4aeb.png)

**Comment by bjori** [comment]
The executeInsert method was removed just before the final 1.0.0 release.
See: https://jira.mongodb.org/browse/PHPC-465

Please use the `Manager->executeBulkWrite` method, see http://php.net/manual/en/mongodb-driver-manager.executebulkwrite.php

I'll leave this ticket open to fix the examples on http://mongodb.github.io/mongo-php-driver/ods/

**Comment by jonnywang** [comment]
thanks
