### ISSUE TITLE
None of the MongoDB\Driver\BSON types implement the JsonSerializable interface

### ISSUE THREAD

**Issue by jacqueswaller** [mongodb/mongo-php-driver#204]
It may sound odd that this is an issue, but because these types all use private members with public accessors they end up printing nothing when you json_encode them.

Consider the following example data:
```
$testTable = ["_id" => new MongoDB\BSON\ObjectID(), "date" => new MongoDB\BSON\UTCDateTime(time())];
```

attempting to print it like
```
print(json_encode($testTable));
```
will give the following result:
```
{"_id":{},"date":{}}
```

I can work around this for now by using a pretty silly pattern
```
print(MongoDB\BSON\toJSON(MongoDB\BSON\fromPHP($testTable)));
```
which gives the expected
```
{ "_id" : { "$oid" : "569d0d892bdc4839a80017da" }, "date" : { "$date" : 1453133887 } }
```
but would rather not convert data repeatedly (consider that it's already in BSON in mongo itself, gets converted to PHP and then when I'm done manipulating, I convert back to BSON just to be able to convert to JSON...)

Public variables will fix this issue too, if implementing JsonSerializable is undesired.

edit: Because `MongoDB\BSON\toJSON` does not have any options, the workaround does not handle any case where the user needs to make use of the json_encode options like `JSON_HEX_QUOT, JSON_HEX_TAG, JSON_HEX_AMP, JSON_HEX_APOS, JSON_NUMERIC_CHECK, JSON_PRETTY_PRINT, JSON_UNESCAPED_SLASHES, JSON_FORCE_OBJECT, JSON_PRESERVE_ZERO_FRACTION, JSON_UNESCAPED_UNICODE, JSON_PARTIAL_OUTPUT_ON_ERROR`

**Comment by jacqueswaller** [comment]
Ok, not sure why I didn't think of this sooner but doing something like
```
$testTable = MongoDB\BSON\toPHP(MongoDB\BSON\fromPHP($testTable));
print(json_encode($testTable));
```

will expose the timestamp as you'd expect, though I dislike having to convert back and forth.

**Comment by bjori** [comment]
See also: https://jira.mongodb.org/browse/PHPC-459

**Comment by jacqueswaller** [comment]
Ah, I had searched for a JIRA but didn't find any. Thank you!
