### ISSUE TITLE
How to print raw query string?

### ISSUE THREAD

**Issue by veego** [mongodb/mongo-php-driver#205]
Is there a way to view the queries that have been sent to the database?

**Comment by bjori** [comment]
See also: https://jira.mongodb.org/browse/PHPC-453

**Comment by jmikola** [comment]
Closing this out as we have a ticket to track the feature request. Please follow that for updates.

Alternatively, you can look into using [query profiling](https://docs.mongodb.org/manual/tutorial/manage-the-database-profiler/) and including [`$comment` modifier](https://docs.mongodb.org/manual/reference/operator/query/comment/) in your queries. A future version of the driver will also include an interface for application performance monitoring (APM), which you'll be able to hook an event listener into to track commands and queries ([PHPC-351](https://jira.mongodb.org/browse/PHPC-351)).
