### ISSUE TITLE
UTCDateTime::__construct with string parameter not working

### ISSUE THREAD

**Issue by guillaumesmo** [mongodb/mongo-php-driver#208]
Using PHP 7.0.2 x86 thread-safe, with PHP_INT_SIZE=4, taken from https://bitnami.com/stack/wamp/installer

With MongoDB extension 1.1.2 TS x86, taken from https://pecl.php.net/package/mongodb/1.1.2/windows

When I try the following: new MongoDB\BSON\UTCDateTime('1453652236000')

I get the following error: MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be integer, string given

**Comment by jmikola** [comment]
@guillaumesmo: I believe this is resolved by @derickr's fix for [PHPC-543](https://jira.mongodb.org/browse/PHPC-543), which should be included in the upcoming 1.1.3 release. If you don't mind following up once that is available to test, I'll leave this open until we can confirm that.

**Comment by jmikola** [comment]
FYI: [1.1.3](https://github.com/mongodb/mongo-php-driver/releases/tag/1.1.3) has been released with the appropriate fix.

**Comment by guillaumesmo** [comment]
Fixed :)

Thank you @derickr and @jmikola
