### ISSUE TITLE
is there any precompiled binary mongo.so for mac to download ?

### ISSUE THREAD

**Issue by jjcang** [mongodb/mongo-php-driver#210]
thanks in advance, i used "pecl install mongo" to get a mongo.so, but it couldn't work, said the version didn't match that of php,

**Comment by bjori** [comment]
Have you tried using homebrew as suggested by the manual?
See: http://php.net/manual/en/mongodb.installation.homebrew.php

Also, the extension is called "mongodb", not "mongo".

**Comment by jmikola** [comment]
Closing this, as we've no plans to create OSX builds; Homebrew and `pecl install` are the suggested install mechanisms, unless there is a PHP environment out there that bundles their own builds (e.g. MAMP).

Pre-compiled binaries are only done for Windows, which is handled by [pecl.php.net](http://pecl.php.net).
