### ISSUE TITLE
Segfault on 1.1.2/1.1.3-dev with PHP 7 FPM under gentoo

### ISSUE THREAD

**Issue by nemessiss81** [mongodb/mongo-php-driver#212]
I am heaving a strange problem under gentoo. Mongodb extension is working fine in apache2 and cli, but fpm fails to start:

```
 /etc/init.d/php-fpm restart
 * Testing PHP FastCGI Process Manager configuration ...
[30-Jan-2016 13:59:47] NOTICE: configuration file /etc/php/fpm-php7.0/php-fpm.conf test is successful

zend_mm_heap corrupted                                                                                                                                                                                            [ !! ]
```

Here is the info from cli:

```
php -i|grep mongo
mongodb
mongodb support => enabled
mongodb version => 1.1.3-dev
mongodb stability => devel
libmongoc version => 1.3.1-dev
mongodb.debug => no value => no value
```

I even compiled mongodb without sasl but the result is the same.
Mongodb extension was manually compiled like this(my system is x86_64):

```
git clone https://github.com/mongodb/mongo-php-driver.git
cd mongo-php-driver; git submodule sync && git submodule update --init
```

Run phpize:

```
phpize --clean
phpize
```

Remove the aclocal.m4 file:

```
rm aclocal.m4
```

Run aclocal and autoconf:

```
aclocal
autoconf
```

Now configure, make and install the package:

```
./configure --without-mongodb_sasl??
make
make install
```

add extension=mongodb.so in php.ini: /etc/php/fpm-php7.0/php.ini
restart php-fpm: /etc/init.d/php-fpm restart

The strangest thing is that if i start php-fpm process with gdb to backtrace the extensions works.

```
gdb -q /usr/lib/php7.0/bin/php-fpm
Reading symbols from /usr/lib/php7.0/bin/php-fpm...(no debugging symbols found)...done.
(gdb) set args --pid /run/php-fpm.pid --fpm-config /etc/php/fpm-php7.0/php-fpm.conf -c /etc/php/fpm-php7.0/
(gdb) run
Starting program: /usr/lib64/php7.0/bin/php-fpm --pid /run/php-fpm.pid --fpm-config /etc/php/fpm-php7.0/php-fpm.conf -c /etc/php/fpm-php7.0/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[Inferior 1 (process 4075) exited normally]
(gdb)
```

Any help is apreciated
Thank you!

**Comment by jmikola** [comment]
`./configure --without-mongodb_sasl??` looks a bit odd. Are you sure you didn't meant to use `./configure --with-mongodb-sasl=no`?

Offhand, I found [this StackOverflow question](http://stackoverflow.com/questions/2247977/what-does-zend-mm-heap-corrupted-mean) discussing `zend_mm_heap corrupted` errors, although the suggested solutions vary quite a bit.

Is there a reason you were manually running `aclocal` and `autoconf`? I typically build with `phpize; ./configure; make all`, which I believe `pecl install` also follows.

**Comment by nemessiss81** [comment]
Thank you for your reply.
?? was put there because i was not sure if it is really needed (the install option was --with-mongodb-sasl=no)
If i do not run aclocal and autoconf and i want to manually build then i receive an error. It works installing using PECL but if i use the extension obtained i receive the same error.
I already tried most of the solutions there but please undestand that the same modules work in php cli and in apache-php.

**Comment by nemessiss81** [comment]
One more thing that i think worths mentioning: my problem is under php 7 and ONLY with php fpm.

**Comment by ssi10** [comment]
I have a problem too. It's only happened under php 7 with fpm
when I try "php-fpm -t"

output is:

> [root@xxx php.d]# php-fpm -t
> [04-Mar-2016 01:38:08] NOTICE: configuration file /etc/php-fpm.conf test is successful
> 
> zend_mm_heap corrupted

or

> [root@xxx php.d]# php-fpm -t
> [04-Mar-2016 01:38:08] NOTICE: configuration file /etc/php-fpm.conf test is successful
> 
> segmentation fault

I already tried all of the stackoverflow (above linked) solutions.
And tried ( pecl install ), ( yum install from remi-php70 ), ( compile: make, make install ).

but..  All same.

**Comment by jmikola** [comment]
Cross-referencing with [PHPC-556](https://jira.mongodb.org/browse/PHPC-556) for later investigation.

**Comment by jmikola** [comment]
@ssi10 @nemessiss81: can you confirm whether this issue is related to #209 and [PHPC-632](https://jira.mongodb.org/browse/PHPC-632)?

**Comment by jmikola** [comment]
Sorry, I inadvertently closed this via a comment in the referenced PR.

I've since released [1.1.5](https://github.com/mongodb/mongo-php-driver/releases/tag/1.1.5), which I believe may fix this issue if it is indeed a duplicate of #209. I will leave it open for you to confirm.

Note that the patch is only able to resolve the problem when libmongoc is bundled (i.e. statically compiled) with the driver. If libmongoc is loaded as a system library, that will rely on an upstream fix (see: [CDRIVER-1165](https://jira.mongodb.org/browse/CDRIVER-1165)).

**Comment by nemessiss81** [comment]
Just tested it and works fine (pecl install mongodb):
mongodb

mongodb support	enabled
mongodb version	1.1.5
mongodb stability	stable
libmongoc version	1.3.3
libbson version	1.3.3

Thank you!

**Comment by jmikola** [comment]
:+1:

**Comment by ssi10** [comment]
It works fine. ( 1.1.5 )

Thank you!
