### ISSUE TITLE
How does sorting work in the new mongodb PECL extension?

### ISSUE THREAD

**Issue by dugajean** [mongodb/mongo-php-driver#214]
I have just shifted from the old mongo extension to the newest PHP driver (mongodb). I'm also using the PHP library provided for mongodb.

Previously, I could simply do `->sort()` on a cursor instance, but that doesn't seem to be the case anymore since I get this error:

```
Fatal error: Uncaught Error: Call to undefined method MongoDB\Driver\Cursor::sort()
```

What is the alternative to sorting/limiting/skipping now? Help would be appreciated.

**Comment by jonnywang** [comment]
in mongodb no sort method, not mongo

confusion

**Comment by dugajean** [comment]
@jonnywang Yes, I am aware of that. What is the solution to this now?

**Comment by jonnywang** [comment]
<php7,  you can use mongo

**Comment by dugajean** [comment]
Well, I need to use PHP 7. So simply lowering the whole project's PHP version is clearly not an option. There should be something that can be done about this.

**Comment by bjori** [comment]
Sorting is part of the MongoDB Query language, and therefore part of the query object.

Using the raw driver you'd do something like this:
```php
$filter = array();
$options = array(
    "sort" => array("username" => 1),
);

$manager = new MongoDB\Driver\Manager("mongodb://localhost");
$query = new MongoDB\Driver\Query($filter, $options);

$cursor = $manager->executeQuery("mydb.mycollection", $query);

foreach ($cursor as $document) {
    echo $document->username . "\n";
}
```

See: http://php.net/manual/en/mongodb-driver-query.construct.php


Using the library you'd do something like this:
```php
$filter = array();
$options = array(
    "sort" => array("username" => 1),
);

$client = new MongoDB\Client("mongodb://localhost");
$client->mydb->mycollection->find($filter, $options);
```
See (WIP): http://mongodb.github.io/mongo-php-library/classes/collection/#mongodbcollection

**Comment by dugajean** [comment]
Thank you for this @bjori ! Should the `$options` parameter also include the `limit` and `skip` parts?

**Comment by bjori** [comment]
Yep @dugajean .

If you are interested in the internal details: https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst
This is the interface the mongo-php-library is implementing, while the core driver (mongo-php-driver) is very raw interface without the "nice interface".

**Comment by dugajean** [comment]
Thank you very much @bjori ! This solved my issue.
