### ISSUE TITLE
(php7) php: symbol lookup error: /usr/lib/php/20151012/mongodb.so: undefined symbol: _mongoc_host_list_destroy_all

### ISSUE THREAD

**Issue by jonathanpmartins** [mongodb/mongo-php-driver#219]
I dont know if this is the right place to put it but I have a problem. In my case Im using Lumen 5.2, PHP 7.0.2 - MongoDB 1.1.2 - Ubuntu 14.04... etc.

On my composer.json file
        
    "illuminate/redis":"5.2.*",
    "predis/predis": "^1.1@dev"

When i run my unit tests it results in this error:

```
.2016/02/03 15:35:03.0458: [ 1359]:    DEBUG:       client: Using custom stream initiator.
php: symbol lookup error: /usr/lib/php/20151012/mongodb.so: undefined symbol: _mongoc_host_list_destroy_all
```

The only reference on google whas this file: https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-uri.c

When I install everything in the server I use the ```ondrej/php```repository. You can look-up the setup installation script here: https://github.com/jonathanpmartins/ubuntusetup/blob/master/server/setup-php7-nginx-1.9.10-ubuntu-14.04.sh

Perhaps I should open a issue on another repository. Can someone help me out?

**Comment by jonathanpmartins** [comment]
after installing the last version of libmongoc the problem is gone!
http://api.mongodb.org/c/1.3.2/installing.html

**Comment by derickr** [comment]
Just curious on this side... did you compile this against a system provided libmongoc? If so, where did that come from? And which version did you have before? We'd probably like to fix this (ie, make sure you get a warning/error while compiling).

**Comment by jonathanpmartins** [comment]
@derickr

Before, when I type in:

$ php -i | grep mongo

    mongodb
    mongodb support => enabled
    mongodb version => 1.1.2
    mongodb stability => stable
    libmongoc version => 1.3.0
    mongodb.debug => no value => no value

Note that at this point in time I have only install mongo with apt-get, like so ```sudo apt-get install php-mongo``` like you can see in the machine setup here: https://github.com/jonathanpmartins/ubuntusetup/blob/master/server/setup-php7-nginx-1.9.10-ubuntu-14.04.sh

And after compiling libmongoc from scratch: 

    mongodb
    mongodb support => enabled
    mongodb version => 1.1.2
    mongodb stability => stable
    libmongoc version => 1.3.1-dev
    mongodb.debug => no value => no value

Note that I use the 1.3.2 file: https://github.com/mongodb/mongo-c-driver/releases/download/1.3.2/mongo-c-driver-1.3.2.tar.gz. But the installed lib was 1.3.1-dev. Strange, but now its working fine.

After compile and install libmongoc again I need to type again:
$ pecl install mongodb
I think this was necessary to glue everything together!

After restart php everything works fine!

**Comment by jonathanpmartins** [comment]
@derickr Sorry,
The old one came from ```ondrej/php```PPA repository.

**Comment by jonathanpmartins** [comment]
If you have more questions, feel free to ask. I feel very glad to help you guys...

**Comment by jonathanpmartins** [comment]
@derickr I think this issue can be closed. https://github.com/mongodb/mongo-php-library/issues/115#issuecomment-180256436

**Comment by jmikola** [comment]
@jonathanpmartins: If I read this correctly, the problem was originally with using the `php-mongodb` package from the `ondrej/php` apt repository. If you ultimately used `pecl install mongodb` to reinstall the extension, that would have used our bundled libmongoc and libbson libraries, where the private symbols line up. If you're comfortable with using the bundled libs with PECL, I'd suggest sticking with that.

This all seems due to our reliance on the private API in libmongoc, which we're actively working to fix (both in our PHP/HHVM drivers and libmongoc itself, where we need to create more public APIs -- no earlier than 1.4.0).

**Comment by jonathanpmartins** [comment]
@jmikola You are correct!

**Comment by oerdnj** [comment]
JFTR you cannot mix and match libraries from PPA and package from PECL. The PPA version php-mongodb matches the libraries in the repository, and it has it's own copy of private symbols, so the symbol lookup should not happen. However errors might happen, so there might be some error.
