### ISSUE TITLE
Missing timeout on read operations - command / query

### ISSUE THREAD

**Issue by marcinrosinski** [mongodb/mongo-php-driver#235]
Hi there,

I can see timeout option for [`WriteConcern`](http://php.net/manual/en/mongodb-driver-writeconcern.construct.php) but can't see anything inside the documentation regarding timeout on read operations - checked [`ReadPreferences`](http://php.net/manual/en/mongodb-driver-readpreference.construct.php) and [`ReadConcern`](http://php.net/manual/en/mongodb-driver-readconcern.construct.php). 

Can you please let me know if its there and I am missing something or it has not been implemented or documented yet?

**Comment by jacqueswaller** [comment]
The WriteConcern timeout may not be exactly what you're thinking; it's the time to wait for writes to propagate to the replicas (if your write concern is set to "ensure my write made it to the replicas" mode).

The connection timeout is specified in the URI options
https://docs.mongodb.org/manual/reference/connection-string/#connections-connection-options 

As for the cursor timeout... I actually have no idea how to set it or disable it with the new php driver. Old driver was http://php.net/manual/en/mongocursor.timeout.php  but that's not too useful...


ok after digging I found this: https://jira.mongodb.org/browse/PHPC-576

looks like you can't set it per operation anymore but you can control it for the entire manager via the URI option `socketTimeoutMS`

**Comment by derickr** [comment]
We have discussed this, and came to the conclusion that using socketTimeoutMS is most likely not what you want to do. When this timeout happens, the connection needs to be killed and recreated, and cursors on the server might linger for a long time.

The correct way is to use "maxTimeMS" as options to commands and queries, and we're looking at where we can add this in a non-kludgy way right now.

**Comment by jmikola** [comment]
There are no plans to add per-operation timeouts on the underlying [libmongoc](https://github.com/mongodb/mongo-c-driver) library, so we cannot implement this. [PHPC-576](https://jira.mongodb.org/browse/PHPC-576) will need to be resolved as "Won't fix".

The [library](https://github.com/mongodb/mongo-php-library/) does support `maxTimeMS` options on the various read operations where it makes sense (the server does not support it for write ops). Those are documented in the various Operation class doc blocks, which we'll ultimately add to the [written documentation](mongodb.github.io/mongo-php-library). If using the driver directly, you will need to include `maxTimeMS` when constructing your Command or Query to use with `executeCommand()` or `executeQuery()`, respectively. I've created [PHPC-585](https://jira.mongodb.org/browse/PHPC-585) to track getting some examples added to the PHP.net docs.

Specifying `maxTimeMS` is different for commands and queries (see: [server docs](https://docs.mongodb.org/manual/tutorial/terminate-running-operations/#maxtimems)). For queries, `maxTimeMS` is set through the `$maxTimeMS` modifier, which would be set through the Query object's `modifiers` option:

```
$query = new MongoDB\Driver\Query(
    ['foo' => 'bar'],
    ['modifiers' => ['$maxTimeMS' => 1000]]
);

$cursor = $manager->executeQuery($query);
```

For commands, you generally include a `maxTimeMS` field at the top-level of your command document.
