### ISSUE TITLE
How do I do regex operations in find?

### ISSUE THREAD

**Issue by clintcan** [mongodb/mongo-php-driver#236]
Hi guys,
The documentation of the new driver is very hard to find, in the old driver one can do:
$filter = new MongoRegex("/^a/"); 
$where = array('ro' => $regex);
$cursor = $collection->find($where);

Where can I do the same thing in the new driver?  It's quite confusing.

**Comment by ZorgUK** [comment]
$filter = new MongoDB\BSON\Regex($pattern, $flags);

Is what you appear to be searching for.

**Comment by clintcan** [comment]
Thank you ZongUK, that's exactly what I was looking for.

**Comment by ZorgUK** [comment]
The only thing that caught me out is you don't need to enclose it in /'s, so "/^a/" becomes just "^a".

**Comment by derickr** [comment]
I've added links in the documentation of the old driver that point to the classes and methods in the new driver for the database's data types: https://jira.mongodb.org/browse/PHPC-583

These will show up in the official documentation at http://php.net/mongo in about a week's time. As you have found that the new class is MongoDB\BSON\Regex, I'm closing this issue.
