### ISSUE TITLE
Cannot query on ObjectID

### ISSUE THREAD

**Issue by fmestrone** [mongodb/mongo-php-driver#238]
I am trying to retrieve documents based on ObjectID, which I have successfully done in the shell with this query

`db.getCollection('KanjiCourses').find({"_id": ObjectId("56cc398bd48e94c24b794651"), lessons: { $exists: true, $ne: [] }}, {_id: 0, lessons: 1})
`
But when I try and render this in PHP I get no results back. This is what I am doing

`$result = $collection->find(['_id' => new MongoDB\BSON\ObjectID("56cc398bd48e94c24b794651"), 'lessons' => [ '$exists' => true, '$ne' => [] ]], ['projection' => ['lessons' => true]]);`

Am I using it incorrectly or is there a known problem with this approach?

Thanks

**Comment by derickr** [comment]
It is possible that you are mixing the API of the old legacy driver and the new driver. The find() method on the MongoCollection class is the old driver, while using MongoDB\BSON\ObjectID and the ['projection'] option to the query is the **new** driver.

As you didn't share more code, I can't see whether you call the find() method on a class from the PHP Library instead (http://mongodb.github.io/mongo-php-library/classes/collection/#finding-one-or-more-documents)—if that's the case, then please share more code, as your example should work.

If indeed you're mixing the old and the new API, then that does not work.
Instead, you should do something like:

```
<?php
$m = new \MongoDB\Driver\Manager();
$ns = 'yourDaseName.KanjiCourses';

$query = new \MongoDB\Driver\Query(
    [
        '_id' => new \MongoDB\BSON\ObjectID("56cc398bd48e94c24b794651"),
        'lessons' => [ '$exists' => true, '$ne' => [] ]
    ], 
    [ 'projection' => [ 'lessons' => true ] ]
);

$result = $m->executeQuery( $ns, $query );
foreach ( $result as $record )
{
    var_dump( $record );
}
```

**Comment by fmestrone** [comment]
Thanks for your reply, I am using it like so - I understand that I am using a PHP Library wrapper around the new driver?

```
$client = new MongoDB\Client;
$collection = $client->kanjisensei->KanjiCourses;
$result = $collection->find(['_id' => new MongoDB\BSON\ObjectID("56cc398bd48e94c24b794651"), 'lessons' => [ '$exists' => true, '$ne' => [] ]], ['projection' => ['lessons' => true]]);
```

Is that wrong? What's the PHP Library that goes with the new driver used for otherwise? This is the one I mean: http://php.net/manual/en/mongodb.tutorial.library.php

I am quite happy with your code snippet though, so will try it and if it works, I'm done :-)

**Comment by fmestrone** [comment]
Works! Thanks! In fact, the initial version of the code now also works, I must have made some typo somewhere along the lines... although I wasn't able to spot the problem
