### ISSUE TITLE
Unable to safe convert time formats from PHP to UTCDateTime

### ISSUE THREAD

**Issue by jakubboucek** [mongodb/mongo-php-driver#244]
PHP native work with time like an integer timestamp, that mean **seconds** from epoch.
Mongo (and other Javascript based apps) use the same principle, but base unit is **milliseconds**.

In a previous version of Mongo driver [class `MongoDate` work with native PHP format](https://secure.php.net/manual/en/class.mongodate.php) and doing convert to Mongo's milliseconds safe without the user's wishes.

This driver doesn't provide safe way to convert PHP date format to Mongo format, [`UTCDateTime` is expect input as milliseconds](https://secure.php.net/manual/en/class.mongodb-bson-utcdatetime.php) and user must keep it in mind and always do this useless multiplication: http://stackoverflow.com/a/34906712/1641372

And in addition, I can not extend `UTCDateTime` because method `__construct` is marked as `final`. Is no another way how to use clean and directly time in Mongo. 

Expexted way:
```php
public function addItem( $title, \DateTime $date ) {
	$data = [
		'title' => $title,
		'created_date' => new UTCDateTime( $date )
	];
	$this->anyCollection->insertOne( $data );
}
```
But it doesn't works. I must use this stupid way **everywhere I am work with date in Mongo**:
```php
...
		'created_date' => new UTCDateTime( $date->toTimestamp() *1000 )
...
```

I tried to expand `UTCDateTime` and replace `__construct` by my own implementation like a:
```php
class CustomUTCDateTime extends \MongoDB\BSON\UTCDateTime {
	public __construct ( \DateTime $date ) {
		parent::__construct( $date->toTimestamp() *1000 );
	}
}

public function addItem( $title, \DateTime $date ) {
	$data = [
		'title' => $title,
		'created_date' => new CustomUTCDateTime( $date )
	];
	$this->anyCollection->insertOne( $data );
}
``` 
But I can't – `__construct` is `final` :-(

I think: safe converting values between environments is one of the important jobs for drivers.

Can you please to help me find safe way to using time with your driver? Or allow to overrides driver's methods.

**Comment by derickr** [comment]
We can't really remove the final keyword, as the object stores internal information. We can't change how the constructor works either, as that would break backwards compatibility, but we do have https://jira.mongodb.org/browse/PHPC-536 to add support for constructing a UTCDateTime object with a PHP \DateTime class as constructor argument. I'm closing this issue in favour of the JIRA ticket, which you probably want to follow.

**Comment by Sammaye** [comment]
I must admit the UTCDateTime object is really annoying me, it has made coding a up hill struggle now having to constantly put defaults in and convert between seconds and milliseconds.

Every time I want to make a new date I have to do:

    new UTCDateTime(time()*1000)

Now, just to use a date.

Are there any real plans to make it easier to use?

**Comment by Sammaye** [comment]
Well, actually now that I think about it accepting DateTime objects and defaulting would be good enough sop that for 1.2

**Comment by worp1900** [comment]
I am going to zombie this thread so people finding it in the future don't have to go and read the jira ticket:

Using DateTime in the UTCDateTime constructor has been implemented in v1.2.
This is now possible:

    new \MongoDB\BSON\UTCDateTime(new \DateTime());

**Comment by prashant-pokhriyal** [comment]
I'm not able to use DateTime in UTCDateTime constructor. It throws **InvalidArgumentException**
```php
MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be integer, object given
```

My environment
```bash
php : 7.0.30-0ubuntu0.16.04.1
```

Output of `php --ri mongodb`
```
mongodb support => enabled
mongodb version => 1.1.5
mongodb stability => stable
libbson version => 1.3.3
libmongoc version => 1.3.3
```

Output of `pecl info mongodb`
```
Release Type          PECL-style PHP extension (source code)
Name                  mongodb
Channel               pecl.php.net
Summary               MongoDB driver for PHP
Release Date          2018-02-20 19:34:54
Release Version       1.4.1 (stable)
API Version           1.4.1 (stable)
Required Dependencies PHP version 5.5.0-7.99.99
                      PEAR installer version 1.4.8 or newer
package.xml version   2.0
Last Modified         2018-06-01 07:57
Previous Installed    - None -
```

**Comment by jmikola** [comment]
@prashant-pokhriyal Per the [`MongoDB\BSON\UTCDateTime::__construct()` changelog](http://php.net/manual/en/mongodb-bson-utcdatetime.construct.php#refsect1-mongodb-bson-utcdatetime.construct-changelog), support for a `DateTimeInterface` object was introduced in 1.2.0. You appear to be using version 1.1.5 of the extension. I'd suggest upgrading to the latest stable release on [PECL](http://pecl.php.net/package/mongodb).

I will also revise the changelog text to clarify that the constructor only accepted an integer argument prior to 1.2.0.

Lastly, please defer to [creating a new issue](https://github.com/mongodb/mongo-php-driver/issues/new) in the future instead of reporting a problem on an older, closed issue. You can always link to previous issues in your description for added context, but creating a new issue will increase the chance that we see it in a timely manner and minimize the risk of polluting existing threads with possibly unrelated conversation.

**Comment by jmikola** [comment]
> I will also revise the changelog text to clarify that the constructor only accepted an integer argument prior to 1.2.0.

Done: http://svn.php.net/viewvc?view=revision&revision=345084

**Comment by prashant-pokhriyal** [comment]
@jmikola Please excuse me for my late response and thank you so much for quick response and I'll keep your suggestion in mind. I have the following concern:

The output of `pecl info mongodb` gives release version as  **1.4.1 (stable)**

I'm not able to get which one is the mongodb driver version, the one given by `php --ri mongodb` or `pecl info mongodb`. And why are they giving different version?

**Comment by alcaeus** [comment]
`pecl info mongodb` displays package information from PECL. Given package information is up to date, it will show the latest available version, not the installed version.

`php --ri mongodb` however shows `phpinfo` output for a given extension and thus displays the currently installed version. You'll want to trust this to find out which version you're currently using.
