### ISSUE TITLE
Method UTCDateTime::toDateTime doesn't respect current timezone

### ISSUE THREAD

**Issue by jakubboucek** [mongodb/mongo-php-driver#246]
Object `DateTime` has `$timezone` as one of internal variable used for correct convert between date formats. If is not defined in call  `new DateTime()`, is set to current timezone based on `date_default_timezone_set()` function or `php.ini` configuration.

Method `UTCDateTime::toDateTime` is ignoring this convention and always create `DateTime` object with timezone `+0000` and is necessarily to keep in mind and rewrite timezone **on every use this method**:

```php 
$UTCDateTime->toDateTime()->setTimeZone( new \DateTimeZone( date_default_timezone_get() ) );
```

**Comment by derickr** [comment]
Hi!

In theory, this is by design. The database doesn't know about timezones (yet), and you could argue that inventing a timezone to go with something that is stored in the database is a bad idea.

But I see your use case.

We can't change how ``toDateTime`` behaves, as that would mean breaking backwards compatibility. But we could add a ``toLocalDateTime()`` method or something similar to add the default configured timezone to the ``\DateTime`` object that it returns. Would that work?

cheers,
Derick

**Comment by jakubboucek** [comment]
I understand you can't change currently defined interface, the `toLocalDateTime()` is good compromise. Don't forget add this behaviour to documentation - it save lot of hours for all developer using driver to debug.

I still think, this is not by design. As name of class say, timestamp in DB is defined in UTC. DateTime is designed for use with timezones and by design respect current timezone setted for process when is not specified another tz in method argument.

**Comment by jakubboucek** [comment]
One more thing: Why is unable serialize `UTCDateTime`? 

My app loading document from Mongo and save it to User session as info about loggedIn user. Previous generation of `MongoDate` allow to serialize they. But `UTCDateTime` doesn't.

Is any reason for that?

**Comment by derickr** [comment]
We're aware of the serialisation issues. This is tracked in https://jira.mongodb.org/browse/PHPC-460 and https://jira.mongodb.org/browse/HHVM-130, and will make it into the 1.2 version of the driver.

**Comment by jmikola** [comment]
Opened [PHPC-760](https://jira.mongodb.org/browse/PHPC-760) to track the `toLocalDateTime()` feature request. Please watch that issue for any updates.

As for UTCDateTime serialization, that is now supported in the [1.2.0alpha1](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0alpha1) release.
