### ISSUE TITLE
\MongoDB\BSON\ObjectID: Invalid BSON ID provided

### ISSUE THREAD

**Issue by acrozes** [mongodb/mongo-php-driver#253]
With the old diver this example was ok:
```
return new \MongoId('56925B7330616224D0000001');
```
but with the new driver there is an exception 
```
return new \MongoDB\BSON\ObjectID('56925B7330616224D0000001');

  [MongoDB\Driver\Exception\InvalidArgumentException]
  Invalid BSON ID provided
```

The Id was ok with the old driver and it is 24 characters lenght ...

**Comment by jacqueswaller** [comment]
It seems that the string must use lower case letters. `56925b7330616224d0000001` works fine, for example.

**Comment by acrozes** [comment]
Yes it seems ok for me too.
Waiting the fix, the add of strtolower() is necessary ...

**Comment by derickr** [comment]
This looks indeed like a bug. I've created a Jira ticket to track this with our planning: https://jira.mongodb.org/browse/PHPC-620 Please follow that JIRA ticket to track the progress.

**Comment by derickr** [comment]
This was also an issue for the HHVM driver: https://jira.mongodb.org/browse/HHVM-188 — which now has a pull request at https://github.com/mongodb/mongo-hhvm-driver/pull/73
