### ISSUE TITLE
Why didn't have 1.1.5 for php 5.6 nts x86 platform?

### ISSUE THREAD

**Issue by ejzhang** [mongodb/mongo-php-driver#268]
There are 1.1.5 for php 5.6 ts x86/x64 and nts x64, but have not that for php 5.6 nts x86.

**Comment by jmikola** [comment]
According to the PHP.net build report "php_mongodb-1.1.5-5.6-nts-vc11-x86 succeeded", so I'm not sure why it didn't make it to https://pecl.php.net/package/mongodb/1.1.5/windows. It's also not present in the [directory listing](http://windows.php.net/downloads/pecl/releases/mongodb/1.1.5/). Also, [php_mongodb-1.1.5-5.6-ts-vc11-x86.zip](http://windows.php.net/downloads/pecl/releases/mongodb/1.1.5/php_mongodb-1.1.5-5.6-ts-vc11-x86.zip) appears to only be available in the directory listing. It's not listed on the PECL page.

I'll follow up with someone at PHP.net, which manages that build infrastructure. That said, the bug fix in 1.1.5 was only relevant to Linux and OSX users, so you're not missing anything by sticking with 1.1.4 on Windows for the time being.

**Comment by jmikola** [comment]
Files should now be present: https://pecl.php.net/package/mongodb/1.1.5/windows

Thanks for alerting us to the issue.
