### ISSUE TITLE
'Cannot run command count(): exception: $or/$and/$nor entries need to be full objects'

### ISSUE THREAD

**Issue by romegonic** [mongodb/mongo-php-driver#269]
Hi all,
First please apologize if I do not follow all the rules of this forum, I have just created my account, and I am French, so I could miss any details.

I'm using php 5.4.6 on apache 2.X, and I do mongodb requests through php mongo driver, some of them use $in $and $or operators.

I recently met an issue concerning a $and request on a rather consequent collection (> 2 millions entries). This issue did not appear before (when the collection contains less than 2M entries).

Here is the error message, then the code which makes its error occurs.

Fatal error: Uncaught exception 'MongoException' with message 'Cannot run command count(): exception: $or/$and/$nor entries need to be full objects' in C:\www\monitoring\admin\statistiques\generer.php:58 Stack trace: #0 C:\www\monitoring\admin\statistiques\generer.php(58): MongoCursor->count() #1 {main} thrown in C:\www\monitoring\admin\statistiques\generer.php on line 58

Here are the 57th and 58th code lines

57 $resultat = $coll->find(array('$and' => array( $type, array('date' => array( '$gt' => $timestamp_debut, '$lt' => $timestamp_fin )))));
58 $nb_entrees_range = var_dump($resultat->count());

I meet the same issue if I change var_dump($resultat->count()) to $resultat->count()

The message is about count() behaviour, which seems to not be able to handle the data type the request gets.
But this request worked until few days ago, and nothing has been changed recently, and this request still works on smaller collections.

Could you please help me on this problem, because I don't know if I have to use my request to only a part of my collection (if it is a problem of size), or if my request really raises problem.

Thanks in advance for your feedback.

For Information:
variables $type|$timestamp_debut|$timestamp_fin have already been set, before the request

**Comment by derickr** [comment]
Hi,

Your question seems to be about the legacy driver (https://github.com/mongodb/mongo-php-driver-legacy), and not this new driver. This is also a bug tracker, and not a forum. For future questions, please write to the https://groups.google.com/forum/#!forum/mongodb-user Google Group.

I think your query incorrect (I've formatted it for clarity):

```
$resultat = $coll->find( [
    '$and' => [
        $type, 
        [ 'date' => [ '$gt' => $timestamp_debut, '$lt' => $timestamp_fin ] ]
    ]
] );
```

You're saying:

`variables $type|$timestamp_debut|$timestamp_fin have already been set, before the request`

But you don't say what ``$type`` contains. If it is a scalar value (number, string, etc), then that makes your query not work, as it ``$and`` needs an array of objects, something like:

```
$resultat = $coll->find( [
    '$and' => [
        [ 'type' => $type ],
        [ 'date' => [ '$gt' => $timestamp_debut, '$lt' => $timestamp_fin ] ]
    ]
] );
```

As ``$and`` is the default, you can actually just leave that out, and shorten it to:

```
$resultat = $coll->find( [
    'type' => $type,
    'date' => [ '$gt' => $timestamp_debut, '$lt' => $timestamp_fin ]
] );
```

(I've removed the ``$and`` array, and array elements around ``type =>`` and ``date =>``).

hope that helps,
Derick

**Comment by romegonic** [comment]
Hi,

Thanks for your anwer.
I will follow your advice and post another possible issues to the forum you pointed me on.

Concerning the current issue I have noticed your comments/advices :
- $and is not mandatory as it's the default operator => useful to know ! (to make request more readable)
- You seem to prefer only [] instead of (), I need to check if there is a different behaviour with thoses.
- You're right, as $type is a string ('APPSERVER'), that's the reason of the issue.
Thank you to have provided me clear explanations about the error message.
As $and is not mandatory, for this simple request, I will remove it.

Thanks again for your help.
romegonic

**Comment by jmikola** [comment]
> You seem to prefer only [] instead of (), I need to check if there is a different behaviour with thoses.

They are both equivalent notations for denoting PHP arrays since 5.4. See: http://php.net/manual/en/migration54.new-features.php
