### ISSUE TITLE
Error on serialize of object from \MongoDB\BSON\ObjectID

### ISSUE THREAD

**Issue by bupt1987** [mongodb/mongo-php-driver#270]
code
~~~
$a = [
	'_id' => new \MongoDB\BSON\ObjectID('000000000000000000000001'),
	'test' => 1,
	'aa' => [
		'b' => 1,
	]
];

$b = serialize($a);

echo $b;
~~~

error
~~~~
PHP Fatal error:  Uncaught exception 'Exception' with message 'Serialization of 'MongoDB\BSON\ObjectID' is not allowed'
~~~~

I need save mongo data to memcache, but throw error when set cache.
Then I find  that the data include \MongoDB\BSON\ObjectID

**Comment by jmikola** [comment]
Enabling PHP serialization of the BSON classes is being tracked in [PHPC-460](https://jira.mongodb.org/browse/PHPC-460).

**Comment by dondencker** [comment]
@jmikola What is the estimated timeframe of this?

**Comment by jmikola** [comment]
@dondencker: In-progress PR is: https://github.com/mongodb/mongo-php-driver/pull/340

I'll be working on this over the coming week and expect to review it with Derick during the week of July 11. While the functionality is slated for 1.2.0, we will consider an alpha release to get the functionality out there before waiting for other 1.2.0 features.

**Comment by dondencker** [comment]
@jmikola Sounds great. An alpha release would be absolutely terrific!

**Comment by rscafi** [comment]
Please release it as an alpha, we are really needing it 👍

**Comment by jmikola** [comment]
#340 was merged to master last week; however, some Windows build issues are holding up an alpha release. I wouldn't expect an alpha before the week of July 25th.

If you urgently need serialization support I would suggest building from master using [these instructions](http://php.net/manual/en/mongodb.installation.manual.php).

**Comment by dondencker** [comment]
@jmikola I did it as soon as the PR was merged. Actually used your working branch in your private fork until then 😏  Thanks!

**Comment by Roycohen** [comment]
Hi Guys,

When this change will be pushed to a stable version?

**Comment by jmikola** [comment]
Windows build issues should get resolved by https://github.com/mongodb/mongo-php-driver/pull/365, so I think we may be able to get this out in an alpha release once that is merged. Stable 1.2.0 release will come later, but we will not be holding it up for MongoDB 3.4's release (that was previously the idea).

**Comment by jmikola** [comment]
[1.2.0alpha1](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0alpha1) has been released.
