### ISSUE TITLE
\MongoDB\BSON\ObjectID::_construct() $id parameter optional

### ISSUE THREAD

**Issue by csizmazia** [mongodb/mongo-php-driver#282]
This is a minor issue, as it only affects syntax highlighting in IDEs, functionality works as expected.

When creating a new `ObjectID`, the `$id` parameter is optional. However, this is not reflected in the PHP interface, which compiles to

```
/**
         * Class ObjectID
         * @link http://php.net/manual/en/class.mongodb-bson-objectid.php
         */
        class ObjectID implements Type
        {
            /**
             * ObjectID constructor.
             * @link http://php.net/manual/en/mongodb-bson-objectid.construct.php
             * @param string $id
             */
            public function __construct($id)
            {
            }

            /**
             * @link http://php.net/manual/en/mongodb-bson-objectid.tostring.php
             * @return string
             */
            public function __toString()
            {
            }
        }
```

PHPStorm (and i guess other IDEs as well) report a problem on lines like this:
`$id = new ObjectID();`
"Required parameter $id missing"

This happens with the latest version 1.1.5 from PECL.

**Comment by jmikola** [comment]
This may be a problem with PHPStorm's interface file, which we do not maintain.

Using reflection, the constructor does report having a single, optional argument:

```
$ php -r 'echo (new ReflectionClass("MongoDB\BSON\ObjectID"))->getMethod("__construct");'
Method [ <internal:mongodb, ctor> final public method __construct ] {

  - Parameters [1] {
    Parameter #0 [ <optional> $id ]
  }
}
```

**Comment by csizmazia** [comment]
you're right, thanks!
for everybody who's interested - this is the path to the interface file which is obviously not up to date:
`{path_to_phpstorm_install}/plugins/php/lib/php.jar!/com/jetbrains/php/lang/psi/stubs/data/mongodb.php`

**Comment by jmikola** [comment]
It appears there's an upstream PR open with a fix for this: https://github.com/JetBrains/phpstorm-stubs/pull/86
