### ISSUE TITLE
MongoDB PHP Driver is not working

### ISSUE THREAD

**Issue by jatinseth2007** [mongodb/mongo-php-driver#283]
I am having Mac OSX 10+, I am using Xampp im my system. I need to install PHP Mongodb driver to connect it to mongodb for my application but It's not working, I have tried following steps:

    1. Installed Mongodb driver using sudo /Applications/XAMPP/xamppfiles/bin/pecl install mongo
    2. Added extension="mongo.so" to php.ini /Applications/XAMPP/xamppfiles/etc

But after that It's not letting Apache Server to start; if I remove extension="mongo.so" from php.ini then it's able to start again

Method 2:

    1. Installed Mongodb driver using sudo /Applications/XAMPP/xamppfiles/bin/pecl install mongodb
    1. Added extension="mongodb.so" to php.ini /Applications/XAMPP/xamppfiles/etc

But after that It's not letting Apache Server to start; if I remove extension="mongodb.so" from php.ini then it's able to start again

I am able to see the mongo.so and mongodb.so file at location /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20131226

My PHP Version is 5.6.19

Error I am getting in log file of Xampp is given below:

    [Tue Apr 05 15:48:23.002151 2016] [ssl:warn] [pid 59298] AH01906: www.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?) [Tue Apr 05 15:48:23.002443 2016] [ssl:warn] [pid 59298] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name [Tue Apr 05 15:48:23.002603 2016] [suexec:notice] [pid 59298] AH01232: suEXEC mechanism enabled (wrapper: /Applications/XAMPP/xamppfiles/bin/suexec) [Tue Apr 05 15:48:24.002160 2016] [ssl:warn] [pid 59299] AH01906: www.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?) [Tue Apr 05 15:48:24.002291 2016] [ssl:warn] [pid 59299] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name [Tue Apr 05 15:48:24.002510 2016] [lbmethod_heartbeat:notice] [pid 59299] AH02282: No slotmem from mod_heartmonitor [Tue Apr 05 15:48:24.002550 2016] [auth_digest:notice] [pid 59299] AH01757: generating secret for digest authentication ...

**Comment by jatinseth2007** [comment]
My PHP Version is 5.6.19

**Comment by jatinseth2007** [comment]
Finally, I got the solution from a Youtube video https://www.youtube.com/watch?v=YStM8_HWxRI

It's very useful and give you step by step explanation for the same.

The problem I was getting because I was updating wrong php.ini file, I was updating /Applications/XAMPP/xamppfiles/etc/php.ini instead of /Applications/XAMPP/etc/php.ini

**Comment by martijnboekema** [comment]
The path '/Applications/XAMPP/etc/' is a shortcut to '/Applications/XAMPP/xamppfiles/etc/'.
So your solution should not be able to work.
The php.ini files you mention are the same file.
I'm having this issue myself..
