### ISSUE TITLE
PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mongodb.so' - /usr/lib64/php/modules/mongodb.so: undefined symbol: zval_used_for_init in Unknown on line 0

### ISSUE THREAD

**Issue by creactivemobile** [mongodb/mongo-php-driver#289]
I'm trying to install mongoDB for PHP and I'm getting this "warning" while loading the php.ini:

> PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mongodb.so' - /usr/lib64/php/modules/mongodb.so: undefined symbol: zval_used_for_init in Unknown on line 0

PHP Version: 7.0.4
mongoDB driver version: 1.1.6

Is there something I can do to make it work?

**Comment by bjori** [comment]
Do you have multiple PHP versions installed?
It looks like the `mongodb.so` was compiled for PHP5, not PHP7

**Comment by creactivemobile** [comment]
yes, our server came with PHP 5.4.16 and Plesk 12.5, but each domain runs on PHP 7.0.4

I installed mongodb using the following command:
`./pecl install mongodb` inside PHP 7.0 bin folder: `/opt/plesk/php/7.0/bin/`

I thought that would be enough to compile for PHP7

**Comment by creactivemobile** [comment]
finally I managed to install the PHP7 build, I had to first install `plesk-php70-devel` and then run then install command from the PHP7 bin folder :happy

**Comment by webdevilopers** [comment]
I got the same error message @creactivemobile . Coming from this issue: https://github.com/mongodb/mongo-php-library/issues/126

`pecl version
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mongodb.so' - /usr/lib/php/20151012/mongodb.so: undefined symbol: zval_used_for_init in Unknown on line 0
PEAR Version: 1.10.1
PHP Version: 7.0.4-7ubuntu2.1

whereis pecl
pecl: /usr/bin/pecl /usr/share/man/man1/pecl.1.gz

whereis pecl7
pecl7:
`

So I guess I used the correct `pecl` to install the package?

Currently I do have the old PHP 5.6 version installed to. Should I even remove it @bjori ?

**Comment by webdevilopers** [comment]
I re-installed mongodb:

```
running: make INSTALL_ROOT="/tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7" install
Installing shared extensions:     /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7/usr/lib/php5/20131226/
running: find "/tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7" | xargs ls -dils
 139278    4 drwxr-xr-x 3 root root    4096 Jun  4 20:53 /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7
1714894    4 drwxr-xr-x 3 root root    4096 Jun  4 20:53 /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7/usr
1714895    4 drwxr-xr-x 3 root root    4096 Jun  4 20:53 /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7/usr/lib
1714896    4 drwxr-xr-x 3 root root    4096 Jun  4 20:53 /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7/usr/lib/php5
1714897    4 drwxr-xr-x 2 root root    4096 Jun  4 20:53 /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7/usr/lib/php5/20131226
1714898 3268 -rwxr-xr-x 1 root root 3344448 Jun  4 20:53 /tmp/pear/temp/pear-build-rootjBJeKS/install-mongodb-1.1.7/usr/lib/php5/20131226/mongodb.so

Build process completed successfully
Installing '/usr/lib/php5/20131226/mongodb.so'
install ok: channel://pecl.php.net/mongodb-1.1.7
configuration option "php_ini" is not set to php.ini location
```

Still looks like PHP5. Is there any way to force `pecl` use php7?

**Comment by webdevilopers** [comment]
Looks like the issues are caused by `phpize` when compiling:
- https://github.com/mongodb/mongo-php-library/issues/170
- https://github.com/mongodb/mongo-php-driver/issues/325

**Comment by webdevilopers** [comment]
In the end I completely purged `php5`:
```
apt-get remove --purge php5-common
```

Then I re-installed `mongodb`:
```
pecl install mongodb
```

This time the `extension_dir` was correct.

Finally!

**Comment by DanielLDorn** [comment]
I had the same issue. It turns out that I had installed mongodb with the incorrect php (OSX version versus Xampp version). To fix this, I had to use `--with-php-config` to point the mongodb driver installation to the right php. Here is my final code for installing the mongodb driver:

```
cd mongodb-1.5.4
phpize
./configure --with-mongodb-sasl=no **--with-php-config=/Applications/XAMPP/xamppfiles/bin/php-config-7.1.11**
```
