### ISSUE TITLE
Connection Reconnect

### ISSUE THREAD

**Issue by ZorgUK** [mongodb/mongo-php-driver#298]
In the event of a MongoDB\Driver\Exception\ConnectionTimeoutException is there a way to tell the MongoDB Driver to drop the socket and reconnect? Or is this an automatic thing that happens in the background if the socket dies?

Ideally I'd like a way to recover from this error if possible.

**Comment by derickr** [comment]
A ConnectionTimeoutException should only be thrown when a connection is *made*. That means, that there would never be a socket that needs to be dropped.

If a connection can't be made, the exception is thrown. The driver will however try to connect again when you do a future operation. As long as it doesn't timeout again, it should work.

In which situation are you getting this? And what exactly are you trying to prevent?

**Comment by ZorgUK** [comment]
That's fine, I just wasn't sure if a dead socket would result in endless timeout exceptions.

If the driver automatically reconnects a dead socket, then everything is good.
