### ISSUE TITLE
Question: Installation with PECL problematic (Ubuntu 14.04)

### ISSUE THREAD

**Issue by sebfek** [mongodb/mongo-php-driver#299]
It's little bit difficult to install this this driver with PECL since on Ubuntu 14.04 not all dependencies are present. Especially C libraries for Openssh.
My Question is where can I found a list of all dependencies for this libraries?
Is it normal that PECL don't handle this dependencies or warn that depdendencies are missing?

I'm not a pro in C depelopment so I don't know exactly how all this dependency management is working.
I see some list in other issues which packages I have to install but is there no a clearer way how to resolve this dependencies.

**Comment by derickr** [comment]
This should work fine on Ubuntu 14.04. Have you installed the ```libssl-dev``` package? PECL doesn't handle OS dependencies unfortunately — although the extension's configure script should tell you that you're missing files .Can you reproduce the full output of what you have executed?

**Comment by sebfek** [comment]
```
vagrant@#####:/##############/$ sudo pecl install mongodb
downloading mongodb-1.1.6.tgz ...
Starting to download mongodb-1.1.6.tgz (653,403 bytes)
..........................................done: 653,403 bytes
350 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /tmp/pear/temp/pear-build-rootI0MFRO/mongodb-1.1.6
running: /tmp/pear/temp/mongodb/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20151012
checking for PHP installed headers prefix... /usr/include/php/20151012
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking PHP version... 70005
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking whether to use system libbson... no
checking configuring libmongoc... ...
checking whether to use system libmongoc... no
checking for pkg-config... no
configure: error: Cannot find OpenSSL's libraries
ERROR: `/tmp/pear/temp/mongodb/configure --with-php-config=/usr/bin/php-config' failed
```
This is my output. So how must I Interpret that?
libssl-dev is installed (but still **configure: error: Cannot find OpenSSL's libraries**)
When I just install the list of packages listed in a previous issue it works but I try to understand how the build tool inform me about this dependencies for other use cases.

**Comment by sebfek** [comment]
Okei I figured out when I install: **pkg-config** it works. It's a little bit difficult for a none experienced C to figure out which build checkings are dependency library related.
I just ask myself if this is normal and why other extensions are working without extra installations?

**Comment by derickr** [comment]
Not all of them use sophisticated techniques ;-) In any case, we should add a check for pkg-config existing to our configure script. You found a bug! :-) I have created a ticket to track that: https://jira.mongodb.org/browse/PHPC-674

**Comment by jmikola** [comment]
@derickr: I'm not certain that this an issue with our build scripts, but rather PHP's own `PHP_SETUP_OPENSSL()` autoconf function. It attempts to use `pkg-config` is available, but falls back to a manual search for the library files:

```
dnl If pkg-config is found try using it
...
dnl If pkg-config fails for some reason, revert to the old method
```

See: https://github.com/php/php-src/blob/aa9f8e695c1babf4be4aa27328f02608fbcf9033/acinclude.m4#L2335

We actually do require `pkg-config` when building with system libbson (see: [here](https://github.com/mongodb/mongo-php-driver/blob/27ee36f2bcf711243075e1486caefbeb4949be7a/config.m4#L331)) and libmongoc (see: [here](https://github.com/mongodb/mongo-php-driver/blob/27ee36f2bcf711243075e1486caefbeb4949be7a/config.m4#L363)) libraries.

**Comment by dondencker** [comment]
I had the same problem, but fixed it temporarily by running:
```
mkdir -p /usr/local/openssl/include/openssl/ && \
	ln -s /usr/include/openssl/evp.h /usr/local/openssl/include/openssl/evp.h && \
	mkdir -p /usr/local/openssl/lib/ && \
	ln -s /usr/lib/x86_64-linux-gnu/libssl.a /usr/local/openssl/lib/libssl.a && \
	ln -s /usr/lib/x86_64-linux-gnu/libssl.so /usr/local/openssl/lib/
```

**Comment by rahulgupta20nov** [comment]
after installing "pkg-config" package. I am getting other error:-
....

OMPILATION -DMONGOC_TRACE -DHAVE_CONFIG_H -g -O0 -D_THREAD_SAFE -pthread -c /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c  -fno-common -DPIC -o src/contrib/.libs/php-ssl.o
In file included from /private/tmp/pear/install/mongodb/src/contrib/php-ssl.c:31:
/private/tmp/pear/install/mongodb/src/contrib/php-ssl.h:33:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make: *** [src/contrib/php-ssl.lo] Error 1
ERROR: `make' failed

**Comment by veerendraudoshi** [comment]
I'm having the same problem as well, although I've installed pkg-config, openssl, libssl-dev, I still get the same error as @rahulgupta20nov .
Here's my output:
`downloading mongodb-1.1.8.tgz ...
Starting to download mongodb-1.1.8.tgz (806,900 bytes)
.................................................................................................................................................................done: 806,900 bytes
360 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /tmp/pear/temp/pear-build-rootLAcEpy/mongodb-1.1.8
running: /tmp/pear/temp/mongodb/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20121212
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable mongodb support... yes, shared
checking OpenSSL dir for mongodb... yes
checking PHP version... 50509
checking whether to enable developer build flags... no
checking whether to enable code coverage... no
checking whether to use system libbson... no
checking configuring libmongoc... ...
checking whether to use system libmongoc... no
checking for pkg-config... /usr/bin/pkg-config
checking for pcre-dir install prefix... yes, shared
checking for pcre... not found
checking for Cyrus SASL support... auto
checking for SASL... not found
checking if weak symbols are supported... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for shm_open... no
checking for shm_open in -lrt... yes
checking for __sync_add_and_fetch_4... yes
checking for __sync_add_and_fetch_8... yes
checking for strnlen... yes
checking for snprintf... yes
checking for _set_output_format... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for struct timespec... yes
checking for library containing clock_gettime... none required
checking for pthread_join in LIBS= with CFLAGS=-pthread... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... (cached) yes
checking whether PTHREAD_ONCE_INIT needs braces... no
checking for stdint-types....... "(putting them into /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-stdint.h)"
checking for uintptr_t... yes
checking for uint64_t... yes
... seen our uintptr_t in stdint.h (uint64_t too)
creating /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-stdint.h : __TMP_PEAR_TEMP_MONGODB_SRC_LIBBSON_SRC_BSON_BSON_STDINT_H
checking for int_least32_t... yes
checking for int_fast32_t... yes
..adding include stdint.h
... seen good stdint.h inttypes
... seen good uint64_t
... DONE /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-stdint.h
checking whether byte ordering is bigendian... no
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for clock_gettime... yes
checking for strnlen... (cached) yes
checking for snprintf... (cached) yes
configure: Current version (from VERSION_CURRENT file): 1.3.5
configure: creating ./config.status
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-config.h
configure: creating ./config.status
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-config.h
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-version.h
configure: Current version (from VERSION_CURRENT file): 1.3.5
configure: creating ./config.status
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-config.h
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-version.h
config.status: creating /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-config.h
configure: creating ./config.status
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-config.h
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-version.h
config.status: creating /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-config.h
config.status: creating /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-version.h
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) nawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status

mongodb was configured with the following options:

Build configuration:
  CFLAGS                                           : -g -O2
  Extra CFLAGS                                     :  -pthread
  Developers flags (slow)                          :
  Code Coverage flags (extra slow)                 :
  System mongoc                                    : no
  System libbson                                   : no
  LDFLAGS                                          :
  EXTRA_LDFLAGS                                    :
  MONGODB_SHARED_LIBADD                            :  -lssl -lcrypto -lrt

Please submit bugreports at:
  https://jira.mongodb.org/browse/PHPC


config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-config.h
config.status: creating /tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/mongoc-version.h
config.status: creating /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-config.h
config.status: creating /tmp/pear/temp/mongodb/src/libbson/src/bson/bson-version.h
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/temp/pear-build-rootLAcEpy/mongodb-1.1.8/libtool --mode=compile cc    -I. -I/tmp/pear/temp/mongodb -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootLAcEpy/mongodb-1.1.8/include -I/tmp/pear/temp/pear-build-rootLAcEpy/mongodb-1.1.8/main -I/tmp/pear/temp/mongodb -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/tmp/pear/temp/mongodb/src/BSON/ -I/tmp/pear/temp/mongodb/src/MongoDB/ -I/tmp/pear/temp/mongodb/src/MongoDB/Exception/ -I/tmp/pear/temp/mongodb/src/contrib/ -I/tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/ -I/tmp/pear/temp/mongodb/src/libbson/src/ -I/tmp/pear/temp/mongodb/src/libbson/src/yajl/ -I/tmp/pear/temp/mongodb/src/libbson/src/bson/  -DBSON_COMPILATION -DMONGOC_COMPILATION -DMONGOC_TRACE -DHAVE_CONFIG_H  -g -O2 -pthread  -c /tmp/pear/temp/mongodb/src/bson.c -o src/bson.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/mongodb -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootLAcEpy/mongodb-1.1.8/include -I/tmp/pear/temp/pear-build-rootLAcEpy/mongodb-1.1.8/main -I/tmp/pear/temp/mongodb -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/tmp/pear/temp/mongodb/src/BSON/ -I/tmp/pear/temp/mongodb/src/MongoDB/ -I/tmp/pear/temp/mongodb/src/MongoDB/Exception/ -I/tmp/pear/temp/mongodb/src/contrib/ -I/tmp/pear/temp/mongodb/src/libmongoc/src/mongoc/ -I/tmp/pear/temp/mongodb/src/libbson/src/ -I/tmp/pear/temp/mongodb/src/libbson/src/yajl/ -I/tmp/pear/temp/mongodb/src/libbson/src/bson/ -DBSON_COMPILATION -DMONGOC_COMPILATION -DMONGOC_TRACE -DHAVE_CONFIG_H -g -O2 -pthread -c /tmp/pear/temp/mongodb/src/bson.c  -fPIC -DPIC -o src/.libs/bson.o
In file included from /usr/include/php5/ext/spl/spl_iterators.h:27:0,
                 from /usr/include/php5/ext/spl/spl_array.h:26,
                 from /tmp/pear/temp/mongodb/src/bson.c:30:
/usr/include/php5/ext/pcre/php_pcre.h:29:18: fatal error: pcre.h: No such file or directory
 #include "pcre.h"
                  ^
compilation terminated.
make: *** [src/bson.lo] Error 1
ERROR: `make' failed
`
Any help will be aprreciated, thank U!!!

**Comment by jmikola** [comment]
> I'm having the same problem as well, although I've installed pkg-config, openssl, libssl-dev, I still get the same error as @rahulgupta20nov 

@veerendraudoshi: The error you've pasted is not the same as the OP, as you were missing PCRE headers. Am I correct in assuming that you since solved your problem based on your comment in https://github.com/mongodb/mongo-php-library/issues/194#issuecomment-236813127?

**Comment by veerendraudoshi** [comment]
@jmikola Yes I did solve my problem by executing the 
sudo apt-get install -y autoconf g++ make openssl libssl-dev libcurl4-openssl-dev pkg-config libsasl2-dev libpcre3-dev 
command... Although I am not aware of PCRE headers, can you please explain what they are???

**Comment by derickr** [comment]
If you install a library with apt-get (such as libssl), you only install the compiled source code ("the binary"). Other code, that makes use of a library can not use the compiled code directly, as it can not figure out how internal structures are laid out. For that, you need to install the "headers". The "headers" contain hints to the compiler on how code can interact with other (already installed) libraries. apt-get usually uses the name "libraryname-dev" for that.

In your case, you likely had libpcre3 installed, but not libpcre3-dev. PCRE itself is a library to work with regular expressions: https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions

**Comment by jmikola** [comment]
The suggestion to install `pkg-config` is documented in the [installation docs for PECL](http://php.net/manual/en/mongodb.installation.pecl.php), so I don't think there's anything to address here.
