### ISSUE TITLE
Class MongoClient not found

### ISSUE THREAD

**Issue by gotardo** [mongodb/mongo-php-driver#300]
Hi,
I have been trying to work around this and I have not managed to find a solution. I have an installation of php7, mongodb and mongo db extension, but when I try to run a script (a Symfony console command like `php bin/console my:command` I always get to the error 'Class MongoClient not found'. I have tried with many different settings and I can not get to a solution.

Here you are some data:

`var_dump( extension_loaded('mongodb') );` shows `bool(true)`

`php -i | grep mongo` shows:
```
mongodb
mongodb support => enabled
mongodb version => 1.1.6
mongodb stability => stable
libmongoc version => 1.3.5
mongodb.debug => no value => no value

```

`php -v` returns:
```
PHP 7.0.4-7ubuntu2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Thanks a lot in advance for your help.

**Comment by derickr** [comment]
MongoClient is a class from the old legacy driver and is not supposed to be available in this one. The new driver has \MongoDB\Driver\Manager, and, the accompanying library has \MongoDB\Client.

You either need to install the old legacy extension (pecl install mongo) and use PHP 5.x, or update your code to use this new driver's classes as the old driver is not available for PHP 7. There is an upgrade guide at http://mongodb.github.io/mongo-php-library/upgrade-guide/

**Comment by gotardo** [comment]
Hi,
Thanks a lot for your quick answer. I was totally lost with the new API. Now everything is working fine :-)
