### ISSUE TITLE
Can't mix unix socket & tcp for connection

### ISSUE THREAD

**Issue by Ange7** [mongodb/mongo-php-driver#301]
i can read in PHP doc this example : (http://php.net/manual/fr/mongoclient.construct.php : example #2)

`<?php

// try unix socket else use localhost 
$m = new MongoClient("mongodb:///tmp/mongodb-27017.sock,localhost:27017");

?>`

But with the same code i have this error : 

> PHP Fatal error:  Uncaught exception 'MongoConnectionException' with message 'Failed to connect to: /tmp/mongodb-27017.sock,localhost:27017:0: No such file or directory' in /usr/share/nginx/html/public/_bootStrap.php:111

If i try only with mongodb://localhost:27017 it's work
if i try only with mongodb:///tmp/mongodb-27017.sock it's work

**Comment by derickr** [comment]
This issue tracker is for the new driver, whereas you are reporting an issue in the old legacy driver. Bugs for the old driver are tracked at http://jira.mongodb.org/browse/PHP exclusively.

In any case, this is not a bug. The hosts that you give to the connection string need to match the exact same host names as you configured in your replicaset. As each host need to be accessible by all other hosts, Unix domain sockets are not supported there.
