### ISSUE TITLE
Logging support

### ISSUE THREAD

**Issue by phofmann-trust** [mongodb/mongo-php-driver#304]
The legacy driver supported setting logging callbacks via  [stream context options](http://php.net/manual/en/context.mongodb.php). Is this also possible with the new driver?

I used this to grab some information about queries/commands issued and time taken.

**Comment by derickr** [comment]
No, but we are going to implement something to track down timing according to this spec: https://github.com/mongodb/specifications/blob/master/source/command-monitoring/command-monitoring.rst

**Comment by jmikola** [comment]
[PHPC-351](https://jira.mongodb.org/browse/PHPC-351) is the relevant tracking ticket.

**Comment by phofmann-trust** [comment]
Is there a timeline for that?

thumbtyped, please excuse brevity and typos

**Comment by jmikola** [comment]
@phofmann-trust: It's currently scheduled as a team [OKR](https://en.wikipedia.org/wiki/OKR) for next quarter (May through July).

**Comment by pascal-hofmann** [comment]
Seems like PHPC-351 was deleted from Jira. Is there another ticket for this now, or was this feature dropped completely?

**Comment by jmikola** [comment]
I don't recall what happened to the original ticket, but [PHPC-349](https://jira.mongodb.org/browse/PHPC-349) is actively tracking the task. The in-progress PR is https://github.com/mongodb/mongo-php-driver/pull/466.
