### ISSUE TITLE
Give BSON UTCDateTime a default value

### ISSUE THREAD

**Issue by TPXP** [mongodb/mongo-php-driver#305]
Hello!

I've recently upgraded my PHP setup to PHP7 and, as a side consequence, switched to the new MongoDB PHP driver. It works pretty well with the library, but I noticed some things are more difficult to make now. And among them, the BSON `UTCDateTime` object (as a replacement on [MongoDate](https://secure.php.net/manual/en/class.mongodate.php)), is now much harder to use, especially if you compare it to the previous version.

Let's say you want to insert a document with the current time. You will want to type something like : 
```<?php $collection->insert(array('date'=>$date));```
where `$date` is a date object, which represents the current time.

In order to create `$date`, I used to type the following before
```$date = new MongoDate;``` 
It now becomes : 
```$date = new MongoDB\BSON\UTCDateTime(intval(microtime(true)*1000));```

I had to write that because `UTCDateTime`'s constructor requires a timestamp corresponding to the *milliseconds* elapsed since the beginning of the UNIX epoch. To get this, I have to call microtime and get its output as a float, so that I have the number of seconds with a correct precision, then I multiply it by 1000 to get the output as milliseconds. Finally, I parse it as an integer with `intval` to get the number I wanted.

It seems to me that this is a a kind of regression since the previous version because, as you can see with the code using the legacy driver, it was much easier to do before.

Maybe we should give a default value, so that `UTCDateTime` defaults to the current time if no timestamp is given ? The ability to parse directly php `DateTime`'s objects (which currently results in another subdocument if recorded through `insert()`, not a MongoDB native Date object, that makes it harder to sort) might also be interesting!

Thank you for your help.

Thomas P.

**Comment by derickr** [comment]
Hello! :-)

We are aware of this, and tracking the default value and DateTime argument type additions at https://jira.mongodb.org/browse/PHPC-536 It's currently slated to make it into the new 1.2 release.

Please follow that ticket to see further updates. I'm closing this ticket out as duplicate.

cheers,
Derick
