### ISSUE TITLE
How can I perform MongoDB query asynchronously in PHP?

### ISSUE THREAD

**Issue by sm2017** [mongodb/mongo-php-driver#334]
How can I perform MongoDB query asynchronously in PHP?

For MySQL we can use

``` php
 <?php
    mysqli_query ( $link , $query,MYSQLI_ASYNC);
    mysqli::poll ( $read , $error , $reject , $sec,$usec );
    mysqli_reap_async_query ( $link );
```

How would somebody perform the above task in MongoDB?

**Comment by derickr** [comment]
The driver does not implement asynchronous requests. We are tracking this as a feature request through https://jira.mongodb.org/browse/PHPC-160

**Comment by cordovapolymer** [comment]
@derickr any updates on this?

**Comment by jmikola** [comment]
There are no immediate plans to work on [PHPC-160](https://jira.mongodb.org/browse/PHPC-160).

**Comment by Makapashev** [comment]
Any updates?

**Comment by jmikola** [comment]
[PHPC-160](https://jira.mongodb.org/browse/PHPC-160) is the canonical ticket for this feature request, so I will post a response there.
