### ISSUE TITLE
A method to count result items returned by Collection->find()

### ISSUE THREAD

**Issue by raeesiqbal** [mongodb/mongo-php-driver#341]
```hack
$Orders = $DB->selectCollection('orders')->find(['UserID' => $User['_id']]);
```

`find` returns `MongoDB\Driver\Cursor` which doesn't have a method to count the result items. But there should be.

**Comment by moderndeveloperllc** [comment]
@raeesiqbal `MongoDB\Driver\Cursor` does not contain all the results in memory when you do the `find`. You will need to pull the info by either doing something like 

``` $orderCount = count($Orders->toArray())```

or run a separate query like

```$count = $db->selectCollection('orders')->count(['userId' => $user['_id']]);```

if all you need is an order count (for a summary page for example).

**Comment by raeesiqbal** [comment]
Yes, I know about that. But I'm suggesting that it should have a method to get count result items rather than converting then array.

**Comment by raeesiqbal** [comment]
@moderndeveloperllc Does the `MongoDB\Driver\Cursor` get data from the database on each iteration of items?

**Comment by moderndeveloperllc** [comment]
@raeesiqbal Take a look at the discussion here: github.com/mongodb/mongo-php-driver/issues/195

**Comment by raeesiqbal** [comment]
I think it understand now, thanks
