### ISSUE TITLE
Forcing close on TCP sockets to mogodb nodes with new API

### ISSUE THREAD

**Issue by lglayal** [mongodb/mongo-php-driver#354]
Hi,
(initially from 
https://github.com/mongodb/mongo-php-library/issues/215)

I'm looking for Mongolient::close() feature available in legacy php driver to force TCP close.
 As mongo-c-driver has mongoc_client_destroy(); an api to cleanly close TCP sessions would be usefull in the following cases : 

Considering a bunch of PHP fastcgi processes, a firewall, and a mongo replicaset.
By using persistent connections to mongo nodes we can improve performance but on low traffic between fastcgi processes and the nodes the FW may timeout TCP sessions, three ways for a FW to drop session :
(1) - drop session table entry without sending end of TCP session to both legs/endpoints
- in this case nor kernel or the fastcgi process has clue on the real state of TCP session, any TCP reuse will generate timeout/exceptions/delayed processing.

(2) - drop session table entry and send end of TCP session to only one leg
- in this case the fastcgi process has no clue on the real state of TCP session, any TCP reuse will generate timeout/exceptions/delayed processing

(3) - drop session table entry and send end of TCP session to both legs
- in this case the kernel knows a socket is closed but the fastcgi process will only see a state change when it tries to reuse socket, so generating an error and needs to recreate a new session.

Dropped sessions in FW can also occur on FW rules reloaded.

With legacy driver, to limit the number of issues we used to check creation time for TCP sockets (tracked using a status file) and we closed it (with reduced timeout configuration) if too old (using MongoClient::close()).

We also close sockets : 
- for application we know only use db for a couple of requests a day.
- to limit number of TCP sessions on platform/firewalls/servers.

Thanks.
BR

**Comment by jmikola** [comment]
> With legacy driver, to limit the number of issues we used to check creation time for TCP sockets (tracked using a status file) and we closed it (with reduced timeout configuration) too old.

In https://github.com/mongodb/mongo-php-library/issues/215, you mentioned that this was done using [MongoClient::close()](http://php.net/manual/en/mongoclient.close.php). There are no plans to reintroduce close methods in the new driver at this time.

libmongoc implements a "serverSelectionTryOnce" mode from the [server selection specification](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#serverselectiontryonce), which should be capable of reconnecting once. It is also possible to disable that mode, which is the default for single-threaded drivers such as PHP, to have libmongoc make several attempts until a configurable timeout is reached. If this implementation does not play nicely with firewalls, that may be worthy of a bug report to libmongoc ([CDRIVER](https://jira.mongodb.org/browse/CDRIVER) in JIRA) for further investigation.

**Comment by jmikola** [comment]
> I will open a bug on JIRA to follow this case.

Before doing so, I would suggest conducting some tests with the `serverSelectionTimeoutMS` and `serverSelectionTryOnce` URI options. If you set `serverSelectionTryOnce` to `false` in the PHP driver, you can then use `serverSelectionTimeoutMS` to specify a timeout period and libmongoc should continue retrying until that timeout is reached. Combining these parameters with dropped sockets (assuming you can manually trigger FW drops or simulate them some other way) should give you a good idea of how the new driver performs in this case.

**Comment by WLWL** [comment]
new mongoDB is a persist ,can't disable connect mongo?

**Comment by jmikola** [comment]
@WLWL's question was addressed in https://github.com/mongodb/mongo-php-driver/issues/397.

Closing this issue as there remains no plans to allow users to close sockets directly.
