### ISSUE TITLE
UTCDateTime conversion to DateTime is ignoring default timezone

### ISSUE THREAD

**Issue by rscafi** [mongodb/mongo-php-driver#370]
When using [`MongoDB\BSON\UTCDateTime::toDateTime` method](http://php.net/manual/en/mongodb-bson-utcdatetime.todatetime.php), the retrieved `DateTime` has a wrong timezone set, ignoring the one from config (set on `ini` file).
I hope that the screenshot below is enough.

![image](https://cloud.githubusercontent.com/assets/6104262/17446384/76cc56ae-5b1f-11e6-971c-597f654a3a47.png)

**Comment by moderndeveloperllc** [comment]
Yep, hence the "UTC" in the class title :-) It only stores the timestamp (in milliseconds). There is a [JIRA ticket open](https://jira.mongodb.org/browse/PHPC-760) to address timezones. Create an account and vote for the issue to make your voice heard!

**Comment by rscafi** [comment]
I guess that makes sense, but it is still kind of a gotcha. Anyway, thanks, i'll vote.

**Comment by jmikola** [comment]
I've updated the [`MongoDB\BSON\UTCDateTime::toDateTime()`](http://php.net/manual/en/mongodb-bson-utcdatetime.todatetime.php) documentation to note that we use the UTC time zone: http://svn.php.net/viewvc?view=revision&revision=339806

**Comment by jmikola** [comment]
Closing this thread. Please follow [PHPC-760](https://jira.mongodb.org/browse/PHPC-760) for further updates.
