### ISSUE TITLE
Connection Pool options: maxIdleTimeMS

### ISSUE THREAD

**Issue by enajeeb** [mongodb/mongo-php-driver#372]
Does the driver supports connection pool options including "maxIdleTimeMS" ?

**Comment by jmikola** [comment]
The PHP driver does not use a connection pool, so the [maxIdleTimeMS](https://docs.mongodb.com/manual/reference/connection-string/#urioption.maxIdleTimeMS) option is ignored. Instead, each worker process will persist sockets to be reused by subsequent requests.

libmongoc, which we use, does support connection pools in a mode multi-threaded applications; however, the PHP driver uses its single-threaded mode. That said, even its multi-threaded mode has not support for a "maxIdleTimeMS" option (see: [CDRIVER-278](https://jira.mongodb.org/browse/CDRIVER-278)).
