### ISSUE TITLE
Got unsupported type 0 'unknown'

### ISSUE THREAD

**Issue by sandipmavani** [mongodb/mongo-php-driver#375]
Got Error While Pass From Recursive Function(Pass By Reference).

here $object Pass From Function 
$bulk->insert($object);
$result = $mng->executeBulkWrite("test.coll", $bulk,$writeConcern);

Got unsupported type 0 'unknown'

**Comment by derickr** [comment]
Can you share a short, but *complete* script that we can run ourselves that exhibits this behaviour? And also share the full exception message (and class) that you get?

**Comment by sandipmavani** [comment]
Hi @derickr 
when I invoke following function on data before inserting to database i got this error.
but without passing from this function it's work fine and successfully inserted.

function recursiveUnsetExplicitType(&$array)
{
	if(is_object($array))
		unset($array->_explicitType);
	if(is_array($array))
		unset($array['_explicitType']);

	if(is_array($array) || is_object($array))
		foreach($array as $key => &$value)
		{
			if(is_array($value) || is_object($value))
			{
				recursiveUnsetExplicitType($value);
			}
		}
}

**Comment by derickr** [comment]
Sorry, but I need a *complete* script. One that I can run, to try and reproduce this.

However, I do think this might be related to opcache - can you try disabling this too?

**Comment by sandipmavani** [comment]
hi @derickr and @jmikola 
There are one case remain for
