### ISSUE TITLE
Do you plan to add method count() to MongoDB\Driver\Cursor

### ISSUE THREAD

**Issue by Labutin** [mongodb/mongo-php-driver#394]
In MongoDB **Cursor** has method count: https://docs.mongodb.com/manual/reference/method/cursor.count/

Do you plan to add method count() to MongoDB\Driver\Cursor ?

**Comment by derickr** [comment]
No, we don't intend to do that in the driver, as it is just a command to run.

We do have this available in the library already: https://mongodb.github.io/mongo-php-library/classes/collection/#count

We recommend that all users use the library in combination with the driver.
