### ISSUE TITLE
UTCDateTime constructor TypeError with integer in 1.2.0alpha

### ISSUE THREAD

**Issue by Algatux** [mongodb/mongo-php-driver#426]
### Description

UtcDateTime throws a type error if initialized with integer

> TypeError: MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be string, integer given
### Environment

Tested it on travis ci 

https://travis-ci.org/facile-it/mongodb-bundle/builds/163101078

**Comment by jmikola** [comment]
This appears to be an issue with `declare(strict_types = 1);` and the code using ["s" with `zend_parse_parameters()`](https://github.com/mongodb/mongo-php-driver/blob/1.2.0alpha3/src/BSON/UTCDateTime.c#L196). I expect [`MongoDB\BSON\Timestamp`](https://github.com/mongodb/mongo-php-driver/blob/1.2.0alpha3/src/BSON/Timestamp.c#L165) has a similar issue.

I've opened [PHPC-804](https://jira.mongodb.org/browse/PHPC-804) to track this issue, so please follow that for updates.

Thanks for testing the alpha release and reporting this!

**Comment by moderndeveloperllc** [comment]
@jmikola You may also want to look into how the test framework interacts with `declare(strict_types = 1);`. There was already a [test created for this scenario](https://github.com/mongodb/mongo-php-driver/blob/master/tests/bson/bson-utcdatetime-003.phpt) which is passing.

**Comment by jmikola** [comment]
@moderndeveloperllc: Indeed, some `strict_types` appear to be what we were lacking. We'll surely create some as part of PHPC-804.

**Comment by nikolaposa** [comment]
I've stumbled upon this issue today while using Monolog's MongoDBHandler. I've created a [issue](https://github.com/Seldaek/monolog/issues/883), and also a [PR](https://github.com/Seldaek/monolog/pull/884) that fixes it. It's a hacky fix though.

**Comment by jmikola** [comment]
[1.2.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0) has been released, which includes the fix for this issue ([PHPC-804](https://jira.mongodb.org/browse/PHPC-804)).
