### ISSUE TITLE
Incorrect behavior of BulkWrite::count()

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-driver#429]
## Environment: 
Ubuntu 16.04 / Linux Mint 18 "Sarah"

mongodb support => enabled
mongodb version => 1.1.8
mongodb stability => stable
libmongoc version => 1.3.5
libbson version => 1.3.5

## Test script:

```php
<?php

$documents = [
	['one'   => 1],
	['two'   => 2],
	['three' => 3],
	['four'  => 4],
	['five'  => 5],
];

$bulk = new \MongoDB\Driver\BulkWrite;

foreach ($documents as $doc) {
	$bulk->insert($doc);
	echo $bulk->count(), PHP_EOL;
}
```

Expected result:
```
1
2
3
4
5
```

Actual result:
```
1
1
1
1
1
```

**Comment by derickr** [comment]
I believe we fixed this in our master/v1.2 release, as I can not reproduce this:

```
derick@whisky:~ $ php --ri mongodb

mongodb

mongodb support => enabled
mongodb version => 1.2.0-dev
mongodb stability => devel
libmongoc version => 1.5.0-rc0
libbson version => 1.5.0-rc0

Directive => Local Value => Master Value
mongodb.debug => no value => no value
[PHP: 7.0.10-dev  ]
derick@whisky:~ $ php issue429.php
1
2
3
4
5
```

Could you see whether 1.2.0alpha3 fixes it for you as well?

**Comment by petr-buchin** [comment]
Unfortunately, for now I have no time to install the development version of the driver on my computer.
I believe that you fixed this bug in master branch, if you cannot reproduce this error.
I think that we can close this issue now. I will update my version of the driver after v1.2 release, and then I'll check this again. If I will be able to reproduce this problem on the version 1.2, I'll reopen this issue.
Thank you very much :)

**Comment by derickr** [comment]
It's this issue btw: https://jira.mongodb.org/browse/PHPC-680?jql=project%20%3D%20PHPC%20AND%20text%20~%20bulkwrite
