### ISSUE TITLE
iterator_to_array($cursor) returns indexed array instead of associative array

### ISSUE THREAD

**Issue by woshicixide** [mongodb/mongo-php-driver#430]
when i use iterator_to_array($cursor), how could i get associative array which '_id' as key,like older one
thank you

**Comment by derickr** [comment]
Thanks for your feedback.

Unfortunately, we can't do that, as the range of values that you can use in the ``_id`` field can not always be represented in an PHP's array key name. (For example, arrays as ``_id`` field).

**Comment by jmikola** [comment]
Note: if you're confident that the `_id` values in your results will be scalars, would be implement this yourself by wrapping the Cursor with a generator. See [this code](https://github.com/alcaeus/mongo-php-adapter/blob/a98cb803b99ce73a61f034b487ad0667e3018ed8/lib/Mongo/MongoCursor.php#L449) in the mongo-php-adapter library for an example of how this can be done.

**Comment by woshicixide** [comment]
will the generator loads all data to the memory when i wrapping the Cursor?
thank you very much!!

**Comment by jmikola** [comment]
@woshicixide: The generator approach does not need to load all data in memory (unlike `iterator_to_array()` and `Cursor::toArray()`).

**Comment by woshicixide** [comment]
@jmikola got it, thank you
