### ISSUE TITLE
install mongo-php-driver to one server and call it to another server to parse mogo code

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb/mongo-php-driver#434]
i setup a server A for mongo db and i want to call it to another server B but it throw me an error. error is "mongo db pecl is not installed or enabled" but in server which i have installed pecl is work fine but i want to call it from server A to B with installing PECL in server B ? if it is possible please help me

**Comment by lindelius** [comment]
You need to install the driver on the server on which you run your PHP scripts. It does not work if you try to run a PHP script on server A if you only installed the driver on server B.

**Comment by jmikola** [comment]
Please follow the [installation instructions](http://php.net/manual/en/mongodb.setup.php) for all PHP application servers on which you plan to use the extension.
