### ISSUE TITLE
Not static compilation

### ISSUE THREAD

**Issue by ilsanbao** [mongodb/mongo-php-driver#441]
./buildconf --force

Forcing buildconf
Removing configure caches
rebuilding configure
/usr/bin/m4:ext/mongodb/config.m4:441: cannot open `src/libmongoc/build/autotools/WeakSymbols.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:442: cannot open `src/libmongoc/build/autotools/m4/ax_pthread.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:476: cannot open `src/libbson/build/autotools/CheckAtomics.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:477: cannot open `src/libbson/build/autotools/FindDependencies.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:478: cannot open `src/libbson/build/autotools/m4/ac_compile_check_sizeof.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:479: cannot open `src/libbson/build/autotools/m4/ac_create_stdint_h.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:523: cannot open `src/libmongoc/build/autotools/Versions.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:537: cannot open `src/libbson/build/autotools/Versions.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
rebuilding main/php_config.h.in
/usr/bin/m4:ext/mongodb/config.m4:441: cannot open `src/libmongoc/build/autotools/WeakSymbols.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:442: cannot open `src/libmongoc/build/autotools/m4/ax_pthread.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:476: cannot open `src/libbson/build/autotools/CheckAtomics.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:477: cannot open `src/libbson/build/autotools/FindDependencies.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:478: cannot open `src/libbson/build/autotools/m4/ac_compile_check_sizeof.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:479: cannot open `src/libbson/build/autotools/m4/ac_create_stdint_h.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:523: cannot open `src/libmongoc/build/autotools/Versions.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:537: cannot open `src/libbson/build/autotools/Versions.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
autoheader: '/usr/bin/autom4te' failed with exit status: 1

**Comment by derickr** [comment]
When you check the driver out from GitHub, you need to clone the git submodules too, as is described at: https://github.com/mongodb/mongo-php-driver/blob/master/CONTRIBUTING.md#contributing-to-the-php-driver-for-mongodb

**Comment by wysow** [comment]
Hello, Is it possible to re-open this issue as it seems that the problem is still here, here are the steps to reproduce:

```
(we are here in the php ext folder from the php source package)

git clone https://github.com/mongodb/mongo-php-driver.git mongodb
cd mongodb
git checkout 1.4.3 && git submodule update --init
cd ..
./buildconf --force
```

Here is the result:

```
Forcing buildconf
Removing configure caches
buildconf: checking installation...
buildconf: autoconf version 2.69 (ok)
rebuilding aclocal.m4
rebuilding configure
/usr/bin/m4:ext/mongodb/config.m4:314: cannot open `scripts/build/autotools/m4/pkg.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:316: cannot open `scripts/build/autotools/CheckHost.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:317: cannot open `scripts/build/autotools/CheckSSL.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:331: cannot open `src/libmongoc/build/autotools/CheckSnappy.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:332: cannot open `src/libmongoc/build/autotools/CheckZlib.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:397: cannot open `src/libmongoc/build/autotools/m4/ax_prototype.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:398: cannot open `src/libmongoc/build/autotools/CheckCompiler.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:402: cannot open `src/libmongoc/build/autotools/FindResSearch.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:404: cannot open `src/libmongoc/build/autotools/WeakSymbols.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:405: cannot open `src/libmongoc/build/autotools/m4/ax_pthread.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:443: cannot open `src/libbson/build/autotools/CheckAtomics.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:444: cannot open `src/libbson/build/autotools/FindDependencies.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:445: cannot open `src/libbson/build/autotools/m4/ac_compile_check_sizeof.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:446: cannot open `src/libbson/build/autotools/m4/ac_create_stdint_h.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:488: cannot open `src/libmongoc/build/autotools/Versions.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:505: cannot open `src/libbson/build/autotools/Versions.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
rebuilding main/php_config.h.in
/usr/bin/m4:ext/mongodb/config.m4:314: cannot open `scripts/build/autotools/m4/pkg.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:316: cannot open `scripts/build/autotools/CheckHost.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:317: cannot open `scripts/build/autotools/CheckSSL.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:331: cannot open `src/libmongoc/build/autotools/CheckSnappy.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:332: cannot open `src/libmongoc/build/autotools/CheckZlib.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:397: cannot open `src/libmongoc/build/autotools/m4/ax_prototype.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:398: cannot open `src/libmongoc/build/autotools/CheckCompiler.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:402: cannot open `src/libmongoc/build/autotools/FindResSearch.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:404: cannot open `src/libmongoc/build/autotools/WeakSymbols.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:405: cannot open `src/libmongoc/build/autotools/m4/ax_pthread.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:443: cannot open `src/libbson/build/autotools/CheckAtomics.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:444: cannot open `src/libbson/build/autotools/FindDependencies.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:445: cannot open `src/libbson/build/autotools/m4/ac_compile_check_sizeof.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:446: cannot open `src/libbson/build/autotools/m4/ac_create_stdint_h.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:488: cannot open `src/libmongoc/build/autotools/Versions.m4': No such file or directory
/usr/bin/m4:ext/mongodb/config.m4:505: cannot open `src/libbson/build/autotools/Versions.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
autoheader: '/usr/bin/autom4te' failed with exit status: 1
```

Someone knows a solution to statically build php mongodb extension?

**Comment by derickr** [comment]
@wysow — We still want to make that work, but we're waiting on some other blocking tickets first. This is tracked at https://jira.mongodb.org/browse/PHPC-1075 and https://jira.mongodb.org/browse/PHPC-759

**Comment by wysow** [comment]
@derickr should I help testing https://github.com/mongodb/mongo-php-driver/pull/749 or maybe another way to help you on this?

**Comment by derickr** [comment]
We're not there yet, as we're waiting on some other things to be done first. Once #749 (or a follow up) gets merged, we'd be delighted if you could test it!

**Comment by jmikola** [comment]
FYI: https://github.com/mongodb/mongo-php-driver/pull/830 is the current PR for supporting static builds of the driver.
