### ISSUE TITLE
Write concern as a document

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-driver#450]
Hi!
Currently method `MongoDB\Driver\Manager::executeBulkWrite()` accepts `MongoDB\Driver\WriteConcern` instance as an argument. Nonetheless, in command options write concern must be provided as a document.
I think specifying write concern in different formats in commands and bulk write is an inconsistency of the driver API. 
So the question is: do you considering fix of this behavior in future releases of the driver?

Thanks in advance!

**Comment by jmikola** [comment]
This has been addressed in the forthcoming 1.2.0 release with [PHPC-498](https://jira.mongodb.org/browse/PHPC-498). The ReadConcern, ReadPreference, and WriteConcern objects now implement [`MongoDB\BSON\Serializable`](http://php.net/manual/en/class.mongodb-bson-serializable.php), which means that they can be used as-is in any documents that will be serialized to BSON. See [`MongoDB\Driver\WriteConcern::bsonSerialize()`](http://php.net/manual/en/mongodb-driver-writeconcern.bsonserialize.php) for an example.
