### ISSUE TITLE
ReTry connections like Java driver does

### ISSUE THREAD

**Issue by necromant2005** [mongodb/mongo-php-driver#451]
### Description

It will be great to add options of 
autoConnectRetry (bool)  / true/false
maxAutoConnectRetryTime (int) max time to finish connections retry (in ms)
autoConnectRetryTime - time between auto-retry to connect (in ms)

### Sample Code
```
<?php
$manager = new MongoDB\Driver\Manager("mongodb://localhost:27017", [
    'autoConnectRetry' => true,
    'maxAutoConnectRetryTime' =>  3000, // 3 sec
    'autoConnectRetryTime' => 1000, // 1 sec
]);
```
The manager tries 3 times (3000/1000) to connect to mongodb cluster.

### Use case
In case of HA (hight availability) when one node fails (or more) and there starts election process, connections fails for some short time. 

### Behavior
1. If autoConnectRetry = false - didn't try to reconnect
2. If maxAutoConnectRetryTime is reached  - raise an exception about connection timeout retry
3. If connections failed during autoConnectRetryTime, retry to connect to some available node until 
maxAutoConnectRetryTime is reached.

connectionTimeout - options works as synonym for maxAutoConnectRetryTime

**Comment by bjori** [comment]
The Java driver options have been deprecated, and even removed in the current major release series.
See:
- https://jira.mongodb.org/browse/JAVA-1076
- https://api.mongodb.com/java/2.12/com/mongodb/MongoClientOptions.Builder.html#autoConnectRetry(boolean)

All drivers now deal with this issue consistently as per the ["SDAM Spec"](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst).

It looks like the relevant options you can tweak aren't documented on http://php.net/manual/en/mongodb-driver-manager.construct.php but there really should not be a need for you to tweak the defaults unless you have highly specialized setup

**Comment by necromant2005** [comment]
Thanks @bjori !
