### ISSUE TITLE
Documentation lost: mongo-php-driver/crud

### ISSUE THREAD

**Issue by Gorbov** [mongodb/mongo-php-driver#452]
There are no more doc:
http://mongodb.github.io/mongo-php-driver/crud/

Where it has been moved?

**Comment by jmikola** [comment]
The GitHub-hosted documentation was intentionally removed in https://github.com/mongodb/mongo-php-driver/pull/447. The material was already covered (with examples) on PHP.net:

 * http://php.net/manual/en/class.mongodb-driver-bulkwrite.php
 * http://php.net/manual/en/class.mongodb-driver-query.php

On a related note, the library's CRUD tutorial is https://docs.mongodb.com/php-library/master/tutorial/crud/.
