### ISSUE TITLE
OpenSSL 1.1.0 support

### ISSUE THREAD

**Issue by oerdnj** [mongodb/mongo-php-driver#453]
Debian is switching to OpenSSL 1.1.0 so it would be appreciated if there could be a patch or release that would support OpenSSL 1.1.0.

On related note - perhaps you can bundle this together with a version that doesn't need libmongoc private symbols and release as 1.2.0?

I need such release before 5. January 2017 (-10 days) to make things easier for me due next stable release freeze: https://lists.debian.org/debian-devel-announce/2016/11/msg00002.html

**Comment by derickr** [comment]
How do we not support OpenSSL 1.1.0 yet? From what I understand, CDRIVER 1.4.0 fixes this. As our 1.2.0 release will use CDRIVER 1.5.0, that should be supported automatically too (https://jira.mongodb.org/browse/CDRIVER-1066).

We need to wait with our 1.2.0 releases (PHP, and HHVM) until the server has released 3.4.0. We expect that to be before January, but no guarantees.

Our latest RCs (https://groups.google.com/forum/#!topic/mongodb-announce/MxJL7b8q3Mo) should work with OpenSSL 1.1.0 - if you can test that as well, that'd be great.

**Comment by jmikola** [comment]
> On related note - perhaps you can bundle this together with a version that doesn't need libmongoc private symbols and release as 1.2.0?

For the record, the upcoming 1.2.0 branch should be free of any private libbson and libmongoc symbol usage. That migration was handled in the 1.2.0alpha1 release (see: [PHPC-542](https://jira.mongodb.org/browse/PHPC-542)).

**Comment by oerdnj** [comment]
JFTR "before January" has to be "Jan 5" - 10 days at a bare minimum for php-mongodb to propagate to stretch and that should probably include updated `libbson` and `libmongoc` packages (and couple of extra days for me would be nice to be able to merge the changes).

No new *source* package can enter Debian stretch after 5. January and packages will need 10-days to migrate to testing.

**Comment by jmikola** [comment]
@oerdnj: [1.2.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.0) has been released. Please let us know if it meets your needs for packaging.

**Comment by jmikola** [comment]
Closing this, as the 1.2.x driver appears to be packaged upstream as [`php-mongodb`](https://packages.debian.org/sid/php-mongodb) and lists `libssl1.1` as a dependency.
