### ISSUE TITLE
Create an example on how to connect to atlas m10 NOT Cluster

### ISSUE THREAD

**Issue by redimongo** [mongodb/mongo-php-driver#459]
Hi, I just can't connect to the right REPLICA SET  I am on the lowest atlas plan, which is ok. but it sucks not being able to get connected. The following I have tried.

static::$_db = new MongoDB\Client("mongodb://USERNAME:PASSWORD@ATLASURL:27017/admin?ssl=true&=authSource=admin");

the error I get is
`Fatal error: Uncaught exception 'MongoDB\Driver\Exception\ConnectionTimeoutException' with message 'No suitable servers found (`serverselectiontryonce` set): [connection error calling ismaster on 'luxemassage-shard-00-00-0kahc.mongodb.net:27017'] [connection error calling ismaster on 'luxemassage-shard-00-01-0kahc.mongodb.net:27017'] [Server closed connection. calling ismaster on 'luxemassage-shard-00-02-0kahc.mongodb.net:27017']' in /home/petfindr/public_html/new/vendor/mongodb/mongodb/src/Collection.php:464 Stack trace: #0 /home/petfindr/public_html/new/vendor/mongodb/mongodb/src/Collection.php(464): MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference)) #1 /home/petfindr/public_html/new/configs/core.php(28): MongoDB\Collection->findOne(Array) #2 /home/petfindr/public_html/new/index.php(104): syscore->testDBConnection() #3 {main} thrown in /home/petfindr/public_html/new/vendor/mongodb/mongodb/src/Collection.php on line 464`

Now here is a simple solution. give an an example connection to mongodb Atlias as the string they give us brings that error up to.

**Comment by lindelius** [comment]
You have an extra equals sign in front of authSource in your query string. Remove it and try connecting again.

**Comment by jmikola** [comment]
There are already connection examples for the driver and library:

 * http://php.net/manual/en/mongodb-driver-manager.construct.php
 * https://docs.mongodb.com/php-library/master/reference/method/MongoDBClient__construct/

This should just be a matter of copy-pasting the URI into the first argument for the `MongoDB\Driver\Manager` or `MongoDB\Client` constructor. I've also personally connected to Atlas URIs in recent weeks with no issue.

One observation I have about your URI is that `&=authSource=admin` should not have an `=` character before `authSource`. If that was not a typo and Atlas actually gave you that string, I'd suggest contacting the Atlas support team to report that.

I'm going to close this, as your report duplicates a comment in your [existing issue on the library project](https://github.com/mongodb/mongo-php-library/issues/285#issuecomment-261505641). Let's keep the discussion consolidated there.
