### ISSUE TITLE
Install doesn't work with Homebrew and OSX 10.12

### ISSUE THREAD

**Issue by Liberateur** [mongodb/mongo-php-driver#468]
**SOURCE :** http://stackoverflow.com/questions/40790093/i-can-not-install-mongodb-php56-osx

----------

I try to install MongoDB for PHP56 but i can not... I don't find "mongo" in my phpinfo(); and class not found.

- https://docs.mongodb.com/ecosystem/drivers/php/
- http://php.net/manual/fr/mongodb.installation.homebrew.php
- https://www.sitepoint.com/building-simple-blog-app-mongodb-php/
- (doesn't work) http://stackoverflow.com/questions/30205687/brew-install-php56-mongo-command-not-working

----------

    # [INFORMATIONS]
    MongoDB run in my mac
    PHP 5.6.4
    OSX 10.12.1-x86_64 (Sierra)
    Homebrew 1.1.1
    Java 1.8.0_101
    Xcode 8.1

    # [COMMANDS INSTALL]

    $ brew update

    $ brew tap homebrew/php (i try without)

    $ brew install php56-mongodb
    ==> Installing php56-mongodb from homebrew/php
    ==> Downloading https://homebrew.bintray.com/bottles-php/php56-mongodb-1.1.9.sierra.bottle.ta
    Already downloaded: /Users/cedric/Library/Caches/Homebrew/php56-mongodb-1.1.9.sierra.bottle.tar.gz
    ==> Pouring php56-mongodb-1.1.9.sierra.bottle.tar.gz
    ==> Caveats
    To finish installing mongodb for PHP 5.6:
      * /usr/local/etc/php/5.6/conf.d/ext-mongodb.ini was created,
        do not forget to remove it upon extension removal.
      * Validate installation via one of the following methods:
      *
      * Using PHP from a webserver:
      * - Restart your webserver.
      * - Write a PHP page that calls "phpinfo();"
      * - Load it in a browser and look for the info on the mongodb module.
      * - If you see it, you have been successful!
      *
      * Using PHP from the command line:
      * - Run `php -i "(command-line 'phpinfo()')"`
      * - Look for the info on the mongodb module.
      * - If you see it, you have been successful!
    ==> Summary
    🍺 /usr/local/Cellar/php56-mongodb/1.1.9: 3 files, 562.0K

    $ sudo apachectl -k restart
    AH00557: httpd: apr_sockaddr_info_get() failed for XXXXXXX.local
    AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message

    $ php --ini
    Configuration File (php.ini) Path: /usr/local/etc/php/5.6
    Loaded Configuration File:         /usr/local/etc/php/5.6/php.ini
    Scan for additional .ini files in: /usr/local/etc/php/5.6/conf.d
    Additional .ini files parsed:      /usr/local/etc/php/5.6/conf.d/ext-mongodb.ini

    $ php -i | grep "mongo"
    Additional .ini files parsed => /usr/local/etc/php/5.6/conf.d/ext-mongodb.ini
    PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
    mongodb
    mongodb support => enabled
    mongodb version => 1.1.9
    mongodb stability => stable
    libmongoc version => 1.3.6
    mongodb.debug => no value => no value
    PATH => /opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mongodb/bin
    _SERVER["PATH"] => /opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mongodb/bin

**Comment by alcaeus** [comment]
As you can see in the output of your last command, the driver was installed successfully. The mongodb driver does not have a `Mongo` class. As outlined in [the documentation](https://secure.php.net/MongoDb), all classes can be found in the `MongoDB\Driver` namespace.

**Comment by Liberateur** [comment]
Hey hi @alcaeus, thanks for try to help me !

When i start my php script :
[Fri Nov 25 11:07:48.875389 2016] [:error] [pid 57066] [client ::1:53423] PHP Fatal error:  Class 'Mongo' not found in /Users/XXXXX/index.php on line 5, referer: http://localhost/~XXXXX/

PHP File :
namespace Core;
$db = new \Mongo();

In phpinfo(); i have normaly "mongo", but i don't have.

**Comment by alcaeus** [comment]
You have installed the new mongodb driver. If you're looking for the legacy driver (the one that includes the `Mongo` class), you need to install `php56-mongo`.

**Comment by derickr** [comment]
You have installed the new "mongodb" driver, which does not have the "Mongo" class. As @alcaeus says, all classes are found in the \MongoDB namespaces now. 

Some information on the new driver and the library that you should use with it: https://docs.mongodb.com/php-library/master/

**Comment by Liberateur** [comment]
Ok guys, so i have installed `php56-mongo` with `brew install php56-mongo` command.

I create new test :
```
<?php
new Mongo();

# LOG
# [Fri Nov 25 11:36:07.598776 2016] [:error] [pid 69086] [client ::1:53934] PHP Fatal error:  Class 'Mongo' not found in /Users/XXXXX/index.php on line 2, referer: http://localhost/~XXXXX/

<?php
new MongoDB();

# LOG
# [Fri Nov 25 11:36:29.015709 2016] [:error] [pid 69078] [client ::1:53935] PHP Fatal error:  Class 'MongoDB' not found in /Users/XXXXX/index.php on line 2, referer: http://localhost/~XXXXX/
```

I remove `brew remove php56-mongodb`, same errors.

If mongo is not in phpinfo(), he is not loaded no ?

**Comment by Liberateur** [comment]
Hey ! I found ! 

**OSX use different php folders**, my apache use different folder to php commands line tool... I added in `/etc/php.ini` : `extension="/usr/local/opt/php56-mongodb/mongodb.so"`

Thanks for help and have nice day !

**Comment by abinhho** [comment]
Try here
https://github.com/Homebrew/homebrew-core/issues/21475#issuecomment-352155715

The following process fixed the issue with php-mongodb driver (temporary workaround)

We are simply compiling the packages with system SSL instead of Homebrew OpenSSL.

$ brew install --build-from-source mongo-c-driver
Make sure it is using --enable-ssl=darwin flag while running ./configure

We will now remove httpd and reinstall it with php71

$ brew remove httpd
$ brew reinstall --build-from-source php71 --with-httpd --with-homebrew-libressl

#compile mongodb driver

$ git clone https://github.com/mongodb/mongo-php-driver.git
$ cd mongo-php-driver
$ git checkout 048d6efa75852ab573ef5dc08267d3e3a3dfb114
$ git submodule sync && git submodule update --init
$ sudo phpize
$ ./configure --with-libmongoc=yes --with-libbson=yes --with-openssl-dir=/usr
$ make clean
$ sudo make install
Now link the new mongodb.so library to your php. Restart apache. Enjoy!! :) :)

Tested with PHP71 and PHP72!

**Comment by jmikola** [comment]
For anyone that comes across @abinhho's post above, please note that these instructions are outdated. See @alcaeus's reply in https://github.com/mongodb/mongo-php-driver/issues/681#issuecomment-397946003 for further details.
