### ISSUE TITLE
"No suitable servers found" on 1.2.0

### ISSUE THREAD

**Issue by wshafer** [mongodb/mongo-php-driver#479]
### Description

Exception: `No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on '127.0.0.1:27017']`

After installing version 1.2.0 I am getting the error "No suitable servers found" when running tasks in parallel.   After downgrading to 1.1.9, the problem went away.

### Environment
Ubuntu 16.04
PHP: PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
imap
intl
json
libxml
mailparse
mbstring
mcrypt
memcached
mongodb
mysqli
mysqlnd
newrelic
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
radius
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

### Test Script

```
<?php
$children = [];

while (true) {
    $batchSize = 20;
    
    $pid = pcntl_fork();

    // if no pid # we are a child process
    if (!$pid) {
        // Child connects to Mongo
        $client = new \MongoDB\Client('mongodb://127.0.0.1:27017');

        // Do something with connection here


        // Child needs to terminate when complete
        exit;
    }

    // parent to keep track of pids so only the allowed $batchSize
    // is running 
    $children[$pid] = $pid;

    if (count($children) == $batchSize) {
        $pid = pcntl_waitpid(0, $status);
        unset($children[$pid]);
    }
}
```
Note:   This will run for awhile, however eventually it will crash after about 200-300 children have spawned.

### Expected and Actual Behavior

Scripts runs normally and connects to MongoDb

**Comment by jmikola** [comment]
> Note: This will run for awhile, however eventually it will crash after about 200-300 children have spawned.

Does the parent process actually crash (e.g. segfault), or does that just mean that you get a "No suitable servers found" exception? If an actual crash occurs, are you able to provide a backtrace?

Assuming it's just exceptions, do all of the children after a certain point start throwing exceptions? There doesn't appear to be any point in the parent process where a driver exception might be thrown. Do you have any insights into the return status from the children (since `$status` isn't being examined)?

**Comment by jmikola** [comment]
The [1.2.6](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.6) release includes fixes for two issues that may have been related. I'd appreciate if you could test that version and report back if your issue persists.

**Comment by wshafer** [comment]
Hi @jmikola

Thanks for the reply.  I am actually no longer on that project and have no good way to test this. 

Going to go ahead an close this issue.
