### ISSUE TITLE
how to install pecl extension in ubuntu 16 

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb/mongo-php-driver#482]
I have installed Ubuntu 16 with php 7.0.8 when i runt the pecl install mongodb command it return pecl is not recognized any one could help me ?

**Comment by moderndeveloperllc** [comment]
Instead of using pecl, you can `sudo apt-get install php7.0-mongodb` which should get it.

**Comment by jmikola** [comment]
The newest Ubuntu package appears to be [1.1.5](http://packages.ubuntu.com/xenial/php-mongodb), but the [ppa:ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php) repository has our latest 1.2.0 version.

This is not the right place to ask about installing PECL on Ubuntu. That question is best taken to the [Ask Ubuntu](http://askubuntu.com/) forums. Here is [one thread](http://askubuntu.com/q/403327/592832) discussing PECL for PHP 5.x. The process for PHP 7.x should be quite similar (albeit with renamed packages).
