### ISSUE TITLE
extending BSON classes

### ISSUE THREAD

**Issue by rbro** [mongodb/mongo-php-driver#495]
In the legacy mongo driver, I was able to extend the MongoDate class and add my own custom methods.  When I tried to do the same with MongoDB\BSON\UTCDateTime, I got an error that the class cannot be extended because it's marked final.  Is there a way to extend the BSON classes of the new MongoDB driver?

```
<?php
class abc extends MongoDB\BSON\UTCDateTime
{

}
```

The error is:
```
Fatal error: Class abc may not inherit from final class (MongoDB\BSON\UTCDateTime) in /tmp/test.php on line 5
```

Thanks for your help.

**Comment by derickr** [comment]
We do not allow this, as most BSON types encapsulate PHP internal structures.

We have currently no plans to allow it directly, but we are working on https://jira.mongodb.org/browse/PHPC-640 which should implement something similar.

The HHVM driver already has this implemented (but not yet documented). It is explained at https://github.com/mongodb/mongo-hhvm-driver/blob/master/serialization.rst#scalar-types A test file showing what this would do is at https://github.com/mongodb/mongo-hhvm-driver/blob/master/tests/bson-deserialize-typewrapped-utcdatetime-001.phpt

**Comment by rbro** [comment]
Derick - thanks for the quick reply.  Yes, PHPC-640 will cover it.  I will watch for that ticket to be added to the mongo-php-driver.
