### ISSUE TITLE
Exception: No suitable servers found (`serverSelectionTryOnce` set): [Server closed connection. calling ismaster on 'mongodb.xxxx.com:40000'] 

### ISSUE THREAD

**Issue by kkperson** [mongodb/mongo-php-driver#501]
### Description

Dear mongo php driver developer team,
We met a problem when upgrading the mongo php driver from 1.1.9 to 1.2.x,
after updating to the newest driver, it works fine for a period time and then will show the following message:

> Exception: No suitable servers found (`serverSelectionTryOnce` set): [Server closed connection. calling ismaster on 'mongodb.xxxx.com:40000']
> /var/www/xxx/composer/mongodb/mongodb/mongodb/src/Collection.php at lines 177, 242, 531

mongodb.xxxx.com is the AWS ELB (load balancer service) which bind three of our mongodb servers's mongos(we setup shard on them).

I  watched many jmikola's suggestions from google but all of them not finish our problem, 
but I found a weird phenomenon, when I ran the sample code I post below, It shown the different
results with different versions drivers, could you give us some suggestions? thanks.
 
[DRIVER 1.2.0, 1.2.1, 1.2.2]

```
object(MongoDB\Driver\Manager)#2 (2) {
  ["uri"]=>
  string(34) "mongodb://mongodb.xxxx.com:40000/"
  ["cluster"]=>
  array(0) {
  }
}
```

[DRIVER 1.1.9]

```
object(MongoDB\Driver\Manager)#2 (2) {
  ["uri"]=>
  string(34) "mongodb://mongodb.xxxx.com:40000/"
  ["cluster"]=>
  array(1) {
    [0]=>
    array(11) {
      ["host"]=>
      string(17) "mongodb.xxxx.com"
      ["port"]=>
      int(40000)
      ["type"]=>
      int(0)
      ["is_primary"]=>
      bool(false)
      ["is_secondary"]=>
      bool(false)
      ["is_arbiter"]=>
      bool(false)
      ["is_hidden"]=>
      bool(false)
      ["is_passive"]=>
      bool(false)
      ["tags"]=>
      array(0) {
      }
      ["last_is_master"]=>
      array(0) {
      }
      ["round_trip_time"]=>
      int(-1)
    }
  }
}
```

### Environment

UBUNTU 16.04 
PHP7.1.0-3

[1.2.2]

```
mongodb
mongodb support => enabled
mongodb version => 1.2.2
mongodb stability => stable
libmongoc version => 1.5.0
libbson version => 1.5.0
mongodb.debug => no value => no value
```

[1.1.9]

```
mongodb support => enabled
mongodb version => 1.1.9
mongodb stability => stable
libmongoc version => 1.3.6
libbson version => 1.3.6
mongodb.debug => no value => no value
```

### Test Script

```
<?php
include "mongodb/autoload.php";
ini_set('mongodb.debug', 'stderr');
$options = ['connecttimeoutms' => 1000, 'wtimeoutms' => 1000];
$manager = new MongoDB\Driver\Manager('mongodb://mongodb.xxxx.com:40000/',$options);
var_dump($manager);
```

### Debug

[1.2.0, 1.2.1, 1.2.2]
```
[2016-12-22T04:03:40+00:00]     PHONGO: DEBUG   > Connection string: 'mongodb://mongodb.xxxx.com:40000/'
[2016-12-22T04:03:40+00:00]     PHONGO: DEBUG   > Creating Manager, phongo-1.2.2[stable] - mongoc-1.5.0(bundled), libbson-1.5.0(bundled), php-7.1.0-3+deb.sury.org~xenial+1
[2016-12-22T04:03:40+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_init():54
[2016-12-22T04:03:40+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_init():75
[2016-12-22T04:03:40+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_init():94
[2016-12-22T04:03:40+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_init():131
[2016-12-22T04:03:40+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_init():1760
[2016-12-22T04:03:40+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_init():1785
[2016-12-22T04:03:40+00:00]     PHONGO: DEBUG   > Created client hash: a:3:{s:3:"uri";s:34:"mongodb://mongodb.xxxx.com:40000/";s:7:"options";a:2:{s:16:"connecttimeoutms";i:1000;s:10:"wtimeoutms";i:1000;}s:13:"driverOptions";N;}

object(MongoDB\Driver\Manager)#2 (2) {
  ["uri"]=>
  string(34) "mongodb://mongodb.xxxx.com:40000/"
  ["cluster"]=>
  array(0) {
  }
}
[2016-12-22T04:03:40+00:00]     mongoc: DEBUG   > Not destroying persistent client for Manager
```

[1.1.9]
```
[2016-12-22T04:08:06+00:00]     PHONGO: DEBUG   > Connection string: 'mongodb://mongodb.xxxx.com:40000/'
[2016-12-22T04:08:06+00:00]     PHONGO: TRACE   > ENTRY: php_phongo_make_mongo_client():1924
[2016-12-22T04:08:06+00:00]     PHONGO: DEBUG   > Creating Manager, phongo-1.1.9[stable] - mongoc-1.3.6(bundled), libbson-1.3.6(bundled), php-7.1.0-3+deb.sury.org~xenial+1
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_init():51
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_init():68
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_init():87
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_init():123
[2016-12-22T04:08:06+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_init():1597
[2016-12-22T04:08:06+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_init():1620
[2016-12-22T04:08:06+00:00]     client: DEBUG   > Using custom stream initiator.
[2016-12-22T04:08:06+00:00]     PHONGO: TRACE   >  EXIT: php_phongo_make_mongo_client():2025
object(MongoDB\Driver\Manager)#2 (2) {
  ["uri"]=>
  string(34) "mongodb://mongodb.xxxx.com:40000/"
  ["cluster"]=>
  array(1) {
    [0]=>
    array(11) {
      ["host"]=>
      string(17) "mongodb.xxxx.com"
      ["port"]=>
      int(40000)
      ["type"]=>
      int(0)
      ["is_primary"]=>
      bool(false)
      ["is_secondary"]=>
      bool(false)
      ["is_arbiter"]=>
      bool(false)
      ["is_hidden"]=>
      bool(false)
      ["is_passive"]=>
      bool(false)
      ["tags"]=>
      array(0) {
      }
      ["last_is_master"]=>
      array(0) {
      }
      ["round_trip_time"]=>
      int(-1)
    }
  }
}
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   > ENTRY: mongoc_topology_description_destroy():89
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   > ENTRY: mongoc_server_description_destroy():145
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   >  EXIT: mongoc_server_description_destroy():151
[2016-12-22T04:08:06+00:00]     mongoc: TRACE   >  EXIT: mongoc_topology_description_destroy():103
[2016-12-22T04:08:06+00:00]    cluster: TRACE   > ENTRY: mongoc_cluster_destroy():1643
[2016-12-22T04:08:06+00:00]    cluster: TRACE   >  EXIT: mongoc_cluster_destroy():1653
```

**Comment by jmikola** [comment]
> when I ran the sample code I post below, It shown the different results with different versions drivers, could you give us some suggestions?

The differences in `var_dump()` output you shared should not be a concern. In 1.1.x, the PHP extension was using libmongoc's private APIs, while the 1.2.x series uses only its public API. Compare:

 * In 1.1.9, we iterate on [`client->topology->description.servers` directly](https://github.com/mongodb/mongo-php-driver/blob/1.1.9/src/MongoDB/Manager.c#L465), which includes entries for undiscovered servers populated from the URI's seed list.
 * In 1.2.2, we use [`mongoc_client_get_server_descriptions()`](https://github.com/mongodb/mongo-php-driver/blob/1.2.2/src/MongoDB/Manager.c#L535), which filters out unknown servers.

In both cases, the driver has yet to discover the type of server provided to the Manager constructor.

> mongodb.xxxx.com is the AWS ELB (load balancer service) which bind three of our mongodb servers's mongos(we setup shard on them).

I believe you're using the correct deployment model. Note that per the [shared cluster docs](https://docs.mongodb.com/manual/core/sharded-cluster-components/#production-configuration) the load balancer should be configured for "client affinity such that every connection from a single client reaches the same mongos."

Based on the exception you shared, it seems like the load balancer is dropping connections after a certain point. Not knowing the details of your PHP deployment (e.g. number of app servers and their request load), it's possible that you're hitting idle timeouts on connections held by some PHP workers' persistent client objects (documented [here](http://php.net/manual/en/mongodb.connection-handling.php)).

The [Elastic Load Balancing Connection Timeout Management](https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/) blog post may have more information about how to adjust this. If you have insight into whether the ELB is actually killing idle connections, I would suggest looking into those logs to verify that dropped idle connections are indeed the cause here.

**Comment by kkperson** [comment]
Hi jmikola,

Thanks to your reply, 
did you mean because the newer version's driver supports the persistent connection and the older one doesn't, resulting in the problem ? 

I think it's a good point that let me to deeply research this problem. In AWS ELB, we set the idle timeout is 1800 seconds and the connection draining time is 300 seconds. 

In our API server, we run 4 instances of php7.1-fpm sockets and each one setting as below:
```
[www-X]
user = www-data
group = www-data
listen = /run/php/php7.1-fpm-X.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm = static
pm.max_children = 45
pm.max_requests = 2000
request_terminate_timeout = 300
listen.backlog = 1024
```

Our architecture is 2 api servers bind to a AWS ELB, and 3 mongodb servers bind to the other AWS ELB. The mongodb servers' architecture you can reference [this](http://blog.itpub.net/attachment/201501/16/27000195_1421398908h0A0.png).

Above, I think the ELB and API server timeout setting should be correct,
now we start to record the ELB log, hoping we can find something there.

After researching I will post the result here, thanks.

**Comment by jmikola** [comment]
> did you mean because the newer version's driver supports the persistent connection and the older one doesn't, resulting in the problem ?

The 1.1.x series and earlier persist only the sockets to the database, which mean that each request needed to re-authenticate and fully discover the topology. 1.2.0 and later persist the entire libmongoc client object, which includes sockets and topology state. Subsequent requests in 1.2.0+ do not need to fully discover the topology and can resume monitoring from a known state. I believe this is thoroughly explained in the [Connection Handling](http://php.net/manual/en/mongodb.connection-handling.php) docs.

[`request_terminate_timeout`](http://php.net/manual/en/install.fpm.configuration.php) only pertains to killing a worker that is still serving a long-running request. My theory is that you have a worker that does not interact with MongoDB for a period longer than the ELB timeout, and it realizes its MongoDB connection was dropped when serving some future request that accesses MongoDB.

**Comment by kkperson** [comment]
Hi jmikola, 
After observing 2 days, the newest mongodb driver still working perfectly,
and thanks to the keep connection information mechanism, 
it reduces much of our servers' resources.

Also, due to the keep mechanism, the AWS ELB's problem occurred, 
although we already set the idle timeout to 1800 seconds,
but seems it still cannot keep the topology information, 
so we decide to remove the mongodb's ELB and just use the mongos load balancer,
we think it's correct choice for the new driver and future version of mongodb.

Really thanks your big support, to the world you may be one person, but to me you may be the world.

**Comment by jmikola** [comment]
@kkperson: Glad to hear the driver is doing its job here. I have no experience running MongoDB with AWS ELB, so my notes above were just the results of some quick research. If you did have additional questions about ELB, it might be worthwhile asking on the [mongodb-user](https://groups.google.com/d/forum/mongodb-user) forum, as I expect there is an audience there with some applicable experience.

That said, I think running a mongos instance on each application server is probably the way to go.

**Comment by rohitkhatri** [comment]
@jmikola I am having kind of same issue, I am not getting this error all of the times, but sometimes when I open the browser and hit the website, It throws the `No suitable servers found` error, I am using mongodb atlas cloud, and I'm also using that `cluster` in python. There's no issue with python, but with php (`jenssegers/laravel-mongodb`), I receive the same error sometimes and after reloading 2-3 times, the error doesn't appear, can you help me with that?

**Comment by jmikola** [comment]
@rohitkhatri: Please open a new issue and provide as much information as possible as requested in the issue template.

**Comment by rohitkhatri** [comment]
@jmikola sure, thanks.
