### ISSUE TITLE
Huge latency from a replica set while one host is down.

### ISSUE THREAD

**Issue by fr05t1k** [mongodb/mongo-php-driver#502]
### Description

When we're trying to make a first connection and call ismaster from replica set we achieve `connectTimeoutMS`. Therefore first request sends with `connectTimeoutMS` latency. It happens when one node from replica set completely down (not present in network). Is it normal?

### Environment
OS: MacOS/Debian 
MongoDB 3.2
PHP 7.0,7.1
```
mongodb
mongodb support => enabled
mongodb version => 1.2.1
mongodb stability => stable
libmongoc version => 1.5.0
libbson version => 1.5.0
mongodb.debug => no value => no value
```
### Test Script

```
<?php

function getDb()
{
    $uriOptions = [
        'connectTimeoutMS' => 1000, // we have huge network latency sometimes 
        'socketTimeoutMS' => 10000,
    ];
    return new \MongoDB\Client(
        sprintf(
            'mongodb://%s,%s,%s,%s/test?replicaSet=rs&rand=%d',
            '192.168.99.100:30001',
            '192.168.99.100:30002',
            '192.168.99.100:30003',
            '192.168.99.101:30001', // this host don't present in network 
            random_int(0, 100000) // to make new connection everytime 
        ),
        $uriOptions
    );
}

foreach (range(0, 100) as $i) {
    $start = microtime(true);
    getDb()->selectCollection('test', 'test')->find(); 
    echo sprintf("\nTotal: %fms", (microtime(true) - $start) * 1000);
    sleep(1);
}
```

### Expected and Actual Behavior

Probably it is expected behavior. If you have any idea how to speed up first query without decreasing `connectTimeoutMS` let me know.

Why we are waiting response from all nodes if we get response from most of them?

### Debug Log
```
Total: 1015.043020ms
Total: 1009.300947ms
Total: 1010.063887ms
Total: 1010.748148ms
Total: 1009.697914ms
```

**Comment by jmikola** [comment]
> Probably it is expected behavior. If you have any idea how to speed up first query without decreasing connectTimeoutMS let me know.
>
> Why we are waiting response from all nodes if we get response from most of them?

The current behavior is consistent with the [Server Discovery and Monitoring specification](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst) implemented by all drivers. To quote [this section](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#clients-do-no-io-in-the-constructor):

> When discovery begins, the client checks all its seeds, and discovery is complete once all servers have been checked, or after some maximum time. Application operations cannot proceed until discovery is complete.

The "maximum time" here is `connectTimeoutMS` (as described [here](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#socket-timeout-for-monitoring-is-connecttimeoutms)).

Additionally, the SDAM spec states that the client constructors not perform any IO. This means that server discovery happens during the first request (unless the client was previously persisted and is now being reused).

**Comment by fr05t1k** [comment]
```php

function getDb()
{
    $uriOptions = [
        'connectTimeoutMS' => 1000, // we have huge network latency sometimes 
        'socketTimeoutMS' => 10000,
    ];
    return new \MongoDB\Client(
        sprintf(
            'mongodb://%s,%s,%s,%s/test?replicaSet=rs',
            '192.168.99.100:30001',
            '192.168.99.100:30002',
            '192.168.99.100:30003',
            '192.168.99.101:30001' // this host don't present in network 
        ),
        $uriOptions
    );
}

foreach (range(0, 100) as $i) {
    $start = microtime(true);
    getDb()->selectCollection('test', 'test')->find(); 
    echo sprintf("\nTotal: %fms", (microtime(true) - $start) * 1000);
    sleep(1);
}
```

**Comment by fr05t1k** [comment]
Ok, I get it.
I changed this script and ran it with fpm 3 times with ~3 seconds interval between them.

```php
function getDb()
{
    $uriOptions = [
        'connectTimeoutMS' => 1000, // we have huge network latency sometimes 
        'socketTimeoutMS' => 10000,
    ];
    return new \MongoDB\Client(
        sprintf(
            'mongodb://%s,%s,%s,%s/test?replicaSet=rs',
            '192.168.99.100:30001',
            '192.168.99.100:30002',
            '192.168.99.100:30003',
            '192.168.99.101:30001' // this host don't present in network 
        ),
        $uriOptions
    );
}

foreach (range(0, 5) as $i) {
    $start = microtime(true);
    getDb()->selectCollection('test', 'test')->find(); 
    echo sprintf("\nTotal: %fms", (microtime(true) - $start) * 1000);
    sleep(1);
}
```

and I got 

```
# 1st request
Total: 1006.237030ms  
Total: 3.076077ms  
Total: 2.791166ms  
Total: 1.595020ms  
Total: 2.937078ms  
Total: 2.613068ms  

# 2nd request
Total: 1008.968115ms  
Total: 1.593113ms  
Total: 1.619101ms  
Total: 1.672029ms  
Total: 2.794027ms  
Total: 1.867056ms  

# 3rd request
Total: 3.895998ms  
Total: 1.966000ms  
Total: 1.651049ms  
Total: 1.626015ms  
Total: 1.610041ms  
Total: 1.628876ms  
```

Why 2nd request achieved connectTimeoutMS if 1st request already had done service discovery?

**Comment by fr05t1k** [comment]
Service discovery run for every fpm child process, right?

**Comment by jmikola** [comment]
> Why 2nd request achieved connectTimeoutMS if 1st request already had done service discovery?

I would assume that the first and second requests were served by different worker processes, and the third request was served by a worker with a libmongoc client already persisted. If you capture debug info via the [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php) INI setting, it should report whether the driver found an existing, persisted client to re-use or needed to create a new one.

> Service discovery run for every fpm child process, right?

To be clear, libmongoc clients are persisted within each worker process (see: [Connection Handling](http://php.net/manual/en/mongodb.connection-handling.php)). Each client contains the sockets, authentication state, and topology state (resulting from server discovery).

**Comment by fr05t1k** [comment]
@jmikola
