### ISSUE TITLE
PHP cannot access MongoDB

### ISSUE THREAD

**Issue by arifhussain353** [mongodb/mongo-php-driver#503]
Hi am trying to use `moadmin` with `MongoDB` but getting this error.
```
PHP cannot access MongoDB, you need to install the Mongo extension for PHP.
```
I add `MongoDB`  extension `extension=mongodb.so`  in `/etc/php/7.0/apache2/php.ini` and restart `apache2` aswell.
Here is `MongoDB` and `php` version detail which i have installed
```
libmongoc version => 1.3.3
mongodb version => 1.1.5
php version 7.0
```
I opened issue here because i am facing problem related `mongodb` extension 
Thanks

**Comment by moderndeveloperllc** [comment]
@arifhussain353 Are you using [this library](https://github.com/MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP)? Based on your error message, it looks that way. If so, then unfortunately they do not support the new `mongodb` extension. It only works with the [older extension](https://github.com/MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP/blob/master/moadmin.php#L310).

**Comment by arifhussain353** [comment]
@moderndeveloperllc I will try with older version extension and will inform you here in case still having issue.Thanks

**Comment by jmikola** [comment]
You may be able to get phpMoAdmin working with the new extension and library by adding [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) to the mix. It provides most of the legacy driver's API and should work for most applications.

On a side note, I'd be wary of any project using `eval()` (see: https://github.com/MongoDB-Rox/phpMoAdmin-MongoDB-Admin-Tool-for-PHP/commit/89ac561fe24f92b37cfd5caed9ed935937a3988e). There is no shortage of [MongoDB GUIs](https://scalegrid.io/blog/which-is-the-best-mongodb-gui/) if you'd like to consider another tool.
