### ISSUE TITLE
Possibility to check if string is valid for ObjectID

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-driver#509]
There is `\MongoId::isValid()` method in legacy driver.
Is method `ObjectID::isValid()` planned for future releases of this driver, or does this driver has an alternative?

**Comment by moderndeveloperllc** [comment]
Doesn't look to be a [ticket created for this](https://jira.mongodb.org/browse/PHPC-500?jql=project%20%3D%20PHPC%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC) if you want to try and see if they would add it. It does look like it will [throw an exception](http://php.net/manual/en/mongodb-bson-objectid.construct.php) if you try to construct an ObjectID with something other than a 24-character hexadecimal string. It would depend on your logic, but offhand, I would think you would want an Exception if you were expecting an ObjectID string and got something different. i also found this which would check validity:
```
preg_match('/^[a-f\d]{24}$/i', $id)
```

**Comment by jmikola** [comment]
We've no plans to add a static method for this, as it's trivial enough to do in userland if you'd rather check a string in lieu of constructing an ObjectID in a try/catch block.

If you'd prefer to avoid a regex, I might also suggest ['strspn()`](https://php.net/strspn):

```
strlen($oid) === 24 && strspn($oid,'0123456789ABCDEFabcdef') === 24
```

**Comment by moderndeveloperllc** [comment]
@jmikola Just to show you learn something everyday, in ~15 years of doing PHP dev I don't think I've ever used or even run across strspn(); other than my eyes drifting past it in the docs. Too bad I'll probably forget about it by next week!

**Comment by petr-buchin** [comment]
@moderndeveloperllc thank you very much, but I just needed to know, whether this functionality is planned in low-level driver, or I should implement it in userland library.

@jmikola , thanks! I also didn't know about this function :)
