### ISSUE TITLE
 Unrecognized field 'readConcern' 

### ISSUE THREAD

**Issue by sautchenkov** [mongodb/mongo-php-driver#516]
Hello! 
We have 3 nodes of mongodb 3.2.11 with replication settings. And now using mongodb-1.2.0alpha3 driver installed via pecl. All working good. But we want to update library to stable version. 

When we try to update mongodb driver to 1.2.3 stable, we begin to receive PHP fatal error:

`2017/01/23 17:40:07 [error] 22364#22364: *49812 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught MongoDB\Driver\Exception\RuntimeException: Failed to parse: { getMore: 33073741133165, collection: "showcase_tree", readConcern: { level: "local" } }. Unrecognized field 'readConcern'. in /var/www/recommerce/models/mBaseModelNestedTree.php:527`

We using latest mongo PHP library from Github. 

Our connection string:
```
$this->client = new \MongoDB\Client(
'mongodb://'. $user .':'. $password .'@'. $hosts,
[
'connectTimeoutMS' => 2000,
'replicaSet' => 'rs0',
'w' => 1,
'wtimeoutMS' => 3000,
'journal' => 'false',
'readConcernLevel' => 'local',
'readPreference' => $this->default_read_preference
],
[
'typeMap' => ['root' => 'array', 'document' => 'array', 'array' => 'array']
]
);
```
When we try to comment `'readConcernLevel' => 'local'` line our webapp start to work without fatal but very very slow.

Will glad for any help!

**Comment by jmikola** [comment]
Can you share a complete PHP script that reproduces the exception you're seeing (from instantiating a `MongoDB\Client` to executing a query)?

**Comment by sautchenkov** [comment]
Hi!
This is code:
```
<?php

$MONGO_HOSTS = [
	'hetzner-1',
	'belarus-1',
	'selectel-1',
];

foreach($MONGO_HOSTS as $server) {
	$hosts .= $server .':'. $port .',';
}

$client = new \MongoDB\Client(
	'mongodb://'. $user .':'. $password .'@'. $hosts,
	[
		'connectTimeoutMS' => 2000,
		'replicaSet' => 'rs0',
		'w' => 1,
		'wtimeoutMS' => 3000,
		'journal' => 'false',
		'readConcernLevel' => 'local',
		'readPreference' => 'primaryPreferred'
	],
	[
		'typeMap' => ['root' => 'array', 'document' => 'array', 'array' => 'array']
	]
);

$db = $client->selectDatabase('domozon_reshop_by');

$collection = $db->selectCollection('customers');

$cursor = $collection->find([], ['sort' => ['date' => -1]]);

$i = 1;
foreach ($cursor as $document) {
	echo '<pre>';
	echo $i++ . ' ' . $document['_id'] . '<br>';
	echo '</pre>';
}
```
This is result which this code generate:
```
1 51b6f55df15e44950900005a
2 51c437c7f15e44f439000002
3 51c73df4f15e44df5300000b
.......................
.......................
100 5264e23c50eba1f92a000097
101 5265057b50eba1fc28000093

Fatal error: Uncaught MongoDB\Driver\Exception\RuntimeException: Failed to parse: { getMore: 44504619209605, collection: "customers", readConcern: { level: "local" } }. Unrecognized field 'readConcern'. in /var/www/recommerce/utilites/test.php:57 Stack trace: #0 {main} thrown in /var/www/recommerce/utilites/test.php on line 57
```
Collection contain ~2500 documents, but after generate 101 element we receive fatal.

**Comment by lindelius** [comment]
Is this the `test.php` file? If so, please include the rest of the file. If not, please include that file, as well.

**Comment by jmikola** [comment]
I was able to reproduce the error locally by using a small collection of three documents and issuing a query with a "local" `readConcernLevel` and `batchSize` of 2, which triggers a `getMore` when iterating to the third result document.

This appears to be a bug in libmongoc, which I've reported in [CDRIVER-2003](https://jira.mongodb.org/browse/CDRIVER-2003). I also opened [PHPC-898](https://jira.mongodb.org/browse/PHPC-898) as a local tracking issue, so feel free to watch either of those tickets for updates.

**Comment by sautchenkov** [comment]
Hi @lindelius! This is completed test.php file. Now I added few lines to begin of the file, which I cut before. Also, changed in error message to correct line. 
This is 41 line throw fatal:   
`foreach ($cursor as $document) {`

**Comment by sautchenkov** [comment]
@jmikola ok, thanks! Will wait solution.

**Comment by jmikola** [comment]
[1.2.4](https://github.com/mongodb/mongo-php-driver/releases/tag/1.2.4) is released with the necessary bug fix. If you were not using the bundled libbson and libmongoc libraries and are instead using system packages (more common on Debian and CentOS), you can get by with simply updating libmongoc to 1.5.4.
