### ISSUE TITLE
eval command is deprecated

### ISSUE THREAD

**Issue by leoncool** [mongodb/mongo-php-driver#535]
Hello Guys, 

I am currently using $connection->command() to call the dataSize function of mongodb. 
query string looks like this:

```
{ dataSize: "database.collection", keyPattern: { field: 1 }, min: { field: 10 }, max: { field: 100 } }
```

https://docs.mongodb.com/manual/reference/command/dataSize/

However, dataSize command is triggered by eval function using the PHP mongo library, which in the mongodb log, it shows "eval command is deprecated". I wish to upgrade to > MongoDB 3.0 soon. My application uses "dataSize" function a lot. What shall I do please? 

Thanks!

**Comment by derickr** [comment]
Hi,

when you say "PHP mongo library" - which exact one do you mean? Do you mean the legacy driver: https://pecl.php.net/package/mongo, the new driver: https://pecl.php.net/package/mongodb, or the PHP library to go with the new driver: https://docs.mongodb.com/php-library/master/ ?

The old legacy driver seems to be the only one that uses eval, but only in its a "execute" method (http://php.net/manual/en/mongodb.execute.php), and not in the command() method.

In any case, you probably want to migrate to the new mongodb extension (https://pecl.php.net/package/mongodb) with the PHP Library (https://docs.mongodb.com/php-library/master/ ) as the legacy driver is also deprecated, and does not support the new features of MongoDB 3.2 and later.

**Comment by jmikola** [comment]
For the record, I do not see "eval command is deprecated" messages in the server log when running the ['dataSize'](https://docs.mongodb.com/manual/reference/command/dataSize/) command on MongoDB 3.4 using the currently supported mongodb extension:

```php
<?php

$manager = new MongoDB\Driver\Manager;
$command = new MongoDB\Driver\Command([
    'dataSize' => 'test.foo',
    'keyPattern' => ['field' => 1],
    'min' => ['field' => 10],
    'max' => ['field' => 100]
]);
$cursor = $manager->executeCommand('test', $command);
var_dump($cursor->toArray());
```

The above script yields the following output:

```
array(1) {
  [0]=>
  object(stdClass)#5 (4) {
    ["size"]=>
    int(0)
    ["numObjects"]=>
    int(0)
    ["millis"]=>
    int(0)
    ["ok"]=>
    float(1)
  }
}
```

Additionally, we can see the following in the server logs when verbose logging is enabled, which tells us that we are running a `dataSize` command and not `eval`:

> 2017-03-01T10:10:13.980-0500 D COMMAND  [conn1] run command test.$cmd { dataSize: "test.foo", keyPattern: { field: 1 }, min: { field: 10 }, max: { field: 100 } }
> 2017-03-01T10:10:13.980-0500 I COMMAND  [conn1] command test.foo command: dataSize { dataSize: "test.foo", keyPattern: { field: 1 }, min: { field: 10 }, max: { field: 100 } } numYields:0 reslen:75 locks:{ Global: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_query 0ms

I used the driver directly in my example, but the relevant method in the MongoDB PHP library for executing an arbitrary command would be [`MongoDB\Database::command()`](https://docs.mongodb.com/php-library/master/reference/method/MongoDBDatabase-command/).
