### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by enleur** [mongodb/mongo-php-driver#537]
### Description

Mongodb extension holds peak memory after running a query

### Environment

```
PHP 7.1.1
mongodb 1.2.5
libbson bundled version => 1.5.4
libmongoc bundled version => 1.5.4
```

### Test Script

```
<?php

$loader = require __DIR__.'/../app/autoload.php';

$collection = (new \MongoDB\Client())->selectCollection('test', 'test');
//$collection->drop();
//
//$documents = [];
//
//for ($i = 0; $i < 1000000; $i++) {
//    $documents[] = ['a' => $i];
//}
//
//$collection->insertMany($documents);

echo memory_get_usage(true) . PHP_EOL; //10mb

$collection->find([], ['limit' => 50000])->toArray();
echo memory_get_usage(true) . PHP_EOL; //46mb

$collection->find([], ['limit' => 500000])->toArray();
echo memory_get_usage(true) . PHP_EOL; //396mb

$collection->find([], ['limit' => 50000])->toArray();
echo memory_get_usage(true) . PHP_EOL; //396mb why?
```

Related to https://github.com/mongodb/mongo-php-library/issues/318

**Comment by derickr** [comment]
I don't believe this has anything to do with the MongoDB driver, as PHP itself behaves exactly the same.

See this example:

```
<?php

function create_docs( $amount )
{
	$documents = [];

	for ($i = 0; $i < $amount; $i++) {
		$documents[] = ['a' => $i];
	}
}

echo memory_get_usage( true ), PHP_EOL;

$a = create_docs( 50000 );

echo memory_get_usage( true ), PHP_EOL;

$a = create_docs( 500000 );

echo memory_get_usage( true ), PHP_EOL;

$a = create_docs( 50000 );

echo memory_get_usage( true ), PHP_EOL;
```

Which outputs:

```
2097152
23068672
211812352
211812352
```

PHP does not return memory back to the operating system until its process ends, as is explained in https://bugs.php.net/bug.php?id=53669 by Rasmus at "[2011-04-12 18:48 UTC]".

**Comment by enleur** [comment]
@derickr thank you

**Comment by enleur** [comment]
@derickr why does it work on php 5.x? https://3v4l.org/2OVeU

**Comment by derickr** [comment]
Yeah, that's a very good question! Apparently in PHP 7, the memory manager has changed. There is now a gc_mem_caches() [function](https://3v4l.org/cLefK) that "solves" this, but I don't know what the drawbacks are. Let's see what happens at the PHP bug ticket.

**Comment by enleur** [comment]
gc_mem_caches() solves the problem. Thank you again @derickr !
