### ISSUE TITLE
Cannot find OpenSSL's <evp.h> 

### ISSUE THREAD

**Issue by ThomasDupont** [mongodb/mongo-php-driver#538]
### Description

Hello,

I'm trying to get the mongodb extension without succes

### Environment

PHP 7.1
OpenSSL 1.0.2

### Test Script

I tried to run this script:
```
sudo pecl install mongodb --configure --with-openssl-dir=/usr/local/opt/openssl
```

The result is Cannot find OpenSSL's <evp.h> 

```
ls -l /usr/local/opt/openssl
```

Result : /usr/local/opt/openssl -> ../Cellar/openssl/1.0.2k

How can I "force" the installation to take the valid path?

#EDIT

I by pass the issue with php71-mongodb of brew

**Comment by derickr** [comment]
I don't think PECL has --configure and --with-openssl-dir settings, you probably will do better by doing:

    pecl download mongodb
    tar -xvzf mongodb*tgz
    cd mongo*
    phpize
    ./configure  --with-openssl-dir=/usr/local/opt/openssl

Usually, PHP extensions require an installed version of a header file (and not pointed to the source), under the name ``include/evp.h`` in the path that you specify. In the case of OpenSSL, it actually looks for ``include/openssl/evp.h`` as part of PHP's build system. In your case, it then tries to use ``/usr/local/opt/openssl/include/openssl/evp.h`` — does that file exist?

**Comment by jrlmontejo** [comment]
In addition to the commands above, you need to run:
```
make
sudo make install
```

**Comment by jmikola** [comment]
Based on the edit in the OP, it looks like this was resolved by installing `php71-mongodb` with Homebrew.

While PECL doesn't support changing the OpenSSL path, we do suggest installing `pkg-config` in the [installation docs for PECL](http://php.net/manual/en/mongodb.installation.pecl.php). Failing that, the manual process @derickr shared above is the only other option if you need to pass a custom path to `./configure`.
