### ISSUE TITLE
I can't use MongoDB\Driver\Command to parse to Update command

### ISSUE THREAD

**Issue by GanLuo96214** [mongodb/mongo-php-driver#548]
### Description

I can't use MongoDB\Driver\Command to parse to Update command.

### Environment

Docker-centos
php-7 compile by self
mongo-php-driver 1.2.5  compile by self

### Test Script

```
<?php

       
        $cmd = [
            'update'=>'User_SplitA'

        ];
        $cmd = new \MongoDB\Driver\Command($cmd);

       error:The updates option is required to the update command.

//     I want update date by _id
       $cmd = [
            'update'=>'User_SplitA'
            ,'updates'=>[
                ['_id'=>'1']
                ,[
                    '$set'=>[
                        'a'=>'a'
                    ]
                ]
            ]
        ];
        $cmd = new \MongoDB\Driver\Command($cmd);

        error : Unrecognized field in update operation: _id 

```

### Expected and Actual Behavior

         $cmd = [
            'insert'=>'User_Transfer_Log'
            ,'documents'=>[
                [
                    "_id" => "152z8ncywib0"
                    ,"LogTime" => 1489044839
                    ,"message" => "152z8ncta5rl accept from 152z8ncl1wpv 499"
                    ,"transTag" => "152z8nd1qply"
                ]
            ]
        ];
        $cmd = new \MongoDB\Driver\Command($cmd);

like I use this code.

### Debug Log

where I can find the document about \MongoDB\Driver\Command.

**Comment by GanLuo96214** [comment]
can give me a example about how to update date?

**Comment by derickr** [comment]
The update command documentation is at https://docs.mongodb.com/manual/reference/command/update/

But I think you might be better off just using [MongoDB\Driver\BulkWrite](http://php.net/manual/en/class.mongodb-driver-bulkwrite.php) with [MongoDB\Driver\Manager::executeBulkWrite](http://php.net/manual/en/mongodb-driver-manager.executebulkwrite.php).

**Comment by GanLuo96214** [comment]
I just want update one document data.I think use bulkwrite will cost more than I use \MongoDB\Driver\Command and \MongoDB\Driver\execCommand. if there is no other way to use it then I will follow your suggestion.

**Comment by GanLuo96214** [comment]
and about document I mean the what should I give parameter to the  \MongoDB\Driver\Command when I want executeCommand do some stuff.

**Comment by derickr** [comment]
BulkWrite is the low-level interface for this in the driver, there is nothing else. The driver also abstracts certain variations of commands depending on different MongoDB versions, so I *strongly* recommend you use Driver\BulkWrite and Manager::executeBulkWrite.

**Comment by GanLuo96214** [comment]
thanks.

**Comment by jmikola** [comment]
@GanLuo96214: For the record, the error in your original post was passing arguments to the update operation (i.e. element in the command's `updates` array field) as an array instead of an object with `q` and `u` fields. This should be clear when comparing your PHP document to the syntax example in the [update command reference](https://docs.mongodb.com/manual/reference/command/update/#dbcmd.update).

**Comment by GanLuo96214** [comment]
@jmikola thanks, I found a lot place and didn't founded.
