### ISSUE TITLE
find() don't bring all documents

### ISSUE THREAD

**Issue by marcelosboeira** [mongodb/mongo-php-driver#572]
I used this: 

```
$collection  = $database->selectCollection("collection_name");
$result = $collection->find();`
```

and the result is: 
```
MongoDB\Driver\Cursor Object
(
    [cursor] => Array
        (
            [stamp] => 0
            [is_command] => 
            [sent] => 1
            [done] => 
            [end_of_event] => 
            [in_exhaust] => 
            [has_fields] => 
            [query] => stdClass Object
                (
                    [$orderby] => stdClass Object
                        (
                            [_id] => 1
                        )
                    [$query] => stdClass Object
                        (
                        )
                )
            [fields] => stdClass Object
                (
                )
            [read_preference] => Array
                (
                    [mode] => 1
                    [tags] => Array
                        (
                        )
                )
            [flags] => 0
            [skip] => 0
            [limit] => 0
            [count] => 1
            [batch_size] => 0
            [ns] => dbase.images
            [current_doc] => stdClass Object
                (
                    [_id] => MongoDB\BSON\ObjectID Object
                        (
                            [oid] => 58e25c6318c26033b3510ab1
                        )

                    [ui_name] => 6335ec41a03258fed94877e95295dcc9.jpg
                    [ui_title] => 
                    [ui_description] => 
                    [ui_use] => 1
                )

        )
    [server_id] => 1
)
```

So bring just one document.

But the collection have 3 documents. 

If I use the count() show me 3 documents

**Comment by jmikola** [comment]
The documentation for [`MongoDB\Collection::find()`](https://docs.mongodb.com/php-library/master/reference/method/MongoDBCollection-find/#examples) includes an example of executing a query and iterating on the returned [`MongoDB\Driver\Cursor`](http://php.net/class.mongodb-driver-cursor) object to obtain results.

In your code above, you appear to be dumping the `MongoDB\Driver\Cursor` object's internal state, which only presents the current document. The cursor is [`Traversable`](http://php.net/traversable), which means you can iterate it with `foreach` (or wrap it with an iterator) to yield the expected query results. Alternatively, you can use [`iterator_to_array()`](http://php.net/iterator_to_array) or [`MongoDB\Driver\Cursor::toArray()`](http://php.net/manual/en/mongodb-driver-cursor.toarray.php) to obtain _all_ of the cursor's results (across multiple batches) as a PHP array. This will come at the expense of memory allocation for the entire result set, which may be undesirable for large results.

**Comment by marcelosboeira** [comment]
Thanks!
