### ISSUE TITLE
php executable segfaults with extension=mongodb.so enabled.

### ISSUE THREAD

**Issue by janneman001** [mongodb/mongo-php-driver#600]
### Description
trying access mongo database with php 5.

however i cannot even start.
simplest like php -v segfaults

### Environment
openSUSE Leap 42.2
Linux 4.4.70-18.9-default
php5-5.6.30-4.5.x86_64
ext-mongodb 1.2.9
mongodb-server-3.4.3-9.1.x86_64

installed with: pecl install mongodb

php --ri mongodb

mongodb

MongoDB support => enabled
MongoDB extension version => 1.2.9
MongoDB extension stability => stable
libbson bundled version => 1.5.5
libmongoc bundled version => 1.5.5
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled

Directive => Local Value => Master Value
mongodb.debug => no value => no value
Segmentation fault (core dumped)

$ php -i | grep -E 'mongodb|libmongoc|libbson'

libbson bundled version => 1.5.5
libmongoc bundled version => 1.5.5
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
mongodb.debug => no value => no value
```
php -m
[PHP Modules]
Core
ctype
curl
date
dom
ereg
filter
gd
gettext
hash
iconv
json
libxml
mbstring
mhash
mongodb
mysql
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

Segmentation fault (core dumped)


### Test Script

php -v
PHP 5.6.30 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
Segmentation fault (core dumped)

### Expected and Actual Behavior

to be able to use mongo database from php

```
DEBUG OR BACKTRACE
```

### Debug Log

If the issue relates to internal driver behavior (e.g. connection issues),
please include a debug log. This may be generated by setting the `mongodb.debug`
INI option to "stderr" or a directory (useful for web SAPIs).

http://php.net/manual/en/mongodb.configuration.php#ini.mongodb.debug

```
DEBUG LOG
```

**Comment by janneman001** [comment]
pecl install log attached.
[peclinstall_log.txt](https://github.com/mongodb/mongo-php-driver/files/1064201/peclinstall_log.txt)
after that:
PHP 5.6.30 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
Segmentation fault (core dumped)
when removing line: extension=mongodb.so
from /etc/php5/cli/php.ini
php runs like before

**Comment by jmikola** [comment]
We would need backtrace to diagnose this. Please refer to [this guide](https://bugs.php.net/bugs-generating-backtrace.php) if you need assistance with that.

**Comment by janneman001** [comment]
i am not able to find a php 5.6.30-4.5 debuginfo. core will not be of much use.
Looks like i am not using a stock version of php for OpenSuSe .
I will revert to stock version and retry.

**Comment by janneman001** [comment]
Went back to php5-5.5.14-77.3.1.x86_64 which is stock in OpenSuSe Leap 42.2.
I can use mongodb-1.2.9 extension for php5 now. Thanks
