### ISSUE TITLE
PECL package for version 1.1.10 has wrong `md5hash` for `README-1.1`

### ISSUE THREAD

**Issue by deiga** [mongodb/mongo-php-driver#602]
### Description

Cannot install mongodb-1.1.10 on Alpine linux, because of wrong md5 checksum for file README-1.1

### Environment

Alpine Linux 3.6
PHP 7.1.4
Mongodb 1.1.10

**Comment by jmikola** [comment]
Thanks for the report. It looks like `package.xml` in [mongodb-1.1.10.tgz
](https://pecl.php.net/get/mongodb-1.1.10.tgz) reports an md5 checksum of `48dedfebdafe1d807b50d1b9cd76b580` for that file, when it should be `ba80f479ccd6213e7d0fd5a632ea7639`.

It looks like this is also reported when running `pecl install -f mongodb-1.1.10`, however, it doesn't abort the build process:

> warning : bad md5sum for file ~/bin/php-bin/php-7.0/lib/php/doc/mongodb/RELEASE-1.1

I'll consult with @derickr and see if there is an easy way to update the package in PECL.

**Comment by jmikola** [comment]
This should be fixed.
