### ISSUE TITLE
can't build with libbson version 1.7-dev

### ISSUE THREAD

**Issue by sgavrylenko** [mongodb/mongo-php-driver#605]
Hi
I try to build driver from sources (tag 1.2.9) manually and get next error
"make: *** No rule to make target '/tmp/build-php7.1-mongodb/mongodb-php-driver/src/libbson/src/yajl/yajl_alloc.c', needed by 'src/libbson/src/yajl/yajl_alloc.lo'.  Stop."

I find out that folder libbson/src/yajl/ exists in only versions before 1.6.0 (repo libbson). 
As I can see you bump libbson and libmongoc to 1.7.0-dev few months ago

How we can fix this issue?

**Comment by jmikola** [comment]
If you're building the 1.2.9 with bundled versions of libmongoc and libbson (the default), those libraries should be 1.5.5 as indicated by the git submodules. If you are building with shared libraries (controlled via `./configure` options), there should be no issue with newer versions of libmongoc and libbson.

Any bumps to libmongoc/libbson 1.7.0-dev were done in the master branch of the PHP extension, which is 1.3.0-dev.

**Comment by sgavrylenko** [comment]
Thanks for your answer!
