### ISSUE TITLE
Large log files named "PHONGO-XXXXXXXXXXXXXXXX" are saved to /tmp folder

### ISSUE THREAD

**Issue by maorpolak** [mongodb/mongo-php-driver#620]
On a Linux server running Apache, whenever the Mongo database is queried, large log files (up to tens of MB each) are saved to the /tmp folder. This quickly amounts to GBs of data.

An example file name is:
PHONGO-15015049117JzoqP

The queries are made through a PHP application using the Laravel framework and the [laravel-mongo](https://github.com/jenssegers/laravel-mongodb) library.

I believe it's the Mongo PHP driver that's creating these log files. Is it possible to disable this logging, and if so, how?

Thanks in advance,

Maor

**Comment by jmikola** [comment]
These logs are generated by the [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php) INI directive. Logging can be disabled by setting the option to an empty string (its default value) or [several other special strings](https://github.com/mongodb/mongo-php-driver/blob/1.2.9/php_phongo.c#L1771) (i.e. "0", "off", "no", "false").

If enabled (i.e. "1", "on", "yes", "true"), log files are created in the system temp directory (i.e. `sys_get_temp_dir()`). Alternatively, the option could be set to a specific file path or output stream ("stderr" or "stdout").

**Comment by maorpolak** [comment]
Hi @jmikola,

I actually tried this before. I edited the php.ini file located in /etc/php/7.0/apache2/, adding the following line:
mongodb.debug=""

I then restarted the Apache service, but the log files were still being created.

Am I editing the wrong file?

**Comment by jmikola** [comment]
I expect you are either editing the wrong INI file (possibly for a different PHP environment) or the INI setting is being overwritten by either another INI file loaded after `php.ini` or during runtime via [`ini_set()`](http://php.net/manual/en/function.ini-set.php).

Alternatively, I would suggest examining `ini_get('mongodb.debug')` and/or `phpinfo()` output from your application to confirm that value of `mongodb.debug` at runtime.

**Comment by maorpolak** [comment]
Thank you @jmikola, I'll give it a try.
