### ISSUE TITLE
MongoDB-Drive for PHP throws errors

### ISSUE THREAD

**Issue by HansGlueck** [mongodb/mongo-php-driver#636]
### Description
Hi,

we have a small project (only 1000 rows in collections) using MongoDB with PHP. Since we put this project onine and getting
traffic on, we have the following error in our logs and some (not all) queries (writes and reads) won't work anymore:

Error-Messages in php-fpm log:
"Connection reset by peer"
"Pattern contain null bytes" (over SOAP-Request of our project to mongo)

Error-Messages in MongoDB log:
".. closing client connection: 9001 socket exception .."

In the error situation we are always observing a "Pattern cannot contain null bytes" Exception which seems to be thrown from Regex.c in line 50:
https://github.com/mongodb/mongo-php-driver/blob/master/src/BSON/Regex.c

But when tracing our network traffic we did not find any null bytes polluting the request.

After reloading the php-fpm, everything is fine for a couple of days. Seems to be the more traffic we
have the smaller the time slot is, till the next error is poping up.

Our first setup of the MongoDB was a replication cluster with 3 Nodes. One primary and 2 secondary. 
Writes and reads against the primary node:

'uri_options' => ['readPreference' => 'primaryPreferred']

We also tried a single node (new server setup), but with the same result.

We debugged the error to the line of the Mongo-Libary-Class:
mongodb/mongodb/src/Operation/InsertOne.php Line: 79
" ..
 $insertedId = $bulk->insert($this->document);
.. "

Hopefully with some advices for us.

Cheers
 HansGlueck

### Environment

Our setup:
PHP 5.6.30-0+deb8u1 (cli)
MongoDB-Server 3.4

MongoDB-Client 1.2.9 PHP-Modul

Libary-Classes:
"name": "mongodb/mongodb",
"version": "1.0.2",
"description": "MongoDB driver library",

### Debug Log

Error-Messages in php-fpm log:
"Connection reset by peer"
"Pattern contain null bytes" (over SOAP-Request of our project to mongo)

Error-Messages in MongoDB log:
".. closing client connection: 9001 socket exception .."

**Comment by jmikola** [comment]
Thanks for diving into the extension code to trace the source of the exception.

`php_phongo_regex_init()` could be called via the following methods:

 * `MongoDB\BSON\Regex::__construct()`
 * `MongoDB\BSON\Regex::__set_state()`
 * `MongoDB\BSON\Regex::unserialize()`

Can you provide a full backtrace for the exception? Additionally, if you're able to reliable reproduce this, can you provide the offending pattern string?

It seems unlikely that the exception would originate at [`MongoDB\Operation\InsertOne::execute()`](https://github.com/mongodb/mongo-php-library/blob/1.0.2/src/Operation/InsertOne.php#L79), as the library would not be initializing a `MongoDB\BSON\Regex` object at that point. If anything, we might be serializing a `MongoDB\BSON\Regex` to BSON if the document you were inserting happened to contain a Regex object (also unlikely, as that BSON type is generally used for querying but not storage).

Also, while I don't think it's related to the error, I'll note that the most recent stable version of the library is 1.1.2 and you're using 1.0.2.

**Comment by HansGlueck** [comment]
Thanks for your answer. We will update the libary to 1.1.2 and try to debug to get the string.

We will provide you then with more informations.

**Comment by HansGlueck** [comment]
Hi,

first of all, thanks for waiting for our response. It took a while till we figured out what went wrong exactly.
We have updated the libary with the result that nothing have changed.

The basic problem was that we somehow got an ISO-8859-1 coded string with a german umlaut sent to the webpage. This resolved in a "data mess" since we expect UTF-8. The datamess was then sent to the driver, who then laid down his work.

If you need any further details to make some adjustments just let me know.

Regards,

HansGlueck

**Comment by jmikola** [comment]
> The basic problem was that we somehow got an ISO-8859-1 coded string with a german umlaut sent to the webpage. This resolved in a "data mess" since we expect UTF-8. The datamess was then sent to the driver, who then laid down his work.

Was this string being used to construct a Regex object? You never did provide the full exception backtrace and offending input string, which I'd need to investigate further.

If you'd still like to share the input string, I'd suggest providing the raw bytes as hex string (e.g. [`bin2hex`](http://php.net/manual/en/function.bin2hex.php)) to avoid any change it may be mangled through the comment form.

I'm not a character set expert by any means, but ISO-8859-1 is a single-byte format. It's still not clear to me how an umlaut would be related to the PHP string containing a null byte, which would then trigger [this condition in `php_phongo_regex_init()`](https://github.com/mongodb/mongo-php-driver/blob/1.2.9/src/BSON/Regex.c#L62).

**Comment by HansGlueck** [comment]
Sorry for our late answer,
yes we put the Umlauts in Regex and yes it was broken. We are sorry that we could not reconstruct the exact bytes.

**Comment by jmikola** [comment]
I just whipped up a test using umlaut characters from ISO-8859-1 to demonstrate how these interact with the driver's regex methods:

```php
<?php

require 'vendor/autoload.php';

$str = '!"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ';
$escapedStr = preg_quote($str);

echo "Initialize with __construct()\n";
$constructedRegex = new MongoDB\BSON\Regex($escapedStr);
var_dump($constructedRegex);

echo "\nInitialize with unserialize()\n";
$unserializedRegex = unserialize(serialize($constructedRegex));
var_dump($unserializedRegex);

echo "\nInitialize with __set_state()\n";
$setStateRegex = MongoDB\BSON\Regex::__set_state(['pattern' => $escapedStr, 'flags' => '']);
var_dump($setStateRegex);

echo "\nRound-trip through database collection\n";
$collection = (new MongoDB\Client)->test->foo;
$collection->drop();
$collection->insertOne(['x' => $str]);
var_dump($collection->findOne(['x' => $constructedRegex]));
```

The output of this script should resemble:

```
Initialize with __construct()
object(MongoDB\BSON\Regex)#3 (2) {
  ["pattern"]=>
  string(303) "\!"#\$%&\(\)\*\+,\-\./0123456789\:;\<\=\>\?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\[\\\]\^_`abcdefghijklmnopqrstuvwxyz\{\|\}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ"
  ["flags"]=>
  string(0) ""
}

Initialize with unserialize()
object(MongoDB\BSON\Regex)#2 (2) {
  ["pattern"]=>
  string(303) "\!"#\$%&\(\)\*\+,\-\./0123456789\:;\<\=\>\?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\[\\\]\^_`abcdefghijklmnopqrstuvwxyz\{\|\}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ"
  ["flags"]=>
  string(0) ""
}

Initialize with __set_state()
object(MongoDB\BSON\Regex)#4 (2) {
  ["pattern"]=>
  string(303) "\!"#\$%&\(\)\*\+,\-\./0123456789\:;\<\=\>\?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\[\\\]\^_`abcdefghijklmnopqrstuvwxyz\{\|\}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ"
  ["flags"]=>
  string(0) ""
}

Round-trip through database collection
object(MongoDB\Model\BSONDocument)#17 (1) {
  ["storage":"ArrayObject":private]=>
  array(2) {
    ["_id"]=>
    object(MongoDB\BSON\ObjectId)#16 (1) {
      ["oid"]=>
      string(24) "59f1fb1b6118fd1c1c348f52"
    }
    ["x"]=>
    string(283) "!"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ"
  }
}
```

Looking at the [Regex.c](https://github.com/mongodb/mongo-php-driver/blob/master/src/BSON/Regex.c) file you linked, the "null byte" error is thrown when `strlen()`, which stops at the first null byte, does not equal the length reported by PHP through [`Z_STRLEN()`](https://github.com/php/php-src/blob/php-5.6.30/Zend/zend_operators.h#L445) (noting that PHP strings can absolutely contain null bytes). I know that PHP may be configured to support multi-byte strings and [`mbstring.func_overload`](http://php.net/manual/en/mbstring.configuration.php#ini.mbstring.func-overload) may even overload PHP's core functions such as `strlen()` (note this is different than the C `strlen()` we call in `Regex.c`), but I don't _think_ that would change the length on the internal zvals and the behavior macros such as `Z_STRLEN()`. That said, I don't think `mbstring` would apply at all for ISO-8859-1, which is a single-byte character set.

Without the original bytes that caused the exception and a full stack trace, I'm afraid we can't progress any further on this. Feel free to follow up if this issue pops up again in your application and you're able to capture such information.

**Comment by HansGlueck** [comment]
Did you wrote your test with UTF-8 "Umlauts"? 
If yes may be you could try to test the "Umlauts" in ISO-8859-1 by using mb_convert_encoding()?

**Comment by derickr** [comment]
I've tried this as well, and made sure I saved @jmikola's test file in the iso8859-1 encoding:

```
derick@singlemalt:/tmp/636 $ file test.php
test.php: PHP script, ISO-8859 text
```

When I run this, I get following (expected) output — as MongoDB can't do anything besides non-UTF8 for strings:

```
Fatal error: Uncaught MongoDB\Driver\Exception\UnexpectedValueException: Detected invalid UTF-8 for fieldname "x": !"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~����������������������������������������������������������������������������������������������� in /tmp/636/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 103

MongoDB\Driver\Exception\UnexpectedValueException: Detected invalid UTF-8 for fieldname "x": !"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~����������������������������������������������������������������������������������������������� in /tmp/636/vendor/mongodb/mongodb/src/Operation/InsertOne.php on line 103

Call Stack:
    0.0004          0   1. {main}() /tmp/636/test.php:0
    0.0162          0   2. MongoDB\Collection->insertOne($document = array ('x' => '!"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~�����������������������������������������������������������������������������������������������'), $options = ???) /tmp/636/test.php:23
    0.0175          0   3. MongoDB\Operation\InsertOne->execute($server = class MongoDB\Driver\Server { public $host = '127.0.0.1'; public $port = 27017; public $type = 1; public $is_primary = FALSE; public $is_secondary = FALSE; public $is_arbiter = FALSE; public $is_hidden = FALSE; public $is_passive = FALSE; public $last_is_master = array ('ismaster' => TRUE, 'maxBsonObjectSize' => 16777216, 'maxMessageSizeBytes' => 48000000, 'maxWriteBatchSize' => 1000, 'localTime' => class MongoDB\BSON\UTCDateTime { ... }, 'maxWireVersion' => 5, 'minWireVersion' => 0, 'readOnly' => FALSE, 'ok' => 1); public $round_trip_time = 0 }) /tmp/636/vendor/mongodb/mongodb/src/Collection.php:795
    0.0176          0   4. MongoDB\Driver\BulkWrite->insert(array ('x' => '!"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~�����������������������������������������������������������������������������������������������')) /tmp/636/vendor/mongodb/mongodb/src/Operation/InsertOne.php:103
```

(My display is set to UTF-8, so hence the �'s).

However, besides this expected error, there are no other errors, warnings, crashes, or warnings when run this through valgrind.

I tested this with mongodb/mongodb 1.3.2 and PHP 7.2, and mongodb/mongodb 1.3.0-dev and PHP 5.6, which both had a similar output.

I think that, unless you can provide a standalone code snippet that produces the error, we should close this report.
