### ISSUE TITLE
Connection URI parameter parsing

### ISSUE THREAD

**Issue by foospidy** [mongodb/mongo-php-driver#664]
### Description

Connection URIs with query parameters are not parsed properly. Example connection string:

mongodb://dbuser:dbpass@host1:port1,host2:port2/dbname?replicaSet=rs-ds123456

This results in the driver attempting to execute commands against the database name `dbname?replicaSet=rs-ds123456`, rather than just `dbname`.

Example error message in logs:
`Unauthorized: not authorized on dbname?replicaSet=rs-ds123456`

My understanding is that the replicaSet option is an official MongoDB connection URI option and should be supported.

### Environment

```
PHP 7.1.10 (cli) (built: Sep 30 2017 10:04:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.10, Copyright (c) 1999-2017, by Zend Technologies

MongoDB support => enabled
MongoDB extension version => 1.3.0
MongoDB extension stability => stable
libbson bundled version => 1.8.0
libmongoc bundled version => 1.8.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled

libbson bundled version => 1.8.0
libmongoc bundled version => 1.8.0
mongodb.debug => no value => no value
```
Please let me know if you need more info. Thanks!

**Comment by jmikola** [comment]
URI parsing is handled by libmongoc, so I'll see if I can reproduce this in 1.8.0 (based on the bundled version in use) and follow up when I can.

According to the [connection string specification](https://github.com/mongodb/specifications/blob/master/source/connection-string/connection-string-spec.rst), the driver should certainly pick up everything between the forward slash and question mark as the [auth database](https://github.com/mongodb/specifications/blob/master/source/connection-string/connection-string-spec.rst#auth-database-optional). Everything following the question mark should get parsed as a query string. If that's not happening, it could indicate a bug in the URI parsing.

As an immediate workaround, you should be able to remove the auth database component from the URI string and use the [`authSource`](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource) query string parameter instead.

**Comment by derickr** [comment]
@foospidy — is this still a problem for you?

**Comment by foospidy** [comment]
It appears to be working for me now. Thanks!
