### ISSUE TITLE
php mongodb connect pool

### ISSUE THREAD

**Issue by fancyecommerce** [mongodb/mongo-php-driver#688]
doc ： https://github.com/mongodb/mongo-php-driver/issues
```
For details on supported options, see
 » Connection String Options in the MongoDB manual. 
» Connection pool options are not supported, as the PHP driver does not implement connection pools.
```

mongodb doc: https://docs.mongodb.com/manual/reference/connection-string/#connection-pool-options

ask:

1. php mongodb default connection pool is 100, or 1 ？

2. How do I implement a connection pool in php?

**Comment by jmikola** [comment]
> 1. php mongodb default connection pool is 100, or 1 ？
> 2. How do I implement a connection pool in php?

The PHP driver uses [libmongoc](https://github.com/mongodb/mongo-c-driver)'s single-threaded client mode, which does not implement connection pools. There is also no way to implement your own connection pooling using this driver.

Each single-threaded libmongoc client object maintains at most one socket connection per `mongod` or `mongos` server. The relationship between `MongoDB\Driver\Manager` objects and libmongoc client objects is discussed in [Connection Handling](
http://php.net/manual/en/mongodb.connection-handling.php) in the driver documentation.
