### ISSUE TITLE
Retrieve microseconds from UTCDateTime

### ISSUE THREAD

**Issue by Jean85** [mongodb/mongo-php-driver#689]
It would be great if `$date->toDateTime()` would return a DateTime instance with microseconds too. Right now, the test comments says:

https://github.com/mongodb/mongo-php-driver/blob/e6e9d7b3de2ba64f5551c6bede94387f53fa73f0/tests/bson/bson-utcdatetime-todatetime-002.phpt#L2

But, in reality, the test expects something ending with 3 zeroes, so no microseconds...

https://github.com/mongodb/mongo-php-driver/blob/e6e9d7b3de2ba64f5551c6bede94387f53fa73f0/tests/bson/bson-utcdatetime-todatetime-002.phpt#L15-L17

Is there anything that prevents it?

**Comment by derickr** [comment]
MongoDB's UTCDateTime data type only does millisecond resolution, and not microseconds which PHP can support. So this seems like expected behaviour.

Let me know if I misunderstood you :-)

**Comment by Jean85** [comment]
Yes, I was missing that piece of info, thanks.

I was having issues when writing tests for the mapping to-from Mongo. Maybe it's better for me to convert to UTCDateTime before comparing in tests, so I will "lose" precision consistently.

Thanks!
