### ISSUE TITLE
count

### ISSUE THREAD

**Issue by frogRen** [mongodb/mongo-php-driver#695]
$query = [];
$query['_id']['$lt'] = new \MongoDB\BSON\ObjectID('5a2a72bc41fa3c54a42b3dcc');

find($query);
0.002s

count($query);
7.25s ?

**Comment by derickr** [comment]
From the little information you provided:

- ``find()`` only returns a cursor object, and doesn't usually run a query.
- ``count()`` needs to run the query, read all the required documents on disk, and then return the result.

The latter will therefore likely take that much more time.
