### ISSUE TITLE
Package "mongodb" Version "1.3.4" does not have REST xml available

### ISSUE THREAD

**Issue by pjebs** [mongodb/mongo-php-driver#708]
My dockerfile has been working perfectly for weeks but today the same script fails at this point:

```
FROM php:7.2-fpm-alpine3.6

...


RUN pecl install mongodb \               <--------- Fails here
    && pecl install grpc \ 
    && pecl install protobuf
RUN docker-php-ext-enable mongodb grpc opcache protobuf gmp
```

Error outut:

"Package "mongodb" Version "1.3.4" does not have REST xml available"

**Comment by jmikola** [comment]
Around the same time you opened this issue, it looks like [folks in r/php](https://www.reddit.com/r/PHP/comments/7k9ctm/is_pecl_down_for_everyone/) where also discussing PECL being unavailable. There is also a [php-webmaster thread](http://news.php.net/php.webmaster/26643) on the issue. I was just able to successfully install the driver through PECL, so I assume this has been resolved.

Note that while we publish the MongoDB driver package through PECL, we have no control over its infrastructure. If you having problems connecting to PECL in the future, please utilize one of the [PHP.net support channels](http://www.php.net/support.php). Quoting that page:

> If you have a problem or suggestion in connection with the PHP.net website or mirror sites, please [contact the webmasters](http://php.net/contact.php).

**Comment by ndrvieira** [comment]
I was able to fix this problem adding DNS values to docker engine settings:
![image](https://user-images.githubusercontent.com/49926281/163755586-6ed364ef-e582-43c9-982f-405bca86b513.png)
