### ISSUE TITLE
missing ) in parenthetical when performing mapreduce

### ISSUE THREAD

**Issue by JonasSFreire** [mongodb/mongo-php-driver#716]
### Description
Updating to a 3.4.10 mongodb server hosted in atlas and we started to have this exception when performing a mapreduce: 
 ```
SyntaxError: missing ) in parenthetical @:10:13
```
I've searched for something that may had changed in the 3.4.10 version and found [this](https://jira.mongodb.org/browse/SERVER-30009), as this issue in jira describes, now the map and reduce parameters need to be actual javascript code or MongoDB\BSON\Javascript instances instead of strings with the javascript code, but our implementations that are throwing the exception already uses the Javascript class and executing the command in mongoshell works fine too, so maybe this is an problem between the php driver communicating with the server.

Can someone help me understanding what am i doing wrong or find out if this is a problem with the driver

### Environment

i'm using php 7.1 running in docker 
MongoDB extension version 1.3.4
libmongoc version 1.8.2
libbson version 1.8.2

### Test Script
The original scripts are running with Phalcon odm, but i've tested using only the mongodb library and the same error occurs, guess that will be more simple to understand without the Phalcon stuff 

```
<?php
use MongoDB\Driver\Manager;
use MongoDB\BSON\Javascript;
use MongoDB\Driver\Command;

$mongo = new Manager('mongodb://user:pass@3.4.10-server');

$map = new Javascript(
    "function() {
        total = parseInt(0);
        for(i in this.tickets) {
            type = this.tickets[i];
            if (9999 == type.guestTypeId) {
                total += parseInt(type.quantity);
            }
        }
        emit(type.guestTypeId, total);
    };"
);

$reduce = new Javascript(
    "function(key, quantity) {
        return Array.sum(quantity);
    };"
);

$cmd = new Command([
    "mapreduce" => "cart",
    "map" => $map,
    "reduce" => $reduce,
    "query" => [
            'userId' => 999,
            '$or' => [
                [
                    'saleStatus' => 'approved'
                ]
            ]
    ],
    "out" => ['inline' => 1]
]);

$result = $mongo->executeCommand('ingresse', $cmd);
var_dump($result->toArray());
```
the same code above running in a 2.6 version runs fine, to test this script you will need to change the map function and the query paramater

**Comment by jmikola** [comment]
I was able to reproduce the same error locally on a 3.4.10 server and traced the error back to the trailing semicolon in your function definitions. This is mentioned in [this comment from SERVER-30009](https://jira.mongodb.org/browse/SERVER-30009?focusedCommentId=1628346&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1628346) and the ensuing fix in https://github.com/mongodb/mongo/commit/8024561b6a73b5b0b56200bdfa3233219ff7fb18. By removing the trailing semicolon from the strings used to construct the `$map` and `$reduce` objects, I was able to execute your script successfully.

Based on that, I see no evidence that the PHP driver is doing anything wrong here, as the BSON Javascript type was created with the exact string provided to it.
