### ISSUE TITLE
uncaught error: class 'mongo' not found

### ISSUE THREAD

**Issue by DoNotSpamPls** [mongodb/mongo-php-driver#717]
### Description
NGINX keeps returning this error: FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Mongo' not found

### Environment

OS: Ubuntu 16.04 LTS Server x64
PHP Version: 7.1
MongoDB version: 3.0
php -i output: https://hastebin.com/fexukejixo.coffeescript
php -m output:
```
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mongodb
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```
grep output:
```
mongodb
libbson bundled version => 1.8.2
libmongoc bundled version => 1.8.2
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
mongodb.debug => no value => no value
```

(the MongoDB server is running in a Docker container)

**Comment by DoNotSpamPls** [comment]
fixed by switching to php 5

**Comment by jmikola** [comment]
For the record, the [Mongo] class](http://php.net/manual/en/class.mongo.php) is from the legacy `mongo` extension, and the environment you shared `php -i` output for only had the `mongodb` extension loaded.
