### ISSUE TITLE
It's possible to provide ability to disable persistence connection?

### ISSUE THREAD

**Issue by lichunqiang** [mongodb/mongo-php-driver#732]
### Description

Related #393 

After research about the default behavior of persistence connection, I known that this is default implementation of the driver.

But just like the issue mentioned, It's really needed to add a new feature, that can disable persistence connection by modify configuration.

Thanks.

**Comment by lichunqiang** [comment]
I had found this: https://github.com/yuri0229/mongodb-php-driver-dpc

But i'm not sure that if it is can reliable

**Comment by jmikola** [comment]
[yuri0229/mongodb-php-driver-dpc](https://github.com/yuri0229/mongodb-php-driver-dpc) is a community-authored fork of the driver that was inspired by my comments in https://github.com/mongodb/mongo-php-driver/issues/564#issuecomment-296087949. I can't speak to its reliability or correctness. Note that it is trailing behind the current progress in this repository.

That said, my comments in https://github.com/mongodb/mongo-php-driver/issues/564#issuecomment-296087949 should still be accurate. Connection persistence can be disabled building the driver with the following modifications:

 1. moving the initializing of the `pclients` hash table from `GINIT` ([here](https://github.com/mongodb/mongo-php-driver/blob/1.4.0beta1/php_phongo.c#L2652)) to `RINIT`
 2. moving the destruction of the `pclients` hash table from `MSHUTDOWN` ([here](https://github.com/mongodb/mongo-php-driver/blob/1.4.0beta1/php_phongo.c#L2652)) to `RSHUTDOWN`.

At present, we've no plans to implement any functionality that would allow users to disable the persistent connection behavior at runtime.

**Comment by lichunqiang** [comment]
Thanks for your reply.

But I think the library should be open, let's the end user to choose the behavior what they want.
Just like [php-memcached-dev/php-memcached](https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini#L37), the user can configurate it via php.ini .

Finally, Best regards. and thank you again.

**Comment by sameer1750** [comment]
> That said, my comments in [#564 (comment)](https://github.com/mongodb/mongo-php-driver/issues/564#issuecomment-296087949) should still be accurate. Connection persistence can be disabled building the driver with the following modifications:
> 
> 1. moving the initializing of the `pclients` hash table from `GINIT` ([here](https://github.com/mongodb/mongo-php-driver/blob/1.4.0beta1/php_phongo.c#L2652)) to `RINIT`
> 2. moving the destruction of the `pclients` hash table from `MSHUTDOWN` ([here](https://github.com/mongodb/mongo-php-driver/blob/1.4.0beta1/php_phongo.c#L2652)) to `RSHUTDOWN`.

What exactly should be changed in the code can you please elaborate.
