### ISSUE TITLE
MongoDB 3.6 Support

### ISSUE THREAD

**Issue by eman1986** [mongodb/mongo-php-driver#745]
according to your website (https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#php-driver-compatibility) the PHP library only support 3.4, but 3.6 has been out for a while and looks like every other language has ben updated to support 3.6, any timetable on when PHP will see this?

**Comment by derickr** [comment]
We released RC1 of the driver this week (https://github.com/mongodb/mongo-php-driver/releases/tag/1.4.0RC1), and expect the 1.4.0 release to come out early next week with full MongoDB 3.6 support.
