### ISSUE TITLE
fatal error: 'sasl/sasl.h' file not found

### ISSUE THREAD

**Issue by rjma30** [mongodb/mongo-php-driver#756]
Hello,

Getting error below on FreeBSD 11 when install mongodb driver using pecl.

```
c/src/mongoc/ -I/tmp/pear/mongodb/src/libbson/src/ -I/tmp/pear/mongodb/src/libbson/src/jsonsl/ -I/tmp/pear/mongodb/src/libbson/src/bson/ -DHAVE_CONFIG_H -g -O2 -D_THREAD_SAFE -pthread -c /tmp/pear/mongodb/src/libmongoc/src/mongoc/mongoc-cluster-cyrus.c  -fPIC -DPIC -o src/libmongoc/src/mongoc/.libs/mongoc-cluster-cyrus.o
In file included from /tmp/pear/mongodb/src/libmongoc/src/mongoc/mongoc-cluster-cyrus.c:21:
/tmp/pear/mongodb/src/libmongoc/src/mongoc/mongoc-cyrus-private.h:28:10: fatal error: 'sasl/sasl.h' file not found
#include <sasl/sasl.h>
         ^~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /tmp/pear/pear-build-toordHPlAL/mongodb-1.4.0
ERROR: `make' failed
```

**Comment by jmikola** [comment]
Can you share the full output from `configure`? Additionally, the first line in your paste appears to have been cut off and starts with the end of an include path. Please share that entire line, which should begin with the compiler command (e.g. `gcc`, `cc`).

`mongoc-cyrus-private.h`, which attempts to include `sasl/sasl.h`, is itself only included if `MONGOC_ENABLE_SASL_CYRUS` is defined as `1`. We initialize it to `0` and only assign `1` if libsasl is found during `configure` time (see: [`config.m4`](https://github.com/mongodb/mongo-php-driver/blob/1.4.0/config.m4#L355)).

**Comment by rjma30** [comment]
Hello, I've attached the complete output. Thanks!

[mongodb driver installation.txt](https://github.com/mongodb/mongo-php-driver/files/1726649/mongodb.driver.installation.txt)

**Comment by jmikola** [comment]
I believe I've diagnosed the cause of this in [PHPC-1124](https://jira.mongodb.org/browse/PHPC-1124). If possible, would you mind attempting to compile the driver from source with my patch in https://github.com/mongodb/mongo-php-driver/pull/759 to see if that resolves it? Instructions for doing so can be found in [CONTRIBUTING.md](https://github.com/mongodb/mongo-php-driver/blob/master/CONTRIBUTING.md#building-from-source), and you can certainly unpack the PECL archive instead of cloning the repository.

**Comment by rjma30** [comment]
Your patch has resolved it! Thanks jmikola! Appreciate your help!

**Comment by jmikola** [comment]
Good to hear. We can leave this closed. Feel free to follow [PHPC-1124](https://jira.mongodb.org/browse/PHPC-1124) for further updates.
