### ISSUE TITLE
Type error: Argument 3 passed to MongoDB\Driver\Server::executeQuery() must be an instance of MongoDB\Driver\ReadPreference or null, array given

### ISSUE THREAD

**Issue by krimia** [mongodb/mongo-php-driver#757]
After upgrading from mongodb/mongodb 1.2.0 to mongodb/mongodb 1.3.0, i have an issue with the 3th argument of executeQuery() that is now waiting for an object and not an array. 

Can you explaine or fixe this issue ?

### Environment

My environment is PHP 7.1.13 and symfony 3.4

**Comment by jmikola** [comment]
[`MongoDB\Driver\Server::executeQuery()`](http://php.net/manual/en/mongodb-driver-server.executequery.php) supports an options array as its third argument in 1.4.0+.

PHP library 1.3.0 updated its dependency on `ext-mongodb` to [1.4.0](https://pecl.php.net/package/mongodb/1.4.0). If you're using Composer, this requirement should already be checked (see: [`composer.json`](https://github.com/mongodb/mongo-php-library/blob/1.3.0/composer.json#L16)) unless you're disabling platform checks with `--ignore-platform-reqs`, which you should not be doing. The [release notes](https://github.com/mongodb/mongo-php-library/releases/tag/1.3.0) also mentioned the bump to `ext-mongodb` 1.4.0.

**Comment by krimia** [comment]
Thank's but i can't use "ext-mongodb": "^1.4.0" on composer require and i'm not using --ignore-platform-reqs.

I'm using alcaeus/mongo-php-adapter and this error still with mongodb/mongodb 1.3.0.

I resolved this issue by downgading to mongodb/mongodb 1.2.0

maybe mongo-php-adapter issue !

**Comment by jmikola** [comment]
> i can't use "ext-mongodb": "^1.4.0" on composer require

Composer is not capable of install extensions. You would need to ensure the appropriate extension version is installed and loaded in `php.ini`. See: http://php.net/manual/en/mongodb.installation.php

> I'm using alcaeus/mongo-php-adapter and this error still with mongodb/mongodb 1.3.0. I resolved this issue by downgading to mongodb/mongodb 1.2.0. maybe mongo-php-adapter issue !

Looking at [mongo-php-adapter's `composer.json`](https://github.com/alcaeus/mongo-php-adapter/blob/master/composer.json), it doesn't look like that is to blame. The adapter library merely requires version 1.2.0+ of the extension and version 1.0.1+ of the library. With those requirements alone, Composer is capable of selecting the latest version of `mongodb/mongodb` given the version of `ext-mongodb` available. In the absence of a newer extension, it should just try older versions of `mongodb/mongodb` until all dependencies are satisfied. I expect that you're only hitting this error after manually requiring `mongodb/mongodb` 1.3.0 in your own `composer.json` file (or as an indirect dependency through some other library).

In any event, I would suggest you upgrade the extension instead of downgrading the library.

**Comment by krimia** [comment]
Thank you jmikola.

mongodb extention is already installed and is the same as the released version 1.4.0 using pecl php.

I'm waiting until all dependencies are satisfied ;)

**Comment by jmikola** [comment]
> mongodb extention is already installed and is the same as the released version 1.4.0 using pecl php.

Did upgrading the extension to 1.4.0 resolve the original error?

If not, you may have multiple versions of the extension installed (e.g. CLI environment may have 1.4.0, but web SAPI could still be using 1.3.x). Please use `phpversion('mongodb')` or `phpinfo()` from the appropriate environment to confirm.

**Comment by krimia** [comment]
**This is the stdout of pecl search commande :**

Matched packages, channel pecl.php.net:
=======================================
Package Stable/(Latest) Local
mongo   1.6.16 (stable)       MongoDB database driver
mongodb 1.4.0 (stable)  1.4.0 MongoDB driver for PHP

**And this is the stout of $ php --ri mongodb | grep version and $ phpversion('mongodb') **
MongoDB extension version => 1.4.0
libbson bundled version => 1.9.2
libmongoc bundled version => 1.9.2

I don't think i have a multiple versions of the extension

**Comment by krimia** [comment]
Well done, the web CLI still using MongoDB extension version | 1.3.4

how can i update de CLI web php extention ?

**Comment by krimia** [comment]
**The problem is resolved.** 

My apache server dont rebuild automatically so when i restart it every thing is alrigth and the php mongo extension is now 1.4.0

> $ service httpd restart

Thank for help ;)

**Comment by ChristophAnastasiades** [comment]
Is there any way to install ext-mongodb version 1.4.0 using homebrew or do we need to use pecl? When I do `brew install php71-mongodb` it will install ext-mongodb version 1.3.4.

**Comment by krimia** [comment]
In my case, i'm using "pecl install mongodb" to install or "pecl upgrade mongodb" to upgrade.

otherwase, try "composer update" and if updating to 14.0, then restart mongo and apache (it was my case)

**Comment by alcaeus** [comment]
> Is there any way to install ext-mongodb version 1.4.0 using homebrew

There's https://github.com/Homebrew/homebrew-php/pull/4765 to update the `ext-mongodb` formula to 1.4.0.

**Comment by derickr** [comment]
@Tera3yte — that compile error is unrelated to this issue. I can reproduce it if the ``zlib1g-dev`` package isn't installed, so I have created https://jira.mongodb.org/browse/PHPC-1124 — please track the issue there. Installing ``zlib1g-dev`` inside your docker container should provide a workaround.
