### ISSUE TITLE
Convert a MongoDB code with MongoDB\Driver\Manager

### ISSUE THREAD

**Issue by Pim92** [mongodb/mongo-php-driver#758]
Hello, 

Web development beginner, I'm trying to convert a code to access MongoDB using MongoDB\Driver\Manager, but have some difficulties. Indeed, this new driver seems to me a little bit low-level compared to the previous one so it can be a bit complicated to work with...

```
$mongoConn = new MongoClient("mongodb://localhost:27017");
$mongoDB = $mongoConn->selectDataBase(dbname1);//dbname2 exists too
...
$index = new MongoDBIndexation($mongoDB);//our class for using
```

If it is ok that I must begin with:

`$mongoConn = new MongoDB\Driver\Manager("mongodb://localhost:27017");`

How to continue with $mongoDB, please?

And what are the equivalents of:

```
$collection->remove
$collection->save and
$collection->findOne ?
```

Thanks in advance

**Comment by jmikola** [comment]
> Indeed, this new driver seems to me a little bit low-level compared to the previous one so it can be a bit complicated to work with...

The low-level nature of the extension is discussed in the introductory paragraphs of its [PHP.net documentation](http://php.net/mongodb). The design of the current driver is split between the low-level [`mongodb` extension](https://pecl.php.net/package/mongodb) and a [PHP library](https://github.com/mongodb/mongo-php-library) (i.e. `mongodb/mongodb` Composer package). The reasons for this design are discussed in the [Architecture Overview](http://php.net/manual/en/mongodb.overview.php) article, and there is also a [tutorial for using the library](http://php.net/manual/en/mongodb.tutorial.library.php) in the extension's documentation. Actual documentation fo the library is available at: https://docs.mongodb.com/php-library/current/

In the MongoDB manual's own section on the [PHP driver](https://docs.mongodb.com/ecosystem/drivers/php/), we also discuss the relationship between the extension and library, differences from the legacy `mongo` extension, and link out to the documentation for all projects.

May I ask what documentation you were reading where you read about the extension API but were not made aware of the library. If you only viewed specific API references on PHP.net (e.g. [`MongoDB\Driver\Manager::__construct()`](http://php.net/manual/en/mongodb-driver-manager.construct.php), I can see how you would have missed this; however, we did try to ensure that all gateway pages in the documentation sources above discuss the extension _and_ library.

> what are the equivalents of:
>
> ```php
> $collection->remove
> $collection->save and
> $collection->findOne
> ```

The library's [Upgrade Guide](https://docs.mongodb.com/php-library/current/upgrade/) walks through differences between the legacy `mongo` extension's API and the current extension/library APIs. I would suggest reading through that, and then looking through the various [tutorials](https://docs.mongodb.com/php-library/current/tutorial/). From there, you can consult the library's API references as needed.
