### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by 727023460** [mongodb/mongo-php-driver#775]
os : centos 6
php version: 7.1.7
when I exec command:
`make`
 error log:

/usr/local/src/mongo-php-driver-legacy/php_mongo.c: In function ‘php_mongo_trigger_error_on_gle’:
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:708: warning: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type
/usr/local/include/php/Zend/zend_hash.h:161: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:708: error: too many arguments to function ‘zend_hash_find’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:716: warning: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type
/usr/local/include/php/Zend/zend_hash.h:161: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:716: error: too many arguments to function ‘zend_hash_find’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:717: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/include/php/Zend/zend_types.h:331: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:717: warning: passing argument 1 of ‘convert_to_long’ from incompatible pointer type
/usr/local/include/php/Zend/zend_operators.h:254: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:724: warning: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type
/usr/local/include/php/Zend/zend_hash.h:161: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:724: error: too many arguments to function ‘zend_hash_find’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:736: error: too many arguments to function ‘zend_hash_copy’
/usr/local/src/mongo-php-driver-legacy/php_mongo.c:738: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/include/php/Zend/zend_variables.h:100: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
make: *** [php_mongo.lo] Error 1

**Comment by kayoshi** [comment]
same for me =(

**Comment by jmikola** [comment]
The errors above appear to come from attempting to compile the [legacy `mongo` extension](http://php.net/mongo) (repository: [mongo-php-driver-legacy](https://github.com/mongodb/mongo-php-driver-legacy)) with PHP 7.

PHP 7 is only supported by the newer [`mongodb` extension](http://php.net/mongodb) (this repository) since version 1.1.1 (related issue: [PHPC-285](https://jira.mongodb.org/browse/PHPC-285)).

**Comment by kayoshi** [comment]
Yeah, got it.  Thanks. I was trying to install zabbix..gonna compile it on my own
