### ISSUE TITLE
Install extension  mongodb on php 7 .Wampserver

### ISSUE THREAD

**Issue by pedramham** [mongodb/mongo-php-driver#782]
I'm trying to install **mongodb-1.4.2** for php 7.0.10 .I have tow version php on wampserver php 5.6.25 & php 7.0.10 .I can install mongodb-1.4.2 for php 5.6.25 but i can not do that for php 7.0.10.
[link download driver](https://pecl.php.net/package/mongodb/1.4.2/windows)
**I do these :**

> 
> **1**-Download .dll file from PEAR Directory, please make sure .dll file must be compatible with your PHP version
> Put downloaded .dll file into your PHP extension (\ext) directory, mine xampp location is (C:\wamp64\bin\php\php7.0.10\ext\)
> 
> **2**-Enable php_mongo.dll extension from you php.ini file, php.ini , Open file and search 'extension=php_mongo.dll', if found remove semi-colon ';' otherwise add 'extension=php_mongo.dll' line to enable mongoDB extension for PHP
> 
> **3**-Restart Wamp server,if you will get error ‘mondo dll file can not found’ that means your .dll file is not compatible with your PHP version
> 
> **4**-After successful installation, please open your php_info file and search mongo if you found mongo as a module that’s mean you have successfully installed mongoDB driver on your wamp
> 
>

**Comment by pedramham** [comment]
I have a mistake.With the newer version of **MongoDB**, add the following line to your php.ini file
`extension=php_mongodb.dll`
**_Instead_**
`extension=php_mongo.dll`

**Comment by pedramham** [comment]
I wonder . I can see mongodbl installed, when i run phpinfo .But when run  php -m i have not it on result.How i can enable extension mongodb

**Comment by jmikola** [comment]
Each PHP runtime (e.g. CLI environment, web SAPI) likely has its own `php.ini` file.

The [`php_ini_loaded_file()`](http://php.net/manual/en/function.php-ini-loaded-file.php) and [`php_ini_scanned_files()`](http://php.net/manual/en/function.php-ini-scanned-files.php) functions can be used to determine which INI files are being loaded by a particular PHP process. That information should also appear in `phpinfo()` output.

**Comment by pedramham** [comment]
Hi.Thank you.really I am confused.I'm trying to install mongodb-1.4.2 for php 7.0.10 ,yes you say right i have extension mongodb on list php info.but when i run php -m i have not it on list.

I try to install mongo-php-adapter but i have error .((plz check this [issue](https://github.com/alcaeus/mongo-php-adapter/issues/225)))

**Comment by jmikola** [comment]
Closing this, as the related issue (https://github.com/alcaeus/mongo-php-adapter/issues/225) also appears to be resolved. If that's not the case, feel free to re-open and respond to my last comment.
