### ISSUE TITLE
Ability to use dot and dollar sign in keys, at least in embed documents

### ISSUE THREAD

**Issue by Zaporozhec7** [mongodb/mongo-php-driver#790]
### Description

Since mongodb version 3.6 allowed using dots and dollar sign in field names.

Links:
    - https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names
    - https://jira.mongodb.org/browse/SERVER-30575?_ga=2.98954334.1306211417.1522492322-1121716355.1521387154 

But when i trying insert document with keys containing dots in embed document, I have next exception thrown:

**invalid document for insert: keys cannot contain "."**

In file **src/Operation/InsertOne.php** on line **103**.

### Environment

Mongodb version: 3.6
PHP version: 7.1.15
Mongo PHP driver version: 1.4.2

libbson bundled version => 1.9.3
libmongoc bundled version => 1.9.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
mongodb.debug => no value => no value

### Expected and Actual Behavior

Expected to be able insert document without errors, since have Mongodb version 3.6 which allow to use dots in field names.

Actually got exception: **invalid document for insert: keys cannot contain "."**

**Comment by jmikola** [comment]
Per the [Restrictions on Field Names documentation](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names) that you linked:

> Although valid, avoid using . or $ in field names since querying on such fields is not yet functional.

MongoDB 3.6 may support this at the storage layer, but it currently has no support for querying fields that contain dot and dollar sign characters. There are no plans to relax the current restriction in drivers until the server implements an escaping mechanism (likely [SERVER-30575](https://jira.mongodb.org/browse/SERVER-30575)).

**Comment by jmikola** [comment]
Closing this, as I don't believe there's anything to discuss at this point, nor do we have any driver tickets to cross-reference. I would suggest following [SERVER-30575](https://jira.mongodb.org/browse/SERVER-30575) for further updates, as I expect that will end up linked to drivers tickets when the time comes.
