### ISSUE TITLE
How to use one connection to connect to the server multiple times

### ISSUE THREAD

**Issue by Rulovescoding** [mongodb/mongo-php-driver#794]
### Description

Like the title, I am wandering how to use the same connection for multiple php files.

I am trying to write a frontend that can get information from backend, and the clients can decide whether they want to update their information. If they update, overwrite the old information with the new one. And I am using two php files, one is getInfo.php, and another one is updateInfo.php. At the beginning of each file, it is creating a new MongoDB\Client() before checking $_POST[]. 

I am going to put these php files on local server, and all clients send their request to this local server. It will be approximately 400 clients. Since I notice that there is no close() function for mongoDB. Will the number of connection exceed the limit? How should I improve this?

**Comment by jmikola** [comment]
See [Connection Handling](http://php.net/manual/en/mongodb.connection-handling.php) for details about how the driver persist connections. In summary, constructing a `MongoDB\Driver\Manager` (either directly or through the library's Client class) will create a libmongoc client object, which contains all of our connections. That libmongoc client is persisted for the duration of the PHP process (e.g. PHP-FPM worker) and will be reused by subsequent `MongoDB\Driver\Manager` objects constructed with the same arguments.

While the server does allow incoming connections to be limited via a [`maxConns`](https://docs.mongodb.com/manual/reference/program/mongod/#cmdoption-mongod-maxconns) option, I believe the default behavior is limited only by operating system (e.g. file descriptor or other resource limits). If you're using [MongoDB Atlas](https://www.mongodb.com/cloud/atlas), its connection limits will vary depending on the instance size.

**Comment by Rulovescoding** [comment]
Correct me if I misunderstand it.

So basically, if I get two php file
getInfo.php
```
$client = new MongoDB\Client(...);

if(isset($_GET["ID"])){
  $cursor = $client-><DATABASE>-><COLLECTION>->findOne(...);
  echo json_encode($cursor);
}
```
update.php
```
$client = new MongoDB\Client(...);

if(isset($_GET["ID"])){
  $cursor = $client-><DATABASE>-><COLLECTION>->updateOne(...);
}
```
It will use the same connection, without any specification in my code. Coz the mongoDB server does that for me as long as I keep the argument("..." part in "new MongoDB\Client(...)" ) always be same. Right?

**Comment by jmikola** [comment]
> It will use the same connection, without any specification in my code. The mongoDB server does that for me as long as I keep the argument("..." part in "new MongoDB\Client(...)" ) always be the same.

Technically, the MongoDB driver is doing this, not the server :)

Other than that, you're understanding correctly. So long as the arguments to `MongoDB\Client::__construct()` are the same in both scripts, each will be able to use the same persisted libmongoc client and its connections. The first time we see a unique set of constructor arguments in a PHP process (e.g. CLI process, or FPM worker), a libmongoc client will be created and associated with those arguments. Future instances of the same constructor arguments will then re-use the previously persisted libmongoc client.

**Comment by jmikola** [comment]
Closing this, as I believe my last comment explains the original question. Feel free to re-open this issue if that's not the case.
