### ISSUE TITLE
MongoDB driver  not working for OSX High Sierra

### ISSUE THREAD

**Issue by chaipipatP** [mongodb/mongo-php-driver#822]
```
## $php -i
mongodb
MongoDB support => enabled
MongoDB extension version => 1.5.0-dev
MongoDB extension stability => devel
libbson bundled version => 1.9.4
libmongoc bundled version => 1.9.4
libmongoc SSL => enabled
libmongoc SSL library => Secure Transport
libmongoc crypto => enabled
libmongoc crypto library => Common Crypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
```

But mongodb is not show in phpinfo.

php 7.1.16, mongodb driver 1.4.3

**Comment by derickr** [comment]
There are usually two different php.ini files — one for CLI (used for ``php -i``) and one for use with the web server. On the CLI you can check which files are loaded with ``php --ini``, and in the web server it shows up in the top of ``phpinfo()`` as something like: 

```
Loaded Configuration File | /usr/local/php/7.0dev/lib/php.ini
Scan this dir for additional .ini files | (none)
Additional .ini files parsed | (none)
```

You need to make sure that ``extension=mongodb.so`` is present in both.

**Comment by chaipipatP** [comment]
## $which php
/Applications/XAMPP/xamppfiles/bin/php

## $php --ini
Configuration File (php.ini) Path: /Applications/XAMPP/xamppfiles/etc
Loaded Configuration File:         /Applications/XAMPP/xamppfiles/etc/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

## $grep extension_dir=  `which php-config`
extension_dir='/Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20160303'

## $ls /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20160303
mongodb.so	opcache.a	opcache.so	pdo_dblib.a	pdo_dblib.so	pgsql.a		pgsql.so

**Comment by derickr** [comment]
Those are again on the command line, where you said things worked. You didn't show that `` /Applications/XAMPP/xamppfiles/etc/php.ini`` contains a ``extension=mongodb.so`` line though, which is also required.

For seeing what gets loaded for running PHP through the webserver, you need to use ``phpinfo()`` in a ``.php`` file, and see what the values are

**Comment by hoatv** [comment]
Hi chaipipatP are you find out solution for this, I've stuck with this for days

**Comment by abinhho** [comment]
I have same. I am using PHP 7.1.11, MacOS and XAMPP
Anybody can help?

**Comment by abinhho** [comment]
@chaipipatP Did you resolve your problems?

**Comment by jmikola** [comment]
Repeating @derickr's comment above:

> For seeing what gets loaded for running PHP through the webserver, you need to use ``phpinfo()`` in a ``.php`` file, and see what the values are

We're still awaiting output of `phpinfo()` from the web SAPI.

All we've seen above is that:

 * The `mongodb` extension _is_ loaded in the CLI environment
 * The CLI environment's INI file is `/Applications/XAMPP/xamppfiles/etc/php.ini`
 * `/Applications/XAMPP/xamppfiles/etc/php.ini` contains `extension=mongodb.so`

We do not know what INI file is being used by the web SAPI.

Lastly, `which php` output did indicate that XAMPP's `php` binary was being used for the CLI environment. I would also stress the importance of ensuring that the `pecl` binary used to install the extension also comes from XAMPP. That should be easily checked by examining the output of `which pecl`. By using the correct `pecl` binary, we'll also ensure that the extension is built for the correct version of PHP (in the event multiple versions exist on the same system).

**Comment by erwinsetiawan** [comment]
I have same issue here, mongodb appear on php -i

but didn't appear on phpinfo(); 

How to solve this?

**Comment by erwinsetiawan** [comment]
Here from phpinfo()


```
Server API | Apache 2.0 Handler
-- | --
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /Applications/XAMPP/xamppfiles/etc
Loaded Configuration File | /Applications/XAMPP/xamppfiles/etc/php.ini
Scan this dir for additional .ini files | (none)
```

here from php -i 
```
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /Applications/XAMPP/xamppfiles/etc
Loaded Configuration File => /Applications/XAMPP/xamppfiles/etc/php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
```

here from php --ini
```
Configuration File (php.ini) Path: /Applications/XAMPP/xamppfiles/etc
Loaded Configuration File:         /Applications/XAMPP/xamppfiles/etc/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

```

**Comment by abinhho** [comment]
@erwinsetiawan Before I used Xamp on MacOs, I tried a lot but could not resolve this problem. I sugget you use MAMP instead, It'll work for you.

**Comment by jmikola** [comment]
@erwinsetiawan: See @derickr's reply in https://github.com/mongodb/mongo-php-driver/issues/883#issuecomment-406298524.

> Before I used Xamp on MacOs, I tried a lot but could not resolve this problem. I sugget you use MAMP instead, It'll work for you.

@abinhho: We've had users report installation issues with XAMPP and MAMP alike. The common thread appears to be people confusing their PHP environments (e.g. `pecl` command, `php.ini` files) and mixing up CLI and web SAPIs for the same PHP installation (common `pecl` command, but separate INI files).

**Comment by erwinsetiawan** [comment]
@jmikola ok got it, may bad forget with composer. But the first thing is seem like issue when install on xampp, i have check it have sama cli for phpinfo php -i like my comment above. I have already double check it that it used same php.ini file.

@abinhho: thanks for suggets will try to using mamp instead xampp.

**Comment by erwinsetiawan** [comment]
@abinhho Thanks for your suggest it working for me on mamp. Cheers.

**Comment by jmikola** [comment]
I was able to borrow a MacBook with High Sierra and walked through the conflict with XAMPP in https://github.com/mongodb/mongo-php-driver/issues/883#issuecomment-406707863.

@chaipipatP: If you're still following this issue, please walk through my steps and confirm that you encountered the same issuing with PHP attempting to `dlopen()` the `mongodb.so` file as reported in XAMPP's PHP error log.

For anyone else following, I'll concede that @abinhho's suggestion to use MAMP is well founded. XAMPP's [VM for Mac](https://www.apachefriends.org/blog/new_xampp_20170628.html) builds might also be suitable, as they run PHP within a Linux VM. That said, I think the best solution is still installing PHP via Homebrew, especially since most users will already be using Homebrew to install other build dependencies, such as `autoconf` or shared libraries (for the MongoDB driver and/or other PHP extensions).

**Comment by jmikola** [comment]
Closing this, as it ultimately appeared to be an issue with XAMPP's PHP environment, and the alternative solutions required either using their VM-based environment or something else entirely (e.g. PHP installed via Homebrew).
