### ISSUE TITLE
How to select distinct in mongo-php-driver?

### ISSUE THREAD

**Issue by chaipipatP** [mongodb/mongo-php-driver#832]
How to select distinct in mongo-php-driver?
[](https://docs.mongodb.com/manual/reference/method/db.collection.distinct/)

**Comment by jmikola** [comment]
Closing this as a duplicate of https://github.com/mongodb/mongo-php-library/issues/535. Please do not open duplicate issues in both the driver and library projects. We monitor both projects for activity.
