### ISSUE TITLE
Driver update affected insert keys with restricted characters

### ISSUE THREAD

**Issue by KinaneD** [mongodb/mongo-php-driver#844]
### Description
Previously we used to use the 1.2.2 driver with the latest Mongodb version (3.6.4). We were able to store nested keys with `.` characters, but of course were not able to read these keys, which is expected.

We recently updated to the 1.4.3 driver, suddenly keys containing restricted characters could not be stored anymore.

Docs states that restricted characters are allowed in nested objects:
https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

We got the following error:
`MongoDB\Driver\Exception\InvalidArgumentException with message 'invalid document for insert: keys cannot contain ".": "U.13-17"'`

File: `../vendor/mongodb/mongodb/src/Operation/InsertOne.php`
Code: `22`
Line: `96`

### Environment

Running on Debian Jessie, and php version 5.6.

### Test Script

```php
$data = [
                    "platform_id" => "abdhtq4-jki7r",
                    "username" => "@whatever",
                    "content_fetched_at" => "2018-06-10 00:00:00",
                    "data" => [
                        [
                            "name" => "post_video_view_time_by_age_bucket_and_gender",
                            "period" => "lifetime",
                            "values" => [
                                [
                                    "value" => [
                                        "U.13-17" => 15502,
                                        "U.18-24" => 430,
                                        "U.25-34" => 626289,
                                        "U.35-44" => 1367384,
                                        "U.45-54" => 1074571,
                                        "U.55-64" => 228672,
                                        "U.65+" => 410714,
                                        "F.13-17" => 1512734,
                                        "F.18-24" => 23389144,
                                        "F.25-34" => 95186348,
                                        "F.35-44" => 73298624,
                                        "F.45-54" => 30345809,
                                        "F.55-64" => 12638183,
                                        "F.65+" => 7908184,
                                        "M.13-17" => 290850,
                                        "M.18-24" => 7888689,
                                        "M.25-34" => 43292843,
                                        "M.35-44" => 37026402,
                                        "M.45-54" => 17478033,
                                        "M.55-64" => 8723529,
                                        "M.65+" => 4878373
                                    ]
                                ]
                            ],
                            "title" => "Lifetime Video View Time (in MS) by Top Audience",
                            "description" => "Lifetime video view time (in MS) by Top Audience (Age and Gender).",
                            "id" => "345624562456_54276584679846363\/insights\/post_video_view_time_by_age_bucket_and_gender\/lifetime"
                        ],
                    ]
         ];

$this->db->$collection->insertOne($data);
```

Thank you.

**Comment by jmikola** [comment]
Please see my responses in https://github.com/mongodb/mongo-php-driver/issues/790.

To summarize: although various versions of server will insert documents with such field names, the restriction on such field names was not lifted until 3.6 (according to the [manual](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names)). Despite this change to the manual, MongoDB drivers officially do not support inserting such field names, and likely will not until some future version of the server implements an escaping scheme ([SERVER-30575](https://jira.mongodb.org/browse/SERVER-30575)).

The reason you did not encounter that error in older versions of the PHP driver is that [libmongoc](https://github.com/mongodb/mongo-c-driver) did not start enforcing the restriction until 1.6.0 ([CDRIVER-1341](https://jira.mongodb.org/browse/CDRIVER-1341)). PHP driver 1.2.x was still using libmongoc 1.5.x. This exception would have first appeared in PHP driver 1.3.x when we bumped to libmongoc 1.8.x.

**Comment by derickr** [comment]
Closing this, as no further communication occurred.
