### ISSUE TITLE
`pecl install mongodb` fails on Cygwin (64-bit)

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mongodb/mongo-php-driver#848]
### Description

Trying to install the mongodb extension through Cygwin (64-bit, not tested 32-bit) using `pecl install mongodb` and it fails with the following errors:
```
src/libmongoc/src/mongoc/.libs/mongoc-client.o: In function `_mongoc_get_rr_search':
/tmp/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-client.c:413: undefined reference to `__ns_initparse'
/tmp/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-client.c:413:(.text+0xeb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__ns_initparse'
/tmp/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-client.c:430: undefined reference to `__ns_parserr'
/tmp/mongodb-1.4.3/src/libmongoc/src/mongoc/mongoc-client.c:430:(.text+0x148): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__ns_parserr'
collect2: error: ld returned 1 exit status
make: *** [Makefile:619: mongodb.la] Error 1
```

### Environment

`PHP 7.1.16` from Cygwin's setup 'package manager'.

### Expected and Actual Behavior

Expected it to compile, but it doesn't.

I can get `make` to 'succeed' by including `-l/usr/lib/resolv.a` (`pecl download mongodb` etc and then manually edit the `Makefile`), but it outputs only two files and no dll:
```
/tmp/mongodb-1.4.3 [1] $ ls modules/
mongodb.a  mongodb.la
```

The `mongodb.a` doesn't appear to be a dll format either, so it's not just a name thing.

**Comment by derickr** [comment]
Hi!

We do not support Cygwin installs of PHP, as it is not part of PHP's standard mode of [distribution for Windows](https://windows.php.net/download/).

Binaries for each release are automatically built, and end up on the [PECL package page](https://pecl.php.net/package/mongodb) where you can download them.

If you want to build the binaries yourself, please refer to the [build instructions](https://github.com/mongodb/mongo-php-driver/blob/master/CONTRIBUTING.md#ensure-windows-compatibility) on our Contributing page.

cheers,
Derick
