### ISSUE TITLE
Can not install Mongo PHP Driver on MacOS, XAMPP (any versions)

### ISSUE THREAD

**Issue by abinhho** [mongodb/mongo-php-driver#853]
### Description

I need to use mongodb on my project and tried to install php driver to use mongoDB php library. Im install using `sudo /Applications/XAMPP/bin/pecl install mongodb` and successful but:

When I check php in command line as: `php -i | grep mongo`, it's shown 
```
$ php -i | grep mongo
mongodb
libmongoc bundled version => 1.9.4
libmongoc SSL => enabled
libmongoc SSL library => Secure Transport
libmongoc crypto => enabled
libmongoc crypto library => Common Crypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
mongodb.debug => no value => no value
```
Then I check web browse used: `echo phpinfo()` => mongodb not shown up as well.

Im added `extension="mongodb.so"` into `/Applications/XAMPP/xamppfiles/etc/php.ini` and in web browse is the same `ini` file.

Then I tried to install other version XAMPP such as XAMPP 5.6.30, 7.0.30, 7.1.18, 7.2.6 and got same thing. Mongodb just shown in command line but phpinfo() is not.

Any body can help?

**Comment by jmikola** [comment]
[`php_ini_loaded_file()`](http://php.net/manual/en/function.php-ini-loaded-file.php) and `phpinfo()` should both report the path of the `php.ini` file loaded by the running PHP process. I expect you have different `php.ini` files for your CLI environment and web SAPI, and `extension=mongodb.so` was only added to one of them (the CLI environment's INI file).

This seems related to https://github.com/mongodb/mongo-php-driver/issues/822. See that issue for more discussion on checking `php.ini`.

**Comment by abinhho** [comment]
@jmikola Thanks for your answered. I tried a lots and decide to use MAMP instead !
