### ISSUE TITLE
"The SCRAM_SHA_1 authentication mechanism requires libmongoc built with ENABLE_SSL"

### ISSUE THREAD

**Issue by wxpan** [mongodb/mongo-php-driver#869]
```
"The SCRAM_SHA_1 authentication mechanism requires libmongoc built with ENABLE_SSL"
```

**Comment by jmikola** [comment]
There is not nearly enough information about your PHP environment to diagnose this. In the future, please do not ignore the [new issue template](https://github.com/mongodb/mongo-php-driver/issues/new).

That said, this is not a bug. [SCRAM-SHA-1 authentication requires a crypto library](https://github.com/mongodb/mongo-c-driver/blob/1.11.0/src/libmongoc/src/mongoc/mongoc-cluster.c#L1367) and will raise this error if one is not available. The [PECL installation docs](http://php.net/manual/en/mongodb.installation.pecl.php) discusses how best to proceed if the driver cannot find an SSL library at build time.

**Comment by jmikola** [comment]
The discussion in https://github.com/doctrine/DoctrineMongoDBBundle/issues/450 may also help.

**Comment by wxpan** [comment]
@jmikola Thank you for helping me！
