### ISSUE TITLE
How to you install this right.

### ISSUE THREAD

**Issue by qvs5010** [mongodb/mongo-php-driver#878]
Hi 

Regardless what is do i keep getting this following...

```
[root@io modules]# pecl install mongodb
downloading mongodb-1.5.1.tgz ...
Starting to download mongodb-1.5.1.tgz (1,053,197 bytes)
.............................done: 1,053,197 bytes
could not extract the package.xml file from "/tmp/pear/download/mongodb-1.5.1.tgz"
Download of "pecl/mongodb" succeeded, but it is not a valid package archive
Error: cannot download "pecl/mongodb"
Download failed
install failed

```

How do you install the php driver?

pecl install mongodb not working.

**Comment by jmikola** [comment]
I attempted to reproduce this locally with `pecl install -f mongodb` (forcing as I already had the extension installed) but encountered no problem. It's possible that the file was corrupted while you were downloading it.

To diagnose this, you can run `pecl download mongodb` and inspect the archive yourself and confirm that it does contain a `package.xml` file. If it helps, the archive should have the following SHA256 digest:

```
$ sha256sum mongodb-1.5.1.tgz 
1f62497625266aa5a7cb21f0e2fa4921300150aaf69bda296c5abb275c941569  mongodb-1.5.1.tgz
```

Alternatively, you can attempt to download the archive from our [GitHub releases](https://github.com/mongodb/mongo-php-driver/releases) and then install with PECL using a local archive. Consider:

```
$ wget https://github.com/mongodb/mongo-php-driver/releases/download/1.5.1/mongodb-1.5.1.tgz

...

2018-07-16 16:44:17 (9.75 MB/s) - ‘mongodb-1.5.1.tgz’ saved [1053197/1053197]

$ pecl install -f mongodb-1.5.1.tgz 
423 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /tmp/pear/temp/pear-build-jmikoladOdO2T/mongodb-1.5.1

...

Build process completed successfully
Installing '/home/jmikola/bin/php-bin/php-7.0/lib/php/extensions/debug-non-zts-20151012/mongodb.so'
install ok: channel://pecl.php.net/mongodb-1.5.1
configuration option "php_ini" is not set to php.ini location
You should add "extension=mongodb.so" to php.ini
```

**Comment by derickr** [comment]
We are closing this ticket as we think that there was no problem here. Please feel free to reopen with more information if that was not the case.
