### ISSUE TITLE
Problem to parse URI of mongoDB Atlas using PHP

### ISSUE THREAD

**Issue by rainyPoseidon** [mongodb/mongo-php-driver#884]
### Description

I'm having this problem when i tried to parse URI MongoDB atlas using PHP code.Any solution for this?
Below are the result i get when i tried to parse it.

P/S: I already changed the User n Password to the correct one.

```
 Uncaught MongoDB\Driver\Exception\InvalidArgumentException: Failed to parse MongoDB URI: 'mongodb://User:Password@mycluster0-shard-00-00.mongodb.net:27017,mycluster0-shard-00-01.mongodb.net:27017,mycluster0-shard-00-02.mongodb.net:27017/admin?ssl=true&replicaSet=Mycluster0-shard-0&authSource=admin&serverSelectionTryOnce=false&serverSelectionTimeoutMS=15000"'. Unsupported value for "serverSelectionTimeoutMS": "15000"".
```

**Comment by derickr** [comment]
I think you have an extra ```"``` in your URL, as the error message stays that the value for ``serverSelectionTimeoutMS`` is ``15000"`` (notice the extra ```"```).

**Comment by derickr** [comment]
Closing this out, as we think you made a typo in the connection string. Please feel free to reopen if that wasn't the case.
