### ISSUE TITLE
Using $near filter returns all data

### ISSUE THREAD

**Issue by fiere210** [mongodb/mongo-php-driver#912]
### Description

Hi, i'm new to MongoDB.
I have a collection with a coordinates field (and a 2sphere index) like this

```
"id" => $id,
"name" => $name,
"location" => [
     "type" => "Point",
     "coordinates" => [ $lon, $lat ]
]
```

I try to get all the documents near a certain point using the $near operator like this

```
   $filter = [
        'location' => [
          '$near' => [
            '$geometry' => [
              'type' => 'point',
              'coordinates' => [ $lon, $lat ],
              '$maxDistance' => $maxDistance,
              '$minDistance' => 0,
            ]
          ]
        ]
      ];

   $cursor = $collection->find( $filter );
```

But instead I get all the documents.

I tried this same query in the Mongo console and it works as expected

```
db.data.find(
        {
          location: {
            $near: {
              $geometry: {
                type: "point", 
                coordinates: [-72.589593333333, -38.74071]
              }, 
              $maxDistance: 500, 
              $minDistance: 0
            }
          }
        }
      )
```
The other filters that I'm using work fine (single fields, $gte, $lte).

Any help is appreciated. Thank you

### Environment

Ubuntu 16 Server
PHP Version 7.0.30-0ubuntu0.16.04.1
MongoDB v4.0.1
MongoDB extension version | 1.5.2
MongoDB extension stability | stable
libbson bundled version | 1.12.0
libmongoc bundled version | 1.12.0
libmongoc SSL | enabled
libmongoc SSL library | OpenSSL
libmongoc crypto | enabled
libmongoc crypto library | libcrypto
libmongoc crypto system profile | disabled
libmongoc SASL | disabled
libmongoc ICU | disabled
libmongoc compression | enabled
libmongoc compression snappy | disabled
libmongoc compression zlib | enabled

**Comment by derickr** [comment]
In the PHP example you have these distance options *in* the geometry:

```
              '$maxDistance' => $maxDistance,
              '$minDistance' => 0,
```

In the Shell example, you have them outside the *geometry* field. The latter (the shell), is correct.

Could you try this instead:

```
   $filter = [
        'location' => [
          '$near' => [
            '$geometry' => [
              'type' => 'point',
              'coordinates' => [ $lon, $lat ],
            ]
            '$maxDistance' => $maxDistance,
            '$minDistance' => 0,
          ]
        ]
      ];

   $cursor = $collection->find( $filter );
```

I also believe it would be wise to use ``Point`` instead of ``point``.

cheers,
Derick

**Comment by derickr** [comment]
No problem! Closing this.

**Comment by ziyaindia** [comment]
Hi Derickr,

One of my code line was 

`$GMONGO->getAMRecordCursor($tid, array('timestamp' => array('$gte' => $stimestamp, '$lte' => $etimestamp)), false);`

I changed it by following way:

`$GMONGO->getAMRecordCursor($tid, array('timestamp' => array('$gt' => $stimestamp, '$lt' => $etimestamp)), false);`

Replaced `$gte` by `$gt` & `$lte` by `$lt`

Which one is correct and what is the difference between them?

Thanks in Advance

**Comment by jmikola** [comment]
@ziyaindia: Please refrain from adding comments to issues that are long since closed, particularly when the question has no relation to the original discussion. The operators you're asking about are covered in the [Comparison Query Operators](https://docs.mongodb.com/manual/reference/operator/query-comparison/) documentation within the MongoDB server manual. Furthermore, questions about MongoDB's query language and general usage (since this does not appear specific to the PHP driver) would be better suited for the [MongoDB Developer Community Forums](https://developer.mongodb.com/community/forums/).
