### ISSUE TITLE
Fixes for openssl without pkg-config were not merge to 1.5 branch

### ISSUE THREAD

**Issue by DaveRandom** [mongodb/mongo-php-driver#916]
The fixes that came out of #875 were not merged down to the 1.5 branch and are not present in 1.5.2. Specifically the last 3 commits shown [here](https://github.com/mongodb/mongo-php-driver/commits/master/scripts/autotools/libmongoc/CheckSSL.m4) are not present [here](https://github.com/mongodb/mongo-php-driver/commits/v1.5/scripts/autotools/libmongoc/CheckSSL.m4).

**Comment by DaveRandom** [comment]
OK no worries, if I just take a branch based on 1.5 and cherry-pick the commits and PR that is that what you need?

**Comment by derickr** [comment]
Hi,

I think that should work — I don't expect any conflicts. It'd be great if you could use ``PHPC-1241: OpenSSL 1.1 not found if pkg-config is not available`` as commit message.

cheers,
Derick
