### ISSUE TITLE
How to use new MongoDB class with PHP using windows

### ISSUE THREAD

**Issue by joel2011140** [mongodb/mongo-php-driver#922]
Hi i'm trying to use this : $db = new MongoDB\Client("mongodb://localhost:27017");, to connect to my db but when I go to browser just to see something , always appears the message Class MongoDB not found ,is it something that I can do to get out of there ?

**Comment by derickr** [comment]
Hi Joel,

You need to install the PHP Library through Composer as well. The Composer library implements all the nice interfaces and builds on top of the low-level driver. You can find information on how to install the Composer library at https://docs.mongodb.com/php-library/current/tutorial/install-php-library/ Information on the architecture is at http://php.net/manual/en/mongodb.overview.php

cheers,
Derick

**Comment by derickr** [comment]
Closing as no further questions were posed.
