### ISSUE TITLE
mongo-php-driver does not show up in phpinfo()

### ISSUE THREAD

**Issue by imrannazirbhat** [mongodb/mongo-php-driver#939]
### Description

mongo-php extension does not show up in phpinfo(). The extension did got installed successfully and added to php.ini as well.  

### Environment

macOS Mojave - 10.14
php 7.1.19
MongoDB 3.6

Can anyone help!! What am I missing??

Thanks!

**Comment by moderndeveloperllc** [comment]
@imrannazirbhat How do you know it was installed successfully? What does `php --ri mongodb` tell you? Or `pecl list`? Are you using `homebrew` or other package manager on macOS?

**Comment by imrannazirbhat** [comment]
Thanks for your reply. I did installed it with pecl.

Here is the response for your mentioned commands:


System24-PC-2:~ imran$ php --ri mongodb

mongodb

MongoDB support => enabled
MongoDB extension version => 1.4.0
MongoDB extension stability => stable
libbson bundled version => 1.9.2
libmongoc bundled version => 1.9.2
libmongoc SSL => enabled
libmongoc SSL library => Secure Transport
libmongoc crypto => enabled
libmongoc crypto library => Common Crypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled

Directive => Local Value => Master Value
mongodb.debug => no value => no value

-------------

System24-PC-2:~ imran$ pecl list
Installed packages, channel pecl.php.net:
=========================================.
Package Version State
mongodb 1.5.3   stable

---------------

Thanks!

**Comment by jmikola** [comment]
@imrannazirbhat: If the extension is showing up in the CLI environment, I wonder if the `phpinfo()` output you shared earlier is from your web SAPI and you're not accounting for each environment having its own `php.ini` configuration. See https://github.com/mongodb/mongo-php-driver/issues/853#issuecomment-398530527 for a previous discussion on this, which includes instructions to determine which INI file each environment is loading.

Also, on the off chance you have multiple PHP runtimes on your system (e.g. version that ships with macOS, Homebrew, XAMPP or some other bundle), not that each of those will likely have its own `pecl` command as well.

**Comment by imrannazirbhat** [comment]
Thanks for your comment.

I did found an alternative by using MAMP now.

Thanks!!
