### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by stof** [mongodb/mongo-php-driver#942]
Hi,

What are the plans regarding support for PHP 7.3 (which is now stable) ?

**Comment by alcaeus** [comment]
We've been installing the driver in 7.3 builds for MongoDB ODM for a while and it works fine: https://travis-ci.org/doctrine/mongodb-odm/jobs/465159640#L535.

**Comment by derickr** [comment]
PHP 7.3 support should be available with the latest 1.6.1 release already.

**Comment by stof** [comment]
The CI is not running on 7.3 though AFAICT.
But it is true that the changelog for 1.5.3 mentions support for PHP 7.3, even though I missed it.

And 1.6.1 is not available on pecl.php.net. So is it actually released ?

**Comment by derickr** [comment]
Sorry, I meant 1.5.3 — 1.6.1 is for Xdebug (too many versions!). There is a pull request to add 7.3 to Travis, but 7.3.0 isn't on Travis yet: https://travis-ci.community/t/please-add-php-7-3-on-xenial/1238/8

**Comment by derickr** [comment]
Travis says they have 7.3.0 now, so doing: https://github.com/mongodb/mongo-php-driver/pull/944 — which I'll merge once Travis is happy.

**Comment by jmikola** [comment]
https://github.com/mongodb/mongo-php-driver/pull/944 will address this.
