### ISSUE TITLE
Support for updates with aggregation pipeline

### ISSUE THREAD

**Issue by timwhitlock** [mongodb/mongo-php-driver#994]
### Description

I'm unable to execute an [update with a pipeline](https://docs.mongodb.com/master/reference/command/update/index.html#update-with-aggregation-pipeline) such as using the new (upcoming) [aggregate $set operator](https://docs.mongodb.com/master/reference/operator/aggregation/set/#pipe._S_set). This fails before the command is executed as shown below.

I presume that support  simply hasn't been added yet, but can you say if/when it will be supported, or if there's a workaround I can use to execute this?

Thank you.

### Environment

PHP 7.2.16 on Mac OS X

Tried with latest stable driver 1.5.5 and also 1.6.0alpha2.

### Test Script

```
<?php
$batch = new MongoDB\Driver\BulkWrite(['ordered'=>true]);
$batch->update(
    [ ],
    [ [ '$set' => ['foo'=>'bar'] ] ], // <- aggregate pipeline
    [ 'limit' => 0 ]
);
```  

### Expected and Actual Behavior

Fails with MongoDB\Driver\Exception\InvalidArgumentException:

```
invalid argument for replace: keys cannot begin with "$": "$set"
```

**Comment by jmikola** [comment]
This feature is being tracked by [PHPC-1355](https://jira.mongodb.org/browse/PHPC-1355) and is scheduled for 1.6.0, which will be the 4.2-compatible release.

If you need an immediate work-around, you can craft the [`update` command](https://docs.mongodb.com/master/reference/command/update/#syntax) yourself and execute it with [`Manager::executeWriteCommand()`](https://www.php.net/manual/en/mongodb-driver-manager.executewritecommand.php).

Unlike `executeCommand()`, `executeWriteCommand()` will inherit any write concern you may have set via the connection string (or options). If you need to specify a write concern at the operation level, you can also pass it as an option to `executeWriteCommand()` (preferable to putting it directly into the command document).

**Comment by timwhitlock** [comment]
Thank you!
